const fs=require('fs'),path=require('path');
// words-007.json: ranks 1501-1750, B1/B2 level

function rV(id,rank,ita,eng,grp,ppAux,pp,ex,tags){
  const s=ita.replace(/(are|ere|ire)$/,'');
  let pres,impf,fut,cond,cong;
  if(grp==='are'){
    pres={io:s+'o',tu:s+'i',lui:s+'a',noi:s+'iamo',voi:s+'ate',loro:s+'ano'};
    impf={io:s+'avo',tu:s+'avi',lui:s+'ava',noi:s+'avamo',voi:s+'avate',loro:s+'avano'};
    fut={io:s+'erò',tu:s+'erai',lui:s+'erà',noi:s+'eremo',voi:s+'erete',loro:s+'eranno'};
    cond={io:s+'erei',tu:s+'eresti',lui:s+'erebbe',noi:s+'eremmo',voi:s+'ereste',loro:s+'erebbero'};
    cong={io:s+'i',tu:s+'i',lui:s+'i',noi:s+'iamo',voi:s+'iate',loro:s+'ino'};
  }else if(grp==='ere'){
    pres={io:s+'o',tu:s+'i',lui:s+'e',noi:s+'iamo',voi:s+'ete',loro:s+'ono'};
    impf={io:s+'evo',tu:s+'evi',lui:s+'eva',noi:s+'evamo',voi:s+'evate',loro:s+'evano'};
    fut={io:s+'erò',tu:s+'erai',lui:s+'erà',noi:s+'eremo',voi:s+'erete',loro:s+'eranno'};
    cond={io:s+'erei',tu:s+'eresti',lui:s+'erebbe',noi:s+'eremmo',voi:s+'ereste',loro:s+'erebbero'};
    cong={io:s+'a',tu:s+'a',lui:s+'a',noi:s+'iamo',voi:s+'iate',loro:s+'ano'};
  }else{
    const isc=/(finire|capire|costruire|pulire|guarire|preferire|spedire|obbedire|definire|stabilire|reagire|agire)$/.test(ita);
    const p=isc?s+'isc':s;
    pres={io:p+'o',tu:p+'i',lui:p+'e',noi:s+'iamo',voi:s+'ite',loro:p+'ono'};
    impf={io:s+'ivo',tu:s+'ivi',lui:s+'iva',noi:s+'ivamo',voi:s+'ivate',loro:s+'ivano'};
    fut={io:s+'irò',tu:s+'irai',lui:s+'irà',noi:s+'iremo',voi:s+'irete',loro:s+'iranno'};
    cond={io:s+'irei',tu:s+'iresti',lui:s+'irebbe',noi:s+'iremmo',voi:s+'ireste',loro:s+'irebbero'};
    cong={io:p+'a',tu:p+'a',lui:p+'a',noi:s+'iamo',voi:s+'iate',loro:p+'ano'};
  }
  const aux=ppAux==='avere';
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'verb',gender:null,plural:null,
    conjugationGroup:grp,irregular:false,
    conjugations:{presente:pres,passatoProssimo:{auxiliary:ppAux,pastParticiple:pp,
      io:(aux?'ho':'sono')+' '+pp,tu:(aux?'hai':'sei')+' '+pp,
      lui:(aux?'ha':'è')+' '+pp,noi:(aux?'abbiamo':'siamo')+' '+pp,
      voi:(aux?'avete':'siete')+' '+pp,loro:(aux?'hanno':'sono')+' '+pp},
      imperfetto:impf,futuroSemplice:fut,condizionale:cond,congiuntivoPresente:cong},
    irregularForms:null,examples:ex,tags,needsReview:false};
}
function n(id,rank,ita,eng,gender,plural,ex,tags){
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'noun',gender,plural,
    conjugationGroup:null,irregular:false,conjugations:null,irregularForms:null,examples:ex,tags,needsReview:false};
}
function adj(id,rank,ita,eng,plural,ex,tags){
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'adjective',gender:'masculine',plural,
    conjugationGroup:null,irregular:false,conjugations:null,irregularForms:null,examples:ex,tags,needsReview:false};
}
function adv(id,rank,ita,eng,ex,tags){
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'adverb',gender:null,plural:null,
    conjugationGroup:null,irregular:false,conjugations:null,irregularForms:null,examples:ex,tags,needsReview:false};
}

const e=[
// VERBS 1501-1560
rV('it_1501',1501,'stabilire','to establish','ire','avere','stabilito',['Stabiliamo le regole.'],['b1']),
rV('it_1502',1502,'determinare','to determine','are','avere','determinato',['Determina il risultato.'],['b1']),
rV('it_1503',1503,'influenzare','to influence','are','avere','influenzato',['Questo mi influenza.'],['b1']),
rV('it_1504',1504,'condizionare','to condition/influence','are','avere','condizionato',['Il passato mi condiziona.'],['b1']),
rV('it_1505',1505,'motivare','to motivate','are','avere','motivato',['Cosa ti motiva?'],['b1']),
rV('it_1506',1506,'ispirare','to inspire','are','avere','ispirato',['La natura mi ispira.'],['b1']),
rV('it_1507',1507,'stimolare','to stimulate','are','avere','stimolato',['Lo stimola a fare meglio.'],['b1']),
rV('it_1508',1508,'incoraggiare','to encourage','are','avere','incoraggiato',['Lo incoraggia ogni giorno.'],['b1']),
rV('it_1509',1509,'scoraggiare','to discourage','are','avere','scoraggiato',['Non ti scoraggiare.'],['b1']),
rV('it_1510',1510,'convincere','to convince','ere','avere','convinto',['Come ti convince?'],['b1']),
rV('it_1511',1511,'persuadere','to persuade','ere','avere','persuaso',['Persuade con gli argomenti.'],['b1']),
rV('it_1512',1512,'manipolare','to manipulate','are','avere','manipolato',['Non manipolare le persone.'],['b1']),
rV('it_1513',1513,'ingannare','to deceive','are','avere','ingannato',['Mi ha ingannato.'],['b1']),
rV('it_1514',1514,'tradire','to betray','ire','avere','tradito',['Ha tradito la fiducia.'],['b1']),
rV('it_1515',1515,'perdonare','to forgive','are','avere','perdonato',['Perdonami.'],['a2']),
rV('it_1516',1516,'riconciliarsi','to reconcile','are','essere','riconciliato',['Si sono riconciliati.'],['b1']),
rV('it_1517',1517,'litigare','to argue/quarrel','are','avere','litigato',['Litigano spesso.'],['a2']),
rV('it_1518',1518,'discutere','to discuss/argue','ere','avere','discusso',['Discutiamo del problema.'],['a2']),
rV('it_1519',1519,'dibattere','to debate','ere','avere','dibattuto',['Dibattiamo il tema.'],['b1']),
rV('it_1520',1520,'argomentare','to argue (a case)','are','avere','argomentato',['Argomenta la sua posizione.'],['b1']),
rV('it_1521',1521,'sostenere','to support/maintain','ere','avere','sostenuto',['Sostengo la tua idea.'],['b1']),
rV('it_1522',1522,'opporsi','to oppose','ere','essere','opposto',['Mi oppongo a questa decisione.'],['b1']),
rV('it_1523',1523,'resistere','to resist','ere','avere','resistito',['Resiste alla tentazione.'],['b1']),
rV('it_1524',1524,'cedere','to give in/yield','ere','avere','ceduto',['Non cedere!'],['b1']),
rV('it_1525',1525,'rinunciare','to give up/renounce','are','avere','rinunciato',['Non rinunciare ai tuoi sogni.'],['a2']),
rV('it_1526',1526,'persistere','to persist','ere','avere','persistito',['Persiste nei suoi sforzi.'],['b1']),
rV('it_1527',1527,'insistere','to insist','ere','avere','insistito',['Insiste nel voler venire.'],['a2']),
rV('it_1528',1528,'pretendere','to claim/demand','ere','avere','preteso',['Non pretendo troppo.'],['b1']),
rV('it_1529',1529,'esigere','to demand/require','ere','avere','esatto',['Esige rispetto.'],['b1']),
rV('it_1530',1530,'reclamare','to complain/claim','are','avere','reclamato',['Reclama il suo diritto.'],['b1']),
rV('it_1531',1531,'protestare','to protest','are','avere','protestato',['Protestano per i diritti.'],['a2']),
rV('it_1532',1532,'contestare','to contest/challenge','are','avere','contestato',['Contesta la decisione.'],['b1']),
rV('it_1533',1533,'approvare','to approve','are','avere','approvato',['Il parlamento approva la legge.'],['b1']),
rV('it_1534',1534,'disapprovare','to disapprove','are','avere','disapprovato',['Disapprova il suo comportamento.'],['b1']),
rV('it_1535',1535,'autorizzare','to authorize','are','avere','autorizzato',['Ti autorizzo a procedere.'],['b1']),
rV('it_1536',1536,'vietare','to forbid','are','avere','vietato',['È vietato fumare.'],['b1']),
rV('it_1537',1537,'obbligare','to oblige/force','are','avere','obbligato',['Non sei obbligato.'],['b1']),
rV('it_1538',1538,'costringere','to force/compel','ere','avere','costretto',['Mi ha costretto ad andare.'],['b1']),
rV('it_1539',1539,'coinvolgere','to involve','ere','avere','coinvolto',['Vuole coinvolgerti.'],['b1']),
rV('it_1540',1540,'impegnarsi','to commit/engage','are','essere','impegnato',['Mi impegno a farlo.'],['b1']),
rV('it_1541',1541,'dedicarsi','to dedicate oneself','are','essere','dedicato',['Si dedica al lavoro.'],['b1']),
rV('it_1542',1542,'concentrarsi','to concentrate','are','essere','concentrato',['Concentrati!'],['a2']),
rV('it_1543',1543,'rilassarsi','to relax','are','essere','rilassato',['Rilassati!'],['a2']),
rV('it_1544',1544,'stressarsi','to get stressed','are','essere','stressato',['Non stressarti.'],['a2']),
rV('it_1545',1545,'abusare','to abuse','are','avere','abusato',['Abusa della sua posizione.'],['b1']),
rV('it_1546',1546,'sfruttare','to exploit/use','are','avere','sfruttato',['Sfrutta le risorse.'],['b1']),
rV('it_1547',1547,'consumare','to consume','are','avere','consumato',['Consuma molta energia.'],['b1']),
rV('it_1548',1548,'sprecare','to waste','are','avere','sprecato',['Non sprecare il cibo.'],['a2']),
rV('it_1549',1549,'riciclare','to recycle','are','avere','riciclato',['Ricicla sempre.'],['a2']),
rV('it_1550',1550,'inquinare','to pollute','are','avere','inquinato',['Le fabbriche inquinano.'],['a2']),
rV('it_1551',1551,'proteggere','to protect','ere','avere','protetto',['Proteggi l\'ambiente.'],['a2']),
rV('it_1552',1552,'preservare','to preserve','are','avere','preservato',['Preserva la natura.'],['b1']),
rV('it_1553',1553,'conservare','to conserve/keep','are','avere','conservato',['Conserva i documenti.'],['a2']),
rV('it_1554',1554,'restaurare','to restore','are','avere','restaurato',['Restaura un dipinto antico.'],['b1']),
rV('it_1555',1555,'rinnovare','to renew','are','avere','rinnovato',['Rinnova il passaporto.'],['a2']),
rV('it_1556',1556,'sostituire','to replace','ire','avere','sostituito',['Sostituisce il vecchio modello.'],['b1']),
rV('it_1557',1557,'integrare','to integrate','are','avere','integrato',['Integra i dati.'],['b1']),
rV('it_1558',1558,'combinare','to combine','are','avere','combinato',['Combina i colori.'],['a2']),
rV('it_1559',1559,'separare','to separate','are','avere','separato',['Separa i rifiuti.'],['a2']),
rV('it_1560',1560,'dividere','to divide','ere','avere','diviso',['Divide il pane.'],['a2']),

// NOUNS 1561-1680
n('it_1561',1561,'approccio','approach','masculine','approcci',['Un approccio nuovo.'],['b1']),
n('it_1562',1562,'metodo','method','masculine','metodi',['Usiamo un metodo diverso.'],['b1']),
n('it_1563',1563,'procedura','procedure','feminine','procedure',['Segui la procedura.'],['b1']),
n('it_1564',1564,'processo','process','masculine','processi',['Il processo di apprendimento.'],['b1']),
n('it_1565',1565,'meccanismo','mechanism','masculine','meccanismi',['Il meccanismo funziona.'],['b1']),
n('it_1566',1566,'struttura','structure','feminine','strutture',['La struttura dell\'edificio.'],['b1']),
n('it_1567',1567,'schema','scheme/pattern','masculine','schemi',['Un schema logico.'],['b1']),
n('it_1568',1568,'modello','model','masculine','modelli',['Un modello di riferimento.'],['a2']),
n('it_1569',1569,'prototipo','prototype','masculine','prototipi',['Il prototipo è pronto.'],['b1']),
n('it_1570',1570,'versione','version','feminine','versioni',['La versione aggiornata.'],['a2']),
n('it_1571',1571,'formato','format','masculine','formati',['Il formato del file.'],['a2']),
n('it_1572',1572,'contenuto','content','masculine','contenuti',['Il contenuto è interessante.'],['a2']),
n('it_1573',1573,'forma','form/shape','feminine','forme',['In forma migliore.'],['a2']),
n('it_1574',1574,'dimensione','dimension/size','feminine','dimensioni',['Le dimensioni del problema.'],['b1']),
n('it_1575',1575,'scala','scale/staircase','feminine','scale',['Su larga scala.'],['b1']),
n('it_1576',1576,'proporzione','proportion','feminine','proporzioni',['Le proporzioni giuste.'],['b1']),
n('it_1577',1577,'percentuale','percentage','feminine','percentuali',['Una percentuale alta.'],['b1']),
n('it_1578',1578,'tasso','rate','masculine','tassi',['Il tasso di interesse.'],['b1']),
n('it_1579',1579,'media','average','feminine','medie',['La media è alta.'],['b1']),
n('it_1580',1580,'statistica','statistics','feminine','statistiche',['Le statistiche mostrano.'],['b1']),
n('it_1581',1581,'grafico','graph/chart','masculine','grafici',['Guarda il grafico.'],['b1']),
n('it_1582',1582,'tabella','table/chart','feminine','tabelle',['Consulta la tabella.'],['b1']),
n('it_1583',1583,'diagramma','diagram','masculine','diagrammi',['Un diagramma a barre.'],['b1']),
n('it_1584',1584,'mappa','map','feminine','mappe',['Ho una mappa.'],['a2']),
n('it_1585',1585,'piano','plan — see 429','masculine','piani',['Il piano d\'azione.'],['a2']),
n('it_1586',1586,'strategia','strategy','feminine','strategie',['Una strategia vincente.'],['b1']),
n('it_1587',1587,'tattica','tactic','feminine','tattiche',['Una tattica efficace.'],['b1']),
n('it_1588',1588,'priorità','priority','feminine','priorità',['È una priorità.'],['b1']),
n('it_1589',1589,'scadenza','deadline','feminine','scadenze',['La scadenza è domani.'],['b1']),
n('it_1590',1590,'termine','deadline/term','masculine','termini',['Il termine è vicino.'],['b1']),
n('it_1591',1591,'requisito','requirement','masculine','requisiti',['I requisiti del lavoro.'],['b1']),
n('it_1592',1592,'condizione','condition','feminine','condizioni',['Le condizioni sono buone.'],['b1']),
n('it_1593',1593,'presupposto','prerequisite/assumption','masculine','presupposti',['Un presupposto errato.'],['b1']),
n('it_1594',1594,'conseguenza','consequence','feminine','conseguenze',['Le conseguenze sono gravi.'],['b1']),
n('it_1595',1595,'implicazione','implication','feminine','implicazioni',['Le implicazioni sono molte.'],['b1']),
n('it_1596',1596,'impatto','impact','masculine','impatti',['L\'impatto è forte.'],['b1']),
n('it_1597',1597,'influenza','influence — see 909','feminine','influenze',['Ha avuto influenza.'],['b1']),
n('it_1598',1598,'pressione','pressure','feminine','pressioni',['Sotto pressione.'],['b1']),
n('it_1599',1599,'tensione','tension','feminine','tensioni',['C\'è molta tensione.'],['b1']),
n('it_1600',1600,'stress','stress','masculine',null,['Ho molto stress.'],['a2']),
n('it_1601',1601,'equilibrio','balance','masculine','equilibri',['Mantenere l\'equilibrio.'],['b1']),
n('it_1602',1602,'armonia','harmony','feminine','armonie',['Vivere in armonia.'],['b1']),
n('it_1603',1603,'conflitto','conflict — see 1368','masculine','conflitti',['—'],['a2']),
n('it_1604',1604,'contrasto','contrast','masculine','contrasti',['Un forte contrasto.'],['b1']),
n('it_1605',1605,'opposizione','opposition','feminine','opposizioni',['L\'opposizione vota contro.'],['b1']),
n('it_1606',1606,'resistenza','resistance','feminine','resistenze',['La resistenza al cambiamento.'],['b1']),
n('it_1607',1607,'ostacolo','obstacle','masculine','ostacoli',['Supera gli ostacoli.'],['b1']),
n('it_1608',1608,'barriera','barrier','feminine','barriere',['Una barriera linguistica.'],['b1']),
n('it_1609',1609,'limite','limit','masculine','limiti',['Conosci i tuoi limiti.'],['a2']),
n('it_1610',1610,'confine','boundary — see 846','masculine','confini',['I confini del possibile.'],['a2']),
n('it_1611',1611,'margine','margin','masculine','margini',['Con un piccolo margine.'],['b1']),
n('it_1612',1612,'tolleranza','tolerance','feminine','tolleranze',['La tolleranza è una virtù.'],['b1']),
n('it_1613',1613,'accettazione','acceptance','feminine','accettazioni',['L\'accettazione degli altri.'],['b1']),
n('it_1614',1614,'comprensione','understanding','feminine','comprensioni',['La comprensione reciproca.'],['a2']),
n('it_1615',1615,'empatia','empathy','feminine',null,['L\'empatia è importante.'],['b1']),
n('it_1616',1616,'compassione','compassion','feminine',null,['Mostra compassione.'],['b1']),
n('it_1617',1617,'gratitudine','gratitude','feminine',null,['Esprimo gratitudine.'],['b1']),
n('it_1618',1618,'riconoscenza','gratitude/recognition','feminine',null,['Sono pieno di riconoscenza.'],['b1']),
n('it_1619',1619,'apprezzamento','appreciation','masculine','apprezzamenti',['Il mio apprezzamento.'],['b1']),
n('it_1620',1620,'rispetto','respect — see 932','masculine',null,['—'],['a2']),
n('it_1621',1621,'stima','esteem','feminine','stime',['Ho grande stima per lui.'],['b1']),
n('it_1622',1622,'ammirazione','admiration','feminine','ammirazioni',['Suscita ammirazione.'],['b1']),
n('it_1623',1623,'invidia','envy — see 930','feminine','invidie',['—'],['a2']),
n('it_1624',1624,'gelosia','jealousy — see 929','feminine','gelosie',['—'],['a2']),
n('it_1625',1625,'rancore','resentment','masculine','rancori',['Nutro rancore.'],['b1']),
n('it_1626',1626,'vendetta','revenge','feminine','vendette',['Cerca vendetta.'],['b1']),
n('it_1627',1627,'giustizia','justice — see 595','feminine',null,['—'],['a2']),
n('it_1628',1628,'punizione','punishment','feminine','punizioni',['La punizione è severa.'],['b1']),
n('it_1629',1629,'ricompensa','reward','feminine','ricompense',['Una giusta ricompensa.'],['b1']),
n('it_1630',1630,'sacrificio','sacrifice','masculine','sacrifici',['Ha fatto un sacrificio.'],['b1']),
n('it_1631',1631,'impegno','commitment','masculine','impegni',['Rispetta gli impegni.'],['b1']),
n('it_1632',1632,'responsabilità','responsibility','feminine','responsabilità',['Una grande responsabilità.'],['a2']),
n('it_1633',1633,'dovere','duty — see 593','masculine','doveri',['—'],['a2']),
n('it_1634',1634,'obbligo','obligation','masculine','obblighi',['È un obbligo legale.'],['b1']),
n('it_1635',1635,'promessa','promise','feminine','promesse',['Mantieni le promesse.'],['a2']),
n('it_1636',1636,'giuramento','oath/vow','masculine','giuramenti',['Ha fatto giuramento.'],['b1']),
n('it_1637',1637,'patto','pact/agreement','masculine','patti',['Un patto di amicizia.'],['b1']),
n('it_1638',1638,'alleanza','alliance — see 1367','feminine','alleanze',['—'],['b1']),
n('it_1639',1639,'coalizione','coalition','feminine','coalizioni',['Una coalizione di partiti.'],['b1']),
n('it_1640',1640,'solidarietà','solidarity — see 935','feminine',null,['—'],['b1']),
n('it_1641',1641,'cooperazione','cooperation','feminine','cooperazioni',['Cooperazione internazionale.'],['b1']),
n('it_1642',1642,'competizione','competition','feminine','competizioni',['Una sana competizione.'],['b1']),
n('it_1643',1643,'rivalità','rivalry','feminine','rivalità',['Una storica rivalità.'],['b1']),
n('it_1644',1644,'confronto','confrontation/comparison','masculine','confronti',['Un confronto diretto.'],['b1']),
n('it_1645',1645,'negoziazione','negotiation','feminine','negoziazioni',['Una lunga negoziazione.'],['b1']),
n('it_1646',1646,'mediazione','mediation','feminine','mediazioni',['La mediazione ha funzionato.'],['b1']),
n('it_1647',1647,'arbitraggio','arbitration','masculine','arbitraggi',['Ricorriamo all\'arbitraggio.'],['b1']),
n('it_1648',1648,'sentenza','sentence/verdict','feminine','sentenze',['La sentenza è definitiva.'],['b1']),
n('it_1649',1649,'verdetto','verdict','masculine','verdetti',['Il verdetto è colpevole.'],['b1']),
n('it_1650',1650,'appello','appeal','masculine','appelli',['Fa appello.'],['b1']),
n('it_1651',1651,'processo','trial — see 1564','masculine','processi',['Il processo inizia.'],['b1']),
n('it_1652',1652,'giudice','judge','masculine','giudici',['Il giudice decide.'],['b1']),
n('it_1653',1653,'avvocato','lawyer — see 415','masculine','avvocati',['—'],['a2']),
n('it_1654',1654,'procuratore','prosecutor','masculine','procuratori',['Il procuratore della Repubblica.'],['b1']),
n('it_1655',1655,'testimone','witness','masculine','testimoni',['Il testimone parla.'],['b1']),
n('it_1656',1656,'prova','proof/evidence','feminine','prove',['Le prove sono chiare.'],['a2']),
n('it_1657',1657,'accusa','accusation','feminine','accuse',['Respinge le accuse.'],['b1']),
n('it_1658',1658,'difesa','defense','feminine','difese',['La difesa parla.'],['b1']),
n('it_1659',1659,'colpevole','guilty person','masculine','colpevoli',['Il colpevole è stato trovato.'],['b1']),
n('it_1660',1660,'innocente','innocent person','masculine','innocenti',['È innocente.'],['b1']),
n('it_1661',1661,'reato','crime/offense','masculine','reati',['Ha commesso un reato.'],['b1']),
n('it_1662',1662,'crimine','crime','masculine','crimini',['Un crimine grave.'],['b1']),
n('it_1663',1663,'furto','theft','masculine','furti',['Ha denunciato il furto.'],['b1']),
n('it_1664',1664,'rapina','robbery','feminine','rapine',['Una rapina in banca.'],['b1']),
n('it_1665',1665,'frode','fraud','feminine','frodi',['Accusato di frode.'],['b1']),
n('it_1666',1666,'corruzione','corruption','feminine',null,['La corruzione è un problema.'],['b1']),
n('it_1667',1667,'illegalità','illegality','feminine',null,['Atti di illegalità.'],['b1']),
n('it_1668',1668,'trasparenza','transparency','feminine',null,['La trasparenza è fondamentale.'],['b1']),
n('it_1669',1669,'integrità','integrity','feminine',null,['Agisce con integrità.'],['b1']),
n('it_1670',1670,'etica','ethics','feminine',null,['L\'etica professionale.'],['b1']),

// ADJECTIVES 1671-1720
adj('it_1671',1671,'astratto','abstract','astratti',['Un concetto astratto.'],['b1']),
adj('it_1672',1672,'concreto','concrete/tangible','concreti',['Un esempio concreto.'],['b1']),
adj('it_1673',1673,'tangibile','tangible','tangibili',['Un risultato tangibile.'],['b1']),
adj('it_1674',1674,'intangibile','intangible','intangibili',['Un valore intangibile.'],['b1']),
adj('it_1675',1675,'visibile','visible','visibili',['Un cambiamento visibile.'],['b1']),
adj('it_1676',1676,'invisibile','invisible','invisibili',['Un confine invisibile.'],['b1']),
adj('it_1677',1677,'evidente','evident','evidenti',['È evidente.'],['b1']),
adj('it_1678',1678,'ovvio','obvious','ovvi',['È ovvio.'],['a2']),
adj('it_1679',1679,'implicito','implicit','impliciti',['Un accordo implicito.'],['b1']),
adj('it_1680',1680,'esplicito','explicit','espliciti',['Una risposta esplicita.'],['b1']),
adj('it_1681',1681,'letterale','literal','letterali',['Il significato letterale.'],['b1']),
adj('it_1682',1682,'figurato','figurative','figurati',['In senso figurato.'],['b1']),
adj('it_1683',1683,'formale','formal — see 1168','formali',['—'],['a2']),
adj('it_1684',1684,'sostanziale','substantial','sostanziali',['Una differenza sostanziale.'],['b1']),
adj('it_1685',1685,'marginale','marginal','marginali',['Una differenza marginale.'],['b1']),
adj('it_1686',1686,'critico','critical','critici',['Una situazione critica.'],['b1']),
adj('it_1687',1687,'urgente','urgent','urgenti',['È urgente!'],['a2']),
adj('it_1688',1688,'imminente','imminent','imminenti',['È imminente.'],['b1']),
adj('it_1689',1689,'immediato','immediate','immediati',['Una risposta immediata.'],['a2']),
adj('it_1690',1690,'ritardato','delayed','ritardati',['Un pagamento ritardato.'],['b1']),
adj('it_1691',1691,'temporaneo','temporary','temporanei',['Una soluzione temporanea.'],['b1']),
adj('it_1692',1692,'permanente','permanent','permanenti',['Un lavoro permanente.'],['b1']),
adj('it_1693',1693,'duraturo','lasting','duraturi',['Un cambiamento duraturo.'],['b1']),
adj('it_1694',1694,'effimero','ephemeral','effimeri',['Un momento effimero.'],['b1']),
adj('it_1695',1695,'eterno','eternal','eterni',['Un amore eterno.'],['b1']),
adj('it_1696',1696,'infinito','infinite','infiniti',['Un universo infinito.'],['b1']),
adj('it_1697',1697,'finito','finite/finished','finiti',['Le risorse finite.'],['b1']),
adj('it_1698',1698,'illimitato','unlimited','illimitati',['Potenziale illimitato.'],['b1']),
adj('it_1699',1699,'limitato','limited','limitati',['Risorse limitate.'],['a2']),
adj('it_1700',1700,'abbordabile','affordable','abbordabili',['Un prezzo abbordabile.'],['b1']),

// ADVERBS 1701-1750
adv('it_1701',1701,'letteralmente','literally',['È letteralmente impossibile.'],['b1']),
adv('it_1702',1702,'virtualmente','virtually',['È virtualmente identico.'],['b1']),
adv('it_1703',1703,'praticamente','practically',['È praticamente finito.'],['a2']),
adv('it_1704',1704,'sostanzialmente','substantially',['È sostanzialmente corretto.'],['b1']),
adv('it_1705',1705,'marginalmente','marginally',['È marginalmente diverso.'],['b1']),
adv('it_1706',1706,'radicalmente','radically',['È radicalmente cambiato.'],['b1']),
adv('it_1707',1707,'profondamente','profoundly',['Mi ha profondamente colpito.'],['b1']),
adv('it_1708',1708,'superficialmente','superficially',['Conosce superficialmente.'],['b1']),
adv('it_1709',1709,'ampiamente','widely/broadly',['È ampiamente diffuso.'],['b1']),
adv('it_1710',1710,'strettamente','strictly/closely',['È strettamente legato.'],['b1']),
adv('it_1711',1711,'direttamente','directly',['Ti dico direttamente.'],['b1']),
adv('it_1712',1712,'indirettamente','indirectly',['Lo influenza indirettamente.'],['b1']),
adv('it_1713',1713,'formalmente','formally',['Si è formalmente scusato.'],['b1']),
adv('it_1714',1714,'informalmente','informally',['Ne abbiamo parlato informalmente.'],['b1']),
adv('it_1715',1715,'pubblicamente','publicly',['Lo ha detto pubblicamente.'],['b1']),
adv('it_1716',1716,'privatamente','privately',['Ne parliamo privatamente.'],['b1']),
adv('it_1717',1717,'apertamente','openly',['Lo ha detto apertamente.'],['b1']),
adv('it_1718',1718,'segretamente','secretly',['L\'ha fatto segretamente.'],['b1']),
adv('it_1719',1719,'ufficialmente','officially',['È ufficialmente aperto.'],['b1']),
adv('it_1720',1720,'ufficiosa mente','unofficially',['Ufficiosa mente sì.'],['b1']),
adv('it_1721',1721,'legalmente','legally',['È legalmente valido.'],['b1']),
adv('it_1722',1722,'illegalmente','illegally',['Ha agito illegalmente.'],['b1']),
adv('it_1723',1723,'moralmente','morally — see 1250','moralmente',['—'],['b1']),
adv('it_1724',1724,'eticamente','ethically — see 1249','eticamente',['—'],['b1']),
adv('it_1725',1725,'equamente','fairly/equitably',['È distribuito equamente.'],['b1']),
adv('it_1726',1726,'ingiustamente','unjustly',['È stato trattato ingiustamente.'],['b1']),
adv('it_1727',1727,'seriamente','seriously',['Prendilo seriamente.'],['a2']),
adv('it_1728',1728,'scherzosamente','jokingly',['Lo ha detto scherzosamente.'],['b1']),
adv('it_1729',1729,'ironicamente','ironically',['Ironicamente, ha fallito.'],['b1']),
adv('it_1730',1730,'paradossalmente','paradoxically',['Paradossalmente, ha migliorato.'],['b1']),
adv('it_1731',1731,'sorprendentemente','surprisingly',['Sorprendentemente è riuscito.'],['b1']),
adv('it_1732',1732,'stranamente','strangely',['Stranamente non ha chiamato.'],['b1']),
adv('it_1733',1733,'curiosamente','curiously',['Curiosamente ha taciuto.'],['b1']),
adv('it_1734',1734,'significativamente','significantly',['È migliorato significativamente.'],['b1']),
adv('it_1735',1735,'notevolmente','notably/considerably',['È migliorato notevolmente.'],['b1']),
adv('it_1736',1736,'considerevolmente','considerably',['Il prezzo è sceso considerevolmente.'],['b1']),
adv('it_1737',1737,'drammaticamente','dramatically',['È cambiato drammaticamente.'],['b1']),
adv('it_1738',1738,'repentinamente','suddenly/abruptly',['È cambiato repentinamente.'],['b1']),
adv('it_1739',1739,'gradatamente','gradually/step by step',['Migliorerò gradatamente.'],['b1']),
adv('it_1740',1740,'lentamente','slowly — see 393','lentamente',['—'],['a1']),
adv('it_1741',1741,'velocemente','quickly — see 394','velocemente',['—'],['a1']),
adv('it_1742',1742,'prontamente','promptly',['Ha risposto prontamente.'],['b1']),
adv('it_1743',1743,'tempestivamente','timely',['Ha agito tempestivamente.'],['b1']),
adv('it_1744',1744,'tardivamente','belatedly',['Ha capito tardivamente.'],['b1']),
adv('it_1745',1745,'prematuramente','prematurely',['È finito prematuramente.'],['b1']),
adv('it_1746',1746,'improvvisamente','suddenly — see 392','improvvisamente',['—'],['a2']),
adv('it_1747',1747,'all\'improvviso','all of a sudden',['All\'improvviso è arrivato.'],['b1']),
adv('it_1748',1748,'a poco a poco','little by little',['A poco a poco migliora.'],['a2']),
adv('it_1749',1749,'piano piano','slowly/gradually',['Piano piano ce la farà.'],['a2']),
adv('it_1750',1750,'passo dopo passo','step by step',['Passo dopo passo.'],['a2']),
];

const final=e.filter(x=>!x.examples[0].startsWith('—'));
console.log(`Generated ${final.length} entries, ranks ${final[0].rank}-${final[final.length-1].rank}`);
const ranks=final.map(x=>x.rank);
const dups=ranks.filter((r,i)=>ranks.indexOf(r)!==i);
if(dups.length) console.warn('Dups:',dups);
fs.writeFileSync(path.join(__dirname,'../src/data/words-007.json'),JSON.stringify(final,null,2));
console.log('words-007.json written.');
