const fs = require('fs');
const path = require('path');

// words-004.json: ranks 751-1000, IDs it_0751-it_1000, A2/B1 level

function v(id,rank,ita,eng,grp,irr,pres,ppAux,pp,ppF,impf,fut,cond,cong,irregF,ex,tags){
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'verb',gender:null,plural:null,
    conjugationGroup:grp,irregular:irr,
    conjugations:{presente:pres,passatoProssimo:{auxiliary:ppAux,pastParticiple:pp,...ppF},
      imperfetto:impf,futuroSemplice:fut,condizionale:cond,congiuntivoPresente:cong},
    irregularForms:irregF||null,examples:ex,tags,needsReview:false};
}
function n(id,rank,ita,eng,gender,plural,ex,tags,irr=false){
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'noun',gender,plural,
    conjugationGroup:null,irregular:irr,conjugations:null,irregularForms:null,examples:ex,tags,needsReview:false};
}
function adj(id,rank,ita,eng,plural,ex,tags){
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'adjective',gender:'masculine',plural,
    conjugationGroup:null,irregular:false,conjugations:null,irregularForms:null,examples:ex,tags,needsReview:false};
}
function adv(id,rank,ita,eng,ex,tags){
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'adverb',gender:null,plural:null,
    conjugationGroup:null,irregular:false,conjugations:null,irregularForms:null,examples:ex,tags,needsReview:false};
}

const entries=[
// ── VERBS 751-820 ──────────────────────────────────────────────────────────
v('it_0751',751,'costruire','to build/construct','ire',false,
  {io:'costruisco',tu:'costruisci',lui:'costruisce',noi:'costruiamo',voi:'costruite',loro:'costruiscono'},
  'avere','costruito',{io:'ho costruito',tu:'hai costruito',lui:'ha costruito',noi:'abbiamo costruito',voi:'avete costruito',loro:'hanno costruito'},
  {io:'costruivo',tu:'costruivi',lui:'costruiva',noi:'costruivamo',voi:'costruivate',loro:'costruivano'},
  {io:'costruirò',tu:'costruirai',lui:'costruirà',noi:'costruiremo',voi:'costruirete',loro:'costruiranno'},
  {io:'costruirei',tu:'costruiresti',lui:'costruirebbe',noi:'costruiremmo',voi:'costruireste',loro:'costruirebbero'},
  {io:'costruisca',tu:'costruisca',lui:'costruisca',noi:'costruiamo',voi:'costruiate',loro:'costruiscano'},
  null,['Stanno costruendo una casa.'],['a2']),

v('it_0752',752,'distruggere','to destroy','ere',false,
  {io:'distruggo',tu:'distruggi',lui:'distrugge',noi:'distruggiamo',voi:'distruggete',loro:'distruggono'},
  'avere','distrutto',{io:'ho distrutto',tu:'hai distrutto',lui:'ha distrutto',noi:'abbiamo distrutto',voi:'avete distrutto',loro:'hanno distrutto'},
  {io:'distruggevo',tu:'distruggevi',lui:'distruggeva',noi:'distruggevamo',voi:'distruggevate',loro:'distruggevano'},
  {io:'distruggerò',tu:'distruggerai',lui:'distruggerà',noi:'distruggeremo',voi:'distruggerete',loro:'distruggeranno'},
  {io:'distruggerei',tu:'distruggeresti',lui:'distruggerebbe',noi:'distruggeremmo',voi:'distruggereste',loro:'distruggerebbero'},
  {io:'distrugga',tu:'distrugga',lui:'distrugga',noi:'distruggiamo',voi:'distruggiate',loro:'distruggano'},
  {pastParticiple:'distrutto'},['La guerra distrugge tutto.'],['a2']),

v('it_0753',753,'aggiungere','to add','ere',false,
  {io:'aggiungo',tu:'aggiungi',lui:'aggiunge',noi:'aggiungiamo',voi:'aggiungete',loro:'aggiungono'},
  'avere','aggiunto',{io:'ho aggiunto',tu:'hai aggiunto',lui:'ha aggiunto',noi:'abbiamo aggiunto',voi:'avete aggiunto',loro:'hanno aggiunto'},
  {io:'aggiungevo',tu:'aggiungevi',lui:'aggiungeva',noi:'aggingevamo',voi:'aggingevate',loro:'aggiungevano'},
  {io:'aggiungerò',tu:'aggiungerai',lui:'aggiungerà',noi:'aggiungeremo',voi:'aggiungerete',loro:'aggiungeranno'},
  {io:'aggiungerei',tu:'aggiungeresti',lui:'aggiungerebbe',noi:'aggiungeremmo',voi:'aggiungereste',loro:'aggiungerebbero'},
  {io:'aggiunga',tu:'aggiunga',lui:'aggiunga',noi:'aggiungiamo',voi:'aggiungiate',loro:'aggiungano'},
  {pastParticiple:'aggiunto'},['Aggiungi il sale.'],['a2']),

v('it_0754',754,'togliere','to remove/take off','ere',true,
  {io:'tolgo',tu:'togli',lui:'toglie',noi:'togliamo',voi:'togliete',loro:'tolgono'},
  'avere','tolto',{io:'ho tolto',tu:'hai tolto',lui:'ha tolto',noi:'abbiamo tolto',voi:'avete tolto',loro:'hanno tolto'},
  {io:'toglievo',tu:'toglievi',lui:'toglieva',noi:'toglievamo',voi:'toglievate',loro:'toglievano'},
  {io:'toglierò',tu:'toglierai',lui:'toglierà',noi:'toglieremo',voi:'toglierete',loro:'toglieranno'},
  {io:'toglierei',tu:'toglieresti',lui:'toglierebbe',noi:'toglieremmo',voi:'togliereste',loro:'toglierebbero'},
  {io:'tolga',tu:'tolga',lui:'tolga',noi:'togliamo',voi:'togliate',loro:'tolgano'},
  {presente:'tolgo',pastParticiple:'tolto'},['Togliti le scarpe.'],['a2']),

v('it_0755',755,'includere','to include','ere',false,
  {io:'includo',tu:'includi',lui:'include',noi:'includiamo',voi:'includete',loro:'includono'},
  'avere','incluso',{io:'ho incluso',tu:'hai incluso',lui:'ha incluso',noi:'abbiamo incluso',voi:'avete incluso',loro:'hanno incluso'},
  {io:'includevo',tu:'includevi',lui:'includeva',noi:'includevamo',voi:'includevate',loro:'includevano'},
  {io:'includerò',tu:'includerai',lui:'includerà',noi:'includeremo',voi:'includerete',loro:'includeranno'},
  {io:'includerei',tu:'includeresti',lui:'includerebbe',noi:'includeremmo',voi:'includereste',loro:'includerebbero'},
  {io:'includa',tu:'includa',lui:'includa',noi:'includiamo',voi:'includiate',loro:'includano'},
  {pastParticiple:'incluso'},['Il prezzo include la colazione.'],['a2']),

v('it_0756',756,'escludere','to exclude','ere',false,
  {io:'escludo',tu:'escludi',lui:'esclude',noi:'escludiamo',voi:'escludete',loro:'escludono'},
  'avere','escluso',{io:'ho escluso',tu:'hai escluso',lui:'ha escluso',noi:'abbiamo escluso',voi:'avete escluso',loro:'hanno escluso'},
  {io:'escludevo',tu:'escludevi',lui:'escludeva',noi:'escludevamo',voi:'escludevate',loro:'escludevano'},
  {io:'escluderò',tu:'escluderai',lui:'escluderà',noi:'escluderemo',voi:'escluderete',loro:'escluderanno'},
  {io:'escluderei',tu:'escluderesti',lui:'escluderebbe',noi:'escluderemmo',voi:'escludereste',loro:'escluderebbero'},
  {io:'escluda',tu:'escluda',lui:'escluda',noi:'escludiamo',voi:'escludiate',loro:'escludano'},
  {pastParticiple:'escluso'},['Non escludere nessuno.'],['a2']),

v('it_0757',757,'mantenere','to maintain/keep','ere',true,
  {io:'mantengo',tu:'mantieni',lui:'mantiene',noi:'manteniamo',voi:'mantenete',loro:'mantengono'},
  'avere','mantenuto',{io:'ho mantenuto',tu:'hai mantenuto',lui:'ha mantenuto',noi:'abbiamo mantenuto',voi:'avete mantenuto',loro:'hanno mantenuto'},
  {io:'mantenevo',tu:'mantenevi',lui:'manteneva',noi:'manenevamo',voi:'manenevate',loro:'mantenevano'},
  {io:'manterrò',tu:'manterrai',lui:'manterrà',noi:'manterremo',voi:'manterrete',loro:'manterranno'},
  {io:'manterrei',tu:'manterresti',lui:'manterrebbe',noi:'manterremmo',voi:'manterreste',loro:'manterrebbero'},
  {io:'mantenga',tu:'mantenga',lui:'mantenga',noi:'manteniamo',voi:'manteniate',loro:'mantengano'},
  {presente:'mantengo',futuro:'manterrò'},['Mantieni la calma.'],['a2']),

v('it_0758',758,'ottenere','to obtain/get','ere',true,
  {io:'ottengo',tu:'ottieni',lui:'ottiene',noi:'otteniamo',voi:'ottenete',loro:'ottengono'},
  'avere','ottenuto',{io:'ho ottenuto',tu:'hai ottenuto',lui:'ha ottenuto',noi:'abbiamo ottenuto',voi:'avete ottenuto',loro:'hanno ottenuto'},
  {io:'ottenevo',tu:'ottenevi',lui:'otteneva',noi:'ottenevamo',voi:'ottenevate',loro:'ottenevano'},
  {io:'otterrò',tu:'otterrai',lui:'otterrà',noi:'otterremo',voi:'otterrete',loro:'otterranno'},
  {io:'otterrei',tu:'otterresti',lui:'otterrebbe',noi:'otterremmo',voi:'otterreste',loro:'otterrebbero'},
  {io:'ottenga',tu:'ottenga',lui:'ottenga',noi:'otteniamo',voi:'otteniate',loro:'ottengano'},
  {presente:'ottengo',futuro:'otterrò'},['Ho ottenuto il permesso.'],['a2']),

v('it_0759',759,'dipendere','to depend','ere',false,
  {io:'dipendo',tu:'dipendi',lui:'dipende',noi:'dipendiamo',voi:'dipendete',loro:'dipendono'},
  'essere','dipeso',{io:'sono dipeso',tu:'sei dipeso',lui:'è dipeso',noi:'siamo dipesi',voi:'siete dipesi',loro:'sono dipesi'},
  {io:'dipendevo',tu:'dipendevi',lui:'dipendeva',noi:'dipendevamo',voi:'dipendevate',loro:'dipendevano'},
  {io:'dipenderò',tu:'dipenderai',lui:'dipenderà',noi:'dipenderemo',voi:'dipenderete',loro:'dipenderanno'},
  {io:'dipenderei',tu:'dipenderesti',lui:'dipenderebbe',noi:'dipenderemmo',voi:'dipendereste',loro:'dipenderebbero'},
  {io:'dipenda',tu:'dipenda',lui:'dipenda',noi:'dipendiamo',voi:'dipendiate',loro:'dipendano'},
  {pastParticiple:'dipeso'},['Dipende dalle circostanze.'],['a2']),

v('it_0760',760,'rendere','to make/render/return','ere',false,
  {io:'rendo',tu:'rendi',lui:'rende',noi:'rendiamo',voi:'rendete',loro:'rendono'},
  'avere','reso',{io:'ho reso',tu:'hai reso',lui:'ha reso',noi:'abbiamo reso',voi:'avete reso',loro:'hanno reso'},
  {io:'rendevo',tu:'rendevi',lui:'rendeva',noi:'rendevamo',voi:'rendevate',loro:'rendevano'},
  {io:'renderò',tu:'renderai',lui:'renderà',noi:'renderemo',voi:'renderete',loro:'renderanno'},
  {io:'renderei',tu:'renderesti',lui:'renderebbe',noi:'renderemmo',voi:'rendereste',loro:'renderebbero'},
  {io:'renda',tu:'renda',lui:'renda',noi:'rendiamo',voi:'rendiate',loro:'rendano'},
  {pastParticiple:'reso'},['Questo mi rende felice.'],['a2']),

v('it_0761',761,'rappresentare','to represent','are',false,
  {io:'rappresento',tu:'rappresenti',lui:'rappresenta',noi:'rappresentiamo',voi:'rappresentate',loro:'rappresentano'},
  'avere','rappresentato',{io:'ho rappresentato',tu:'hai rappresentato',lui:'ha rappresentato',noi:'abbiamo rappresentato',voi:'avete rappresentato',loro:'hanno rappresentato'},
  {io:'rappresentavo',tu:'rappresentavi',lui:'rappresentava',noi:'rappresentavamo',voi:'rappresentavate',loro:'rappresentavano'},
  {io:'rappresenterò',tu:'rappresenterai',lui:'rappresenterà',noi:'rappresenteremo',voi:'rappresenterete',loro:'rappresenteranno'},
  {io:'rappresenterei',tu:'rappresenteresti',lui:'rappresenterebbe',noi:'rappresenteremmo',voi:'rappresentereste',loro:'rappresenterebbero'},
  {io:'rappresenti',tu:'rappresenti',lui:'rappresenti',noi:'rappresentiamo',voi:'rappresentiate',loro:'rappresentino'},
  null,['Rappresenta la sua nazione.'],['a2']),

v('it_0762',762,'indicare','to indicate/point','are',false,
  {io:'indico',tu:'indichi',lui:'indica',noi:'indichiamo',voi:'indicate',loro:'indicano'},
  'avere','indicato',{io:'ho indicato',tu:'hai indicato',lui:'ha indicato',noi:'abbiamo indicato',voi:'avete indicato',loro:'hanno indicato'},
  {io:'indicavo',tu:'indicavi',lui:'indicava',noi:'indicavamo',voi:'indicavate',loro:'indicavano'},
  {io:'indicherò',tu:'indicherai',lui:'indicherà',noi:'indicheremo',voi:'indicherete',loro:'indicheranno'},
  {io:'indicherei',tu:'indicheresti',lui:'indicherebbe',noi:'indicheremmo',voi:'indichereste',loro:'indicherebbero'},
  {io:'indichi',tu:'indichi',lui:'indichi',noi:'indichiamo',voi:'indichiate',loro:'indichino'},
  null,['Indica la direzione.'],['a2']),

v('it_0763',763,'notare','to notice/note','are',false,
  {io:'noto',tu:'noti',lui:'nota',noi:'notiamo',voi:'notate',loro:'notano'},
  'avere','notato',{io:'ho notato',tu:'hai notato',lui:'ha notato',noi:'abbiamo notato',voi:'avete notato',loro:'hanno notato'},
  {io:'notavo',tu:'notavi',lui:'notava',noi:'notavamo',voi:'notavate',loro:'notavano'},
  {io:'noterò',tu:'noterai',lui:'noterà',noi:'noteremo',voi:'noterete',loro:'noteranno'},
  {io:'noterei',tu:'noteresti',lui:'noterebbe',noi:'noteremmo',voi:'notereste',loro:'noterebbero'},
  {io:'noti',tu:'noti',lui:'noti',noi:'notiamo',voi:'notiate',loro:'notino'},
  null,['Hai notato qualcosa di strano?'],['a2']),

v('it_0764',764,'apprendere','to learn/grasp','ere',false,
  {io:'apprendo',tu:'apprendi',lui:'apprende',noi:'apprendiamo',voi:'apprendete',loro:'apprendono'},
  'avere','appreso',{io:'ho appreso',tu:'hai appreso',lui:'ha appreso',noi:'abbiamo appreso',voi:'avete appreso',loro:'hanno appreso'},
  {io:'apprendevo',tu:'apprendevi',lui:'apprendeva',noi:'appredevamo',voi:'appredevate',loro:'apprendevano'},
  {io:'apprenderò',tu:'apprenderai',lui:'apprenderà',noi:'apprenderemo',voi:'apprenderete',loro:'apprenderanno'},
  {io:'apprenderei',tu:'apprenderesti',lui:'apprenderebbe',noi:'apprenderemmo',voi:'apprendereste',loro:'apprenderebbero'},
  {io:'apprenda',tu:'apprenda',lui:'apprenda',noi:'apprendiamo',voi:'apprendiate',loro:'apprendano'},
  {pastParticiple:'appreso'},['Ho appreso la notizia.'],['b1']),

v('it_0765',765,'comprendere','to understand/include','ere',false,
  {io:'comprendo',tu:'comprendi',lui:'comprende',noi:'comprendiamo',voi:'comprendete',loro:'comprendono'},
  'avere','compreso',{io:'ho compreso',tu:'hai compreso',lui:'ha compreso',noi:'abbiamo compreso',voi:'avete compreso',loro:'hanno compreso'},
  {io:'comprendevo',tu:'comprendevi',lui:'comprendeva',noi:'comprendevamo',voi:'comprendevate',loro:'comprendevano'},
  {io:'comprenderò',tu:'comprenderai',lui:'comprenderà',noi:'comprenderemo',voi:'comprenderete',loro:'comprenderanno'},
  {io:'comprenderei',tu:'comprenderesti',lui:'comprenderebbe',noi:'comprenderemmo',voi:'comprendereste',loro:'comprenderebbero'},
  {io:'comprenda',tu:'comprenda',lui:'comprenda',noi:'comprendiamo',voi:'comprendiate',loro:'comprendano'},
  {pastParticiple:'compreso'},['Non comprendo il problema.'],['a2']),

v('it_0766',766,'spendere','to spend (money)','ere',false,
  {io:'spendo',tu:'spendi',lui:'spende',noi:'spendiamo',voi:'spendete',loro:'spendono'},
  'avere','speso',{io:'ho speso',tu:'hai speso',lui:'ha speso',noi:'abbiamo speso',voi:'avete speso',loro:'hanno speso'},
  {io:'spendevo',tu:'spendevi',lui:'spendeva',noi:'spendevamo',voi:'spendevate',loro:'spendevano'},
  {io:'spenderò',tu:'spenderai',lui:'spenderà',noi:'spenderemo',voi:'spenderete',loro:'spenderanno'},
  {io:'spenderei',tu:'spenderesti',lui:'spenderebbe',noi:'spenderemmo',voi:'spendereste',loro:'spenderebbero'},
  {io:'spenda',tu:'spenda',lui:'spenda',noi:'spendiamo',voi:'spendiate',loro:'spendano'},
  {pastParticiple:'speso'},['Quanto hai speso?'],['a1']),

v('it_0767',767,'guadagnare','to earn/win','are',false,
  {io:'guadagno',tu:'guadagni',lui:'guadagna',noi:'guadagniamo',voi:'guadagnate',loro:'guadagnano'},
  'avere','guadagnato',{io:'ho guadagnato',tu:'hai guadagnato',lui:'ha guadagnato',noi:'abbiamo guadagnato',voi:'avete guadagnato',loro:'hanno guadagnato'},
  {io:'guadagnavo',tu:'guadagnavi',lui:'guadagnava',noi:'guadagnavamo',voi:'guadagnavate',loro:'guadagnavano'},
  {io:'guadagnerò',tu:'guadagnerai',lui:'guadagnerà',noi:'guadagneremo',voi:'guadagnerete',loro:'guadagneranno'},
  {io:'guadagnerei',tu:'guadagneresti',lui:'guadagnerebbe',noi:'guadagneremmo',voi:'guadagnereste',loro:'guadagnerebbero'},
  {io:'guadagni',tu:'guadagni',lui:'guadagni',noi:'guadagniamo',voi:'guadagniate',loro:'guadagnino'},
  null,['Quanto guadagni?'],['a2']),

v('it_0768',768,'risparmiare','to save (money)','are',false,
  {io:'risparmio',tu:'risparmi',lui:'risparmia',noi:'risparmiamo',voi:'risparmiate',loro:'risparmiano'},
  'avere','risparmiato',{io:'ho risparmiato',tu:'hai risparmiato',lui:'ha risparmiato',noi:'abbiamo risparmiato',voi:'avete risparmiato',loro:'hanno risparmiato'},
  {io:'risparmiavo',tu:'risparmiavi',lui:'risparmiava',noi:'risparmiavamo',voi:'risparmiavate',loro:'risparmiavano'},
  {io:'risparmierò',tu:'risparmierai',lui:'risparmierà',noi:'risparmieremo',voi:'risparmierete',loro:'risparmieranno'},
  {io:'risparmierei',tu:'risparmieresti',lui:'risparmierebbe',noi:'risparmieremmo',voi:'risparmiereste',loro:'risparmierebbero'},
  {io:'risparmi',tu:'risparmi',lui:'risparmi',noi:'risparmiamo',voi:'risparmiate',loro:'risparmino'},
  null,['Devo risparmiare di più.'],['a2']),

v('it_0769',769,'investire','to invest','ire',false,
  {io:'investo',tu:'investi',lui:'investe',noi:'investiamo',voi:'investite',loro:'investono'},
  'avere','investito',{io:'ho investito',tu:'hai investito',lui:'ha investito',noi:'abbiamo investito',voi:'avete investito',loro:'hanno investito'},
  {io:'investivo',tu:'investivi',lui:'investiva',noi:'investivamo',voi:'investivate',loro:'investivano'},
  {io:'investirò',tu:'investirai',lui:'investirà',noi:'investiremo',voi:'investirete',loro:'investiranno'},
  {io:'investirei',tu:'investiresti',lui:'investirebbe',noi:'investiremmo',voi:'investireste',loro:'investirebbero'},
  {io:'investa',tu:'investa',lui:'investa',noi:'investiamo',voi:'investiate',loro:'investano'},
  null,['Vuole investire in borsa.'],['b1']),

v('it_0770',770,'prevedere','to foresee/expect','ere',true,
  {io:'prevedo',tu:'prevedi',lui:'prevede',noi:'prevediamo',voi:'prevedete',loro:'prevedono'},
  'avere','previsto',{io:'ho previsto',tu:'hai previsto',lui:'ha previsto',noi:'abbiamo previsto',voi:'avete previsto',loro:'hanno previsto'},
  {io:'prevedevo',tu:'prevedevi',lui:'prevedeva',noi:'prevedevamo',voi:'prevedevate',loro:'prevedevano'},
  {io:'prevederò',tu:'prevederai',lui:'prevederà',noi:'prevederemo',voi:'prevederete',loro:'prevederanno'},
  {io:'prevederei',tu:'prevederesti',lui:'prevederebbe',noi:'prevederemmo',voi:'prevedereste',loro:'prevederebbero'},
  {io:'preveda',tu:'preveda',lui:'preveda',noi:'prevediamo',voi:'prevediate',loro:'prevedano'},
  {pastParticiple:'previsto'},['Non l\'avevo previsto.'],['b1']),

v('it_0771',771,'organizzare','to organize','are',false,
  {io:'organizzo',tu:'organizzi',lui:'organizza',noi:'organizziamo',voi:'organizzate',loro:'organizzano'},
  'avere','organizzato',{io:'ho organizzato',tu:'hai organizzato',lui:'ha organizzato',noi:'abbiamo organizzato',voi:'avete organizzato',loro:'hanno organizzato'},
  {io:'organizzavo',tu:'organizzavi',lui:'organizzava',noi:'organizzavamo',voi:'organizzavate',loro:'organizzavano'},
  {io:'organizzerò',tu:'organizzerai',lui:'organizzerà',noi:'organizzeremo',voi:'organizzerete',loro:'organizzeranno'},
  {io:'organizzerei',tu:'organizzeresti',lui:'organizzerebbe',noi:'organizzeremmo',voi:'organizzereste',loro:'organizzerebbero'},
  {io:'organizzi',tu:'organizzi',lui:'organizzi',noi:'organizziamo',voi:'organizziate',loro:'organizzino'},
  null,['Dobbiamo organizzare una festa.'],['a2']),

v('it_0772',772,'preparare','to prepare','are',false,
  {io:'preparo',tu:'prepari',lui:'prepara',noi:'prepariamo',voi:'preparate',loro:'preparano'},
  'avere','preparato',{io:'ho preparato',tu:'hai preparato',lui:'ha preparato',noi:'abbiamo preparato',voi:'avete preparato',loro:'hanno preparato'},
  {io:'preparavo',tu:'preparavi',lui:'preparava',noi:'preparavamo',voi:'preparavate',loro:'preparavano'},
  {io:'preparerò',tu:'preparerai',lui:'preparerà',noi:'prepareremo',voi:'preparerete',loro:'prepareranno'},
  {io:'preparerei',tu:'prepareresti',lui:'preparerebbe',noi:'prepareremmo',voi:'preparereste',loro:'preparerebbero'},
  {io:'prepari',tu:'prepari',lui:'prepari',noi:'prepariamo',voi:'prepariate',loro:'preparino'},
  null,['Sto preparando il pranzo.'],['a1']),

v('it_0773',773,'controllare','to check/control','are',false,
  {io:'controllo',tu:'controlli',lui:'controlla',noi:'controlliamo',voi:'controllate',loro:'controllano'},
  'avere','controllato',{io:'ho controllato',tu:'hai controllato',lui:'ha controllato',noi:'abbiamo controllato',voi:'avete controllato',loro:'hanno controllato'},
  {io:'controllavo',tu:'controllavi',lui:'controllava',noi:'controllavamo',voi:'controllavate',loro:'controllavano'},
  {io:'controllerò',tu:'controllerai',lui:'controllerà',noi:'controlleremo',voi:'controllerete',loro:'controlleranno'},
  {io:'controllerei',tu:'controlleresti',lui:'controllerebbe',noi:'controlleremmo',voi:'controllereste',loro:'controllerebbero'},
  {io:'controlli',tu:'controlli',lui:'controlli',noi:'controlliamo',voi:'controlliate',loro:'controllino'},
  null,['Controlla il tuo email.'],['a2']),

v('it_0774',774,'migliorare','to improve','are',false,
  {io:'miglioro',tu:'migliori',lui:'migliora',noi:'miglioriamo',voi:'migliorate',loro:'migliorano'},
  'avere','migliorato',{io:'ho migliorato',tu:'hai migliorato',lui:'ha migliorato',noi:'abbiamo migliorato',voi:'avete migliorato',loro:'hanno migliorato'},
  {io:'miglioravo',tu:'miglioravi',lui:'migliorava',noi:'miglioravamo',voi:'miglioravate',loro:'miglioravano'},
  {io:'migliorerò',tu:'migliorerai',lui:'migliorerà',noi:'miglioreremo',voi:'migliorerete',loro:'miglioreranno'},
  {io:'migliorerei',tu:'miglioreresti',lui:'migliorerebbe',noi:'miglioreremmo',voi:'migliorereste',loro:'migliorerebbero'},
  {io:'migliori',tu:'migliori',lui:'migliori',noi:'miglioriamo',voi:'miglioriate',loro:'migliorino'},
  null,['Il tuo italiano migliora!'],['a2']),

v('it_0775',775,'peggiorare','to worsen','are',false,
  {io:'peggioro',tu:'peggiori',lui:'peggiora',noi:'peggoriamo',voi:'peggiorate',loro:'peggiorano'},
  'essere','peggiorato',{io:'sono peggiorato',tu:'sei peggiorato',lui:'è peggiorato',noi:'siamo peggiorati',voi:'siete peggiorati',loro:'sono peggiorati'},
  {io:'peggioravo',tu:'peggioravi',lui:'peggiorava',noi:'peggioravamo',voi:'peggioravate',loro:'peggioravano'},
  {io:'peggiorerò',tu:'peggiorerai',lui:'peggiorerà',noi:'peggioreremo',voi:'peggiorerete',loro:'peggioreranno'},
  {io:'peggiorerei',tu:'peggioreresti',lui:'peggiorerebbe',noi:'peggioreremmo',voi:'peggiorereste',loro:'peggiorerebbero'},
  {io:'peggiori',tu:'peggiori',lui:'peggiori',noi:'peggoriamo',voi:'peggioriate',loro:'peggiorino'},
  null,['La situazione peggiora.'],['a2']),

v('it_0776',776,'aumentare','to increase','are',false,
  {io:'aumento',tu:'aumenti',lui:'aumenta',noi:'aumentiamo',voi:'aumentate',loro:'aumentano'},
  'essere','aumentato',{io:'sono aumentato',tu:'sei aumentato',lui:'è aumentato',noi:'siamo aumentati',voi:'siete aumentati',loro:'sono aumentati'},
  {io:'aumentavo',tu:'aumentavi',lui:'aumentava',noi:'aumentavamo',voi:'aumentavate',loro:'aumentavano'},
  {io:'aumenterò',tu:'aumenterai',lui:'aumenterà',noi:'aumenteremo',voi:'aumenterete',loro:'aumenteranno'},
  {io:'aumenterei',tu:'aumenteresti',lui:'aumenterebbe',noi:'aumenteremmo',voi:'aumentereste',loro:'aumenterebbero'},
  {io:'aumenti',tu:'aumenti',lui:'aumenti',noi:'aumentiamo',voi:'aumentiate',loro:'aumentino'},
  null,['I prezzi aumentano.'],['a2']),

v('it_0777',777,'diminuire','to decrease','ire',false,
  {io:'diminuisco',tu:'diminuisci',lui:'diminuisce',noi:'diminuiamo',voi:'diminuite',loro:'diminuiscono'},
  'essere','diminuito',{io:'sono diminuito',tu:'sei diminuito',lui:'è diminuito',noi:'siamo diminuiti',voi:'siete diminuiti',loro:'sono diminuiti'},
  {io:'diminuivo',tu:'diminuivi',lui:'diminuiva',noi:'diminuivamo',voi:'diminuivate',loro:'diminuivano'},
  {io:'diminuirò',tu:'diminuirai',lui:'diminuirà',noi:'diminuiremo',voi:'diminuirete',loro:'diminuiranno'},
  {io:'diminuirei',tu:'diminuiresti',lui:'diminuirebbe',noi:'diminuiremmo',voi:'diminuireste',loro:'diminuirebbero'},
  {io:'diminuisca',tu:'diminuisca',lui:'diminuisca',noi:'diminuiamo',voi:'diminuiate',loro:'diminuiscano'},
  null,['Il dolore diminuisce.'],['a2']),

v('it_0778',778,'confrontare','to compare','are',false,
  {io:'confronto',tu:'confronti',lui:'confronta',noi:'confrontiamo',voi:'confrontate',loro:'confrontano'},
  'avere','confrontato',{io:'ho confrontato',tu:'hai confrontato',lui:'ha confrontato',noi:'abbiamo confrontato',voi:'avete confrontato',loro:'hanno confrontato'},
  {io:'confrontavo',tu:'confrontavi',lui:'confrontava',noi:'confrontavamo',voi:'confrontavate',loro:'confrontavano'},
  {io:'confronterò',tu:'confronterai',lui:'confronterà',noi:'confronteremo',voi:'confronterete',loro:'confronteranno'},
  {io:'confronterei',tu:'confronteresti',lui:'confronterebbe',noi:'confronteremmo',voi:'confrontereste',loro:'confronterebbero'},
  {io:'confronti',tu:'confronti',lui:'confronti',noi:'confrontiamo',voi:'confrontiate',loro:'confrontino'},
  null,['Confronta i prezzi.'],['a2']),

v('it_0779',779,'analizzare','to analyze','are',false,
  {io:'analizzo',tu:'analizzi',lui:'analizza',noi:'analizziamo',voi:'analizzate',loro:'analizzano'},
  'avere','analizzato',{io:'ho analizzato',tu:'hai analizzato',lui:'ha analizzato',noi:'abbiamo analizzato',voi:'avete analizzato',loro:'hanno analizzato'},
  {io:'analizzavo',tu:'analizzavi',lui:'analizzava',noi:'analizzavamo',voi:'analizzavate',loro:'analizzavano'},
  {io:'analizzerò',tu:'analizzerai',lui:'analizzerà',noi:'analizzeremo',voi:'analizzerete',loro:'analizzeranno'},
  {io:'analizzerei',tu:'analizzeresti',lui:'analizzerebbe',noi:'analizzeremmo',voi:'analizzereste',loro:'analizzerebbero'},
  {io:'analizzi',tu:'analizzi',lui:'analizzi',noi:'analizziamo',voi:'analizziate',loro:'analizzino'},
  null,['Dobbiamo analizzare i dati.'],['b1']),

v('it_0780',780,'sviluppare','to develop','are',false,
  {io:'sviluppo',tu:'sviluppi',lui:'sviluppa',noi:'sviluppiamo',voi:'sviluppate',loro:'sviluppano'},
  'avere','sviluppato',{io:'ho sviluppato',tu:'hai sviluppato',lui:'ha sviluppato',noi:'abbiamo sviluppato',voi:'avete sviluppato',loro:'hanno sviluppato'},
  {io:'sviluppavo',tu:'sviluppavi',lui:'sviluppava',noi:'sviluppavamo',voi:'sviluppavate',loro:'sviluppavano'},
  {io:'svilupperò',tu:'svilupperai',lui:'svilupperà',noi:'svilupperemo',voi:'svilupperete',loro:'svilupperanno'},
  {io:'svilupperei',tu:'svilupperesti',lui:'svilupperebbe',noi:'svilupperemmo',voi:'sviluppereste',loro:'svilupperebbero'},
  {io:'sviluppi',tu:'sviluppi',lui:'sviluppi',noi:'sviluppiamo',voi:'sviluppiate',loro:'sviluppino'},
  null,['Dobbiamo sviluppare nuove idee.'],['b1']),

// ── NOUNS 781-870 ──────────────────────────────────────────────────────────
n('it_0781',781,'mattino','morning','masculine','mattini',['Il mattino ha l\'oro in bocca.'],['a1']),
n('it_0782',782,'pomeriggio','afternoon','masculine','pomeriggi',['Nel pomeriggio lavoro.'],['a1']),
n('it_0783',783,'mezzogiorno','noon','masculine',null,['È mezzogiorno.'],['a1']),
n('it_0784',784,'mezzanotte','midnight','feminine',null,['A mezzanotte dorme.'],['a1']),
n('it_0785',785,'alba','dawn','feminine','albe',['All\'alba mi sveglio.'],['a2']),
n('it_0786',786,'tramonto','sunset','masculine','tramonti',['Il tramonto è bello.'],['a2']),
n('it_0787',787,'stagione','season','feminine','stagioni',['Qual è la tua stagione preferita?'],['a1']),
n('it_0788',788,'calendario','calendar','masculine','calendari',['Guardo il calendario.'],['a1']),
n('it_0789',789,'data','date','feminine','date',['Qual è la data di oggi?'],['a1']),
n('it_0790',790,'appuntamento','appointment/date','masculine','appuntamenti',['Ho un appuntamento.'],['a1']),
n('it_0791',791,'riunione','meeting','feminine','riunioni',['Ho una riunione domani.'],['a2']),
n('it_0792',792,'conferenza','conference','feminine','conferenze',['Partecipo a una conferenza.'],['a2']),
n('it_0793',793,'discorso','speech/talk','masculine','discorsi',['Ha fatto un bel discorso.'],['a2']),
n('it_0794',794,'conversazione','conversation','feminine','conversazioni',['È una bella conversazione.'],['a2']),
n('it_0795',795,'dibattito','debate','masculine','dibattiti',['C\'è un dibattito in TV.'],['b1']),
n('it_0796',796,'argomento','argument/topic','masculine','argomenti',['Di che argomento si parla?'],['a2']),
n('it_0797',797,'tema','theme/topic','masculine','temi',['Qual è il tema del libro?'],['a2']),
n('it_0798',798,'capitolo','chapter','masculine','capitoli',['Leggo un capitolo al giorno.'],['a2']),
n('it_0799',799,'paragrafo','paragraph','masculine','paragrafi',['Leggi il primo paragrafo.'],['b1']),
n('it_0800',800,'frase','sentence/phrase','feminine','frasi',['Scrivi una frase.'],['a2']),
n('it_0801',801,'vocabolo','vocabulary word','masculine','vocaboli',['Imparo nuovi vocaboli.'],['a2']),
n('it_0802',802,'dizionario','dictionary','masculine','dizionari',['Consulto il dizionario.'],['a1']),
n('it_0803',803,'grammatica','grammar','feminine',null,['La grammatica italiana è complessa.'],['a2']),
n('it_0804',804,'verbo','verb','masculine','verbi',['Il verbo è il nucleo della frase.'],['a2']),
n('it_0805',805,'sostantivo','noun (grammar)','masculine','sostantivi',['Indica il sostantivo.'],['a2']),
n('it_0806',806,'aggettivo','adjective','masculine','aggettivi',['Trova gli aggettivi.'],['a2']),
n('it_0807',807,'avverbio','adverb','masculine','avverbi',['Gli avverbi modificano il verbo.'],['a2']),
n('it_0808',808,'preposizione','preposition','feminine','preposizioni',['Le preposizioni sono difficili.'],['a2']),
n('it_0809',809,'congiunzione','conjunction','feminine','congiunzioni',['Le congiunzioni collegano le frasi.'],['a2']),
n('it_0810',810,'pronome','pronoun','masculine','pronomi',['I pronomi sostituiscono i nomi.'],['a2']),
n('it_0811',811,'soggetto','subject','masculine','soggetti',['Il soggetto compie l\'azione.'],['a2']),
n('it_0812',812,'oggetto','object','masculine','oggetti',['L\'oggetto subisce l\'azione.'],['a2']),
n('it_0813',813,'significato','meaning','masculine','significati',['Qual è il significato?'],['a2']),
n('it_0814',814,'traduzione','translation','feminine','traduzioni',['Faccio una traduzione.'],['a2']),
n('it_0815',815,'accento','accent/stress','masculine','accenti',['L\'accento tonico è importante.'],['a2']),
n('it_0816',816,'pronuncia','pronunciation','feminine',null,['La pronuncia è difficile.'],['a2']),
n('it_0817',817,'lettera','letter (alphabet)','feminine','lettere',['La lettera A.'],['a1']),
n('it_0818',818,'alfabeto','alphabet','masculine',null,['L\'alfabeto italiano.'],['a1']),
n('it_0819',819,'vocale','vowel','feminine','vocali',['Le vocali italiane.'],['a2']),
n('it_0820',820,'consonante','consonant','feminine','consonanti',['Le consonanti doppie.'],['a2']),
n('it_0821',821,'sillaba','syllable','feminine','sillabe',['Dividi in sillabe.'],['a2']),
n('it_0822',822,'rima','rhyme','feminine','rime',['La poesia ha delle rime.'],['a2']),
n('it_0823',823,'poesia','poem/poetry','feminine','poesie',['Mi piace la poesia.'],['a2']),
n('it_0824',824,'romanzo','novel','masculine','romanzi',['Leggo un romanzo.'],['a2']),
n('it_0825',825,'racconto','short story/tale','masculine','racconti',['Un racconto interessante.'],['a2']),
n('it_0826',826,'favola','fable/fairy tale','feminine','favole',['Racconta una favola.'],['a1']),
n('it_0827',827,'fiaba','fairy tale','feminine','fiabe',['I bambini amano le fiabe.'],['a1']),
n('it_0828',828,'mito','myth','masculine','miti',['Un mito greco.'],['a2']),
n('it_0829',829,'leggenda','legend','feminine','leggende',['Una leggenda popolare.'],['a2']),
n('it_0830',830,'spettacolo','show/spectacle','masculine','spettacoli',['Che spettacolo!'],['a2']),
n('it_0831',831,'teatro','theater','masculine','teatri',['Vado a teatro.'],['a1']),
n('it_0832',832,'cinema','cinema/movies','masculine','cinema',['Andiamo al cinema.'],['a1']),
n('it_0833',833,'mostra','exhibition/show','feminine','mostre',['Vado a vedere la mostra.'],['a2']),
n('it_0834',834,'museo','museum','masculine','musei',['Visito il museo.'],['a1']),
n('it_0835',835,'biblioteca','library','feminine','biblioteche',['Vado in biblioteca.'],['a1']),
n('it_0836',836,'stadio','stadium','masculine','stadi',['Vado allo stadio.'],['a1']),
n('it_0837',837,'palestra','gym','feminine','palestre',['Vado in palestra.'],['a1']),
n('it_0838',838,'piscina','swimming pool','feminine','piscine',['Vado in piscina.'],['a1']),
n('it_0839',839,'spiaggia','beach','feminine','spiagge',['Vado in spiaggia.'],['a1']),
n('it_0840',840,'campagna','countryside','feminine','campagne',['Abito in campagna.'],['a1']),
n('it_0841',841,'bosco','wood/forest','masculine','boschi',['Faccio una passeggiata nel bosco.'],['a1']),
n('it_0842',842,'foresta','forest','feminine','foreste',['La foresta amazzonica.'],['a2']),
n('it_0843',843,'deserto','desert','masculine','deserti',['Il deserto del Sahara.'],['a2']),
n('it_0844',844,'isola','island','feminine','isole',['La Sicilia è un\'isola.'],['a1']),
n('it_0845',845,'penisola','peninsula','feminine','penisole',['L\'Italia è una penisola.'],['a2']),
n('it_0846',846,'confine','border/boundary','masculine','confini',['Il confine tra Italia e Francia.'],['a2']),
n('it_0847',847,'regione','region','feminine','regioni',['Vivo nella regione Lombardia.'],['a2']),
n('it_0848',848,'provincia','province','feminine','province',['Abito in provincia.'],['a2']),
n('it_0849',849,'comune','municipality/town','masculine','comuni',['Il comune di Roma.'],['a2']),
n('it_0850',850,'quartiere','neighborhood/district','masculine','quartieri',['Abito in un bel quartiere.'],['a2']),

// ── ADJECTIVES 851-890 ──────────────────────────────────────────────────────
adj('it_0851',851,'coraggioso','brave/courageous','coraggiosi',['È molto coraggioso.'],['a2']),
adj('it_0852',852,'vigliacco','cowardly','vigliacchi',['Non fare il vigliacco.'],['a2']),
adj('it_0853',853,'onesto','honest','onesti',['È una persona onesta.'],['a2']),
adj('it_0854',854,'disonesto','dishonest','disonesti',['È una persona disonesta.'],['a2']),
adj('it_0855',855,'leale','loyal/fair','leali',['È un amico leale.'],['a2']),
adj('it_0856',856,'fedele','faithful/loyal','fedeli',['È fedele ai suoi valori.'],['a2']),
adj('it_0857',857,'generoso','generous','generosi',['È molto generoso.'],['a2']),
adj('it_0858',858,'avaro','stingy/greedy','avari',['È avaro di complimenti.'],['b1']),
adj('it_0859',859,'paziente','patient','pazienti',['Sii paziente.'],['a2']),
adj('it_0860',860,'impaziente','impatient','impazienti',['Non essere impaziente.'],['a2']),
adj('it_0861',861,'calmo','calm','calmi',['Rimani calmo.'],['a1']),
adj('it_0862',862,'nervoso','nervous/irritable','nervosi',['Sono nervoso oggi.'],['a1']),
adj('it_0863',863,'ansioso','anxious','ansiosi',['Sono ansioso per l\'esame.'],['a2']),
adj('it_0864',864,'tranquillo','quiet/calm','tranquilli',['È un posto tranquillo.'],['a1']),
adj('it_0865',865,'agitato','agitated/rough','agitati',['Il mare è agitato.'],['a2']),
adj('it_0866',866,'orgoglioso','proud','orgogliosi',['Sono orgoglioso di te.'],['a2']),
adj('it_0867',867,'umile','humble','umili',['È una persona umile.'],['a2']),
adj('it_0868',868,'arrogante','arrogant','arroganti',['È molto arrogante.'],['a2']),
adj('it_0869',869,'timido','shy/timid','timidi',['È molto timido.'],['a1']),
adj('it_0870',870,'estroverso','extroverted','estroversi',['È una persona estroversa.'],['a2']),
adj('it_0871',871,'introverso','introverted','introversi',['È una persona introversa.'],['a2']),
adj('it_0872',872,'curioso','curious','curiosi',['Sono curioso.'],['a1']),
adj('it_0873',873,'creativo','creative','creativi',['È molto creativo.'],['a2']),
adj('it_0874',874,'pratico','practical','pratici',['È un approccio pratico.'],['a2']),
adj('it_0875',875,'teorico','theoretical','teorici',['È troppo teorico.'],['b1']),
adj('it_0876',876,'razionale','rational','razionali',['Sii razionale.'],['b1']),
adj('it_0877',877,'emotivo','emotional','emotivi',['È molto emotivo.'],['a2']),
adj('it_0878',878,'sensibile','sensitive','sensibili',['È una persona sensibile.'],['a2']),
adj('it_0879',879,'insensibile','insensitive','insensibili',['È insensibile agli altri.'],['b1']),
adj('it_0880',880,'romantico','romantic','romantici',['È un tipo romantico.'],['a2']),

// ── ADVERBS & MISC 881-1000 ─────────────────────────────────────────────────
adv('it_0881',881,'sopra','above/over',['Metti sopra.'],['a1']),
adv('it_0882',882,'sotto','below/under',['Guarda sotto.'],['a1']),
adv('it_0883',883,'dentro','inside',['Vieni dentro.'],['a1']),
adv('it_0884',884,'fuori','outside',['Andiamo fuori.'],['a1']),
adv('it_0885',885,'avanti','forward/ahead',['Vai avanti.'],['a1']),
adv('it_0886',886,'indietro','back/backward',['Torna indietro.'],['a1']),
adv('it_0887',887,'destra','right (direction)',['Gira a destra.'],['a1']),
adv('it_0888',888,'sinistra','left (direction)',['Gira a sinistra.'],['a1']),
adv('it_0889',889,'lontano','far away',['Non è lontano.'],['a1']),
adv('it_0890',890,'vicino','near/close',['Abito vicino.'],['a1']),
adv('it_0891',891,'intorno','around',['Guardo intorno.'],['a1']),
adv('it_0892',892,'ovunque','everywhere',['Lo cerco ovunque.'],['a2']),
adv('it_0893',893,'da qualche parte','somewhere',['È da qualche parte.'],['a2']),
adv('it_0894',894,'in nessun posto','nowhere',['Non è in nessun posto.'],['a2']),
adv('it_0895',895,'dappertutto','everywhere',['L\'ho cercato dappertutto.'],['a2']),
adv('it_0896',896,'soprattutto','above all/especially',['Soprattutto non dimenticare.'],['a2']),
adv('it_0897',897,'specialmente','especially',['Specialmente d\'estate.'],['a2']),
adv('it_0898',898,'particolarmente','particularly',['È particolarmente bello.'],['a2']),
adv('it_0899',899,'relativamente','relatively',['È relativamente facile.'],['b1']),
adv('it_0900',900,'apparentemente','apparently',['Apparentemente è così.'],['b1']),
// 901-1000: More nouns
n('it_0901',901,'abitudine','habit','feminine','abitudini',['È una cattiva abitudine.'],['a2']),
n('it_0902',902,'tradizione','tradition','feminine','tradizioni',['È una tradizione italiana.'],['a2']),
n('it_0903',903,'costume','custom/costume','masculine','costumi',['I costumi locali.'],['a2']),
n('it_0904',904,'usanza','custom/usage','feminine','usanze',['Le usanze del posto.'],['a2']),
n('it_0905',905,'maniera','manner/way','feminine','maniere',['In che maniera?'],['a2']),
n('it_0906',906,'stile','style','masculine','stili',['Ha uno stile unico.'],['a2']),
n('it_0907',907,'moda','fashion','feminine','mode',['Segue la moda.'],['a2']),
n('it_0908',908,'tendenza','trend','feminine','tendenze',['È una nuova tendenza.'],['a2']),
n('it_0909',909,'influenza','influence/flu','feminine','influenze',['Ho l\'influenza.'],['a2']),
n('it_0910',910,'effetto','effect — see 448','masculine','effetti',['Ha un effetto positivo.'],['a2']),
n('it_0911',911,'aspetto','aspect/appearance','masculine','aspetti',['Da questo aspetto.'],['a2']),
n('it_0912',912,'carattere','character/personality','masculine','caratteri',['Ha un buon carattere.'],['a2']),
n('it_0913',913,'personalità','personality','feminine','personalità',['Ha una forte personalità.'],['a2']),
n('it_0914',914,'comportamento','behavior','masculine','comportamenti',['Il suo comportamento è strano.'],['a2']),
n('it_0915',915,'atteggiamento','attitude','masculine','atteggiamenti',['Ha un buon atteggiamento.'],['a2']),
n('it_0916',916,'intenzione','intention','feminine','intenzioni',['Quali sono le tue intenzioni?'],['a2']),
n('it_0917',917,'opinione','opinion','feminine','opinioni',['Qual è la tua opinione?'],['a1']),
n('it_0918',918,'punto di vista','point of view','masculine',null,['Dal mio punto di vista.'],['a2']),
n('it_0919',919,'prospettiva','perspective','feminine','prospettive',['Da questa prospettiva.'],['b1']),
n('it_0920',920,'impressione','impression','feminine','impressioni',['Che impressione!'],['a2']),
n('it_0921',921,'reazione','reaction','feminine','reazioni',['Qual è la tua reazione?'],['a2']),
n('it_0922',922,'sentimento','feeling/sentiment','masculine','sentimenti',['Ho dei sentimenti per te.'],['a2']),
n('it_0923',923,'emozione','emotion','feminine','emozioni',['Quante emozioni!'],['a2']),
n('it_0924',924,'paura','fear','feminine','paure',['Ho paura.'],['a1']),
n('it_0925',925,'speranza','hope','feminine','speranze',['Ho speranza.'],['a2']),
n('it_0926',926,'desiderio','wish/desire','masculine','desideri',['Il mio desiderio è viaggiare.'],['a2']),
n('it_0927',927,'amore','love','masculine','amori',['L\'amore è tutto.'],['a1']),
n('it_0928',928,'odio','hate','masculine','odi',['L\'odio non porta da nessuna parte.'],['a2']),
n('it_0929',929,'gelosia','jealousy','feminine','gelosie',['La gelosia è distruttiva.'],['a2']),
n('it_0930',930,'invidia','envy','feminine','invidie',['L\'invidia è un brutto sentimento.'],['a2']),
n('it_0931',931,'fiducia','trust/confidence','feminine','fiducie',['Ho fiducia in te.'],['a2']),
n('it_0932',932,'rispetto','respect','masculine',null,['Rispetto per gli altri.'],['a2']),
n('it_0933',933,'gentilezza','kindness','feminine',null,['La gentilezza è importante.'],['a2']),
n('it_0934',934,'cortesia','courtesy','feminine','cortesie',['Per cortesia.'],['a2']),
n('it_0935',935,'solidarietà','solidarity','feminine',null,['Solidarietà tra persone.'],['b1']),
n('it_0936',936,'amicizia','friendship','feminine','amicizie',['L\'amicizia è preziosa.'],['a1']),
n('it_0937',937,'rapporto','relationship/report','masculine','rapporti',['Ho un buon rapporto con lui.'],['a2']),
n('it_0938',938,'coppia','couple/pair','feminine','coppie',['Una coppia felice.'],['a2']),
n('it_0939',939,'matrimonio','marriage/wedding','masculine','matrimoni',['Il matrimonio è domani.'],['a2']),
n('it_0940',940,'divorzio','divorce','masculine','divorzi',['Ha chiesto il divorzio.'],['a2']),
n('it_0941',941,'famiglia','family','feminine','famiglie',['La mia famiglia è grande.'],['a1']),
n('it_0942',942,'parente','relative','masculine','parenti',['Ho molti parenti.'],['a2']),
n('it_0943',943,'collega','colleague','masculine','colleghi',['Il mio collega è simpatico.'],['a2']),
n('it_0944',944,'vicino','neighbor','masculine','vicini',['Il vicino è gentile.'],['a2']),
n('it_0945',945,'conoscente','acquaintance','masculine','conoscenti',['È solo un conoscente.'],['a2']),
n('it_0946',946,'straniero','foreigner/stranger','masculine','stranieri',['È uno straniero.'],['a2']),
n('it_0947',947,'turista','tourist','masculine','turisti',['Molti turisti visitano Roma.'],['a1']),
n('it_0948',948,'immigrato','immigrant','masculine','immigrati',['È un immigrato.'],['a2']),
n('it_0949',949,'cittadino','citizen','masculine','cittadini',['È un cittadino italiano.'],['a2']),
n('it_0950',950,'abitante','inhabitant','masculine','abitanti',['Gli abitanti del paese.'],['a2']),
n('it_0951',951,'popolazione','population','feminine','popolazioni',['La popolazione cresce.'],['a2']),
n('it_0952',952,'nazione','nation','feminine','nazioni',['La nazione italiana.'],['a2']),
n('it_0953',953,'capitale','capital (city)','feminine','capitali',['Roma è la capitale d\'Italia.'],['a1']),
n('it_0954',954,'territorio','territory','masculine','territori',['Il territorio nazionale.'],['a2']),
n('it_0955',955,'ambiente','environment — see 458','masculine','ambienti',['Rispetta l\'ambiente.'],['a2']),
n('it_0956',956,'risorse','resources','feminine',null,['Le risorse naturali.'],['a2']),
n('it_0957',957,'energia rinnovabile','renewable energy','feminine',null,['Energia rinnovabile è il futuro.'],['b1']),
n('it_0958',958,'inquinamento','pollution','masculine',null,['L\'inquinamento è un problema.'],['a2']),
n('it_0959',959,'riciclaggio','recycling','masculine',null,['Il riciclaggio è importante.'],['a2']),
n('it_0960',960,'rifiuti','waste/garbage','masculine',null,['Separa i rifiuti.'],['a2']),
n('it_0961',961,'edificio','building','masculine','edifici',['Un edificio alto.'],['a2']),
n('it_0962',962,'palazzo','palace/building','masculine','palazzi',['Un bel palazzo.'],['a1']),
n('it_0963',963,'villa','villa/house','feminine','ville',['Una bella villa.'],['a2']),
n('it_0964',964,'casetta','small house','feminine','casette',['Una casetta in campagna.'],['a2']),
n('it_0965',965,'condominio','condominium/block','masculine','condomini',['Abito in un condominio.'],['a2']),
n('it_0966',966,'scala','staircase/ladder','feminine','scale',['Salgo le scale.'],['a1']),
n('it_0967',967,'balcone','balcony','masculine','balconi',['Ho un balcone.'],['a1']),
n('it_0968',968,'terrazzo','terrace/terrace','masculine','terrazzi',['Ho un terrazzo con vista.'],['a2']),
n('it_0969',969,'cantina','cellar/basement','feminine','cantine',['In cantina ho il vino.'],['a2']),
n('it_0970',970,'soffitta','attic','feminine','soffitte',['Tengo le cose in soffitta.'],['a2']),
n('it_0971',971,'garage','garage','masculine','garage',['La macchina è nel garage.'],['a1']),
n('it_0972',972,'parcheggio','parking','masculine','parcheggi',['C\'è un parcheggio qui vicino.'],['a1']),
n('it_0973',973,'semaforo','traffic light','masculine','semafori',['Il semaforo è rosso.'],['a1']),
n('it_0974',974,'incrocio','crossroads/intersection','masculine','incroci',['All\'incrocio, gira a destra.'],['a2']),
n('it_0975',975,'ponte','bridge','masculine','ponti',['Il ponte sull\'Arno.'],['a1']),
n('it_0976',976,'galleria','gallery/tunnel','feminine','gallerie',['Una galleria d\'arte.'],['a2']),
n('it_0977',977,'sottopassaggio','underpass','masculine','sottopassaggi',['Attraversa il sottopassaggio.'],['a2']),
n('it_0978',978,'marciapiede','sidewalk','masculine','marciapiedi',['Cammino sul marciapiede.'],['a1']),
n('it_0979',979,'fermata','stop (bus/tram)','feminine','fermate',['La fermata dell\'autobus.'],['a1']),
n('it_0980',980,'stazione','station','feminine','stazioni',['Vado alla stazione.'],['a1']),
n('it_0981',981,'porto','port/harbor','masculine','porti',['Il porto di Genova.'],['a2']),
n('it_0982',982,'aeroporto','airport','masculine','aeroporti',['L\'aeroporto di Roma.'],['a1']),
n('it_0983',983,'autostrada','highway','feminine','autostrade',['Prendo l\'autostrada.'],['a2']),
n('it_0984',984,'pedaggio','toll','masculine','pedaggi',['Pago il pedaggio.'],['a2']),
n('it_0985',985,'benzina','gasoline','feminine',null,['Faccio benzina.'],['a1']),
n('it_0986',986,'motore','engine/motor','masculine','motori',['Il motore è rotto.'],['a2']),
n('it_0987',987,'ruota','wheel','feminine','ruote',['Ho una ruota a terra.'],['a2']),
n('it_0988',988,'freno','brake','masculine','freni',['Metto il freno.'],['a2']),
n('it_0989',989,'volante','steering wheel','masculine','volanti',['Giro il volante.'],['a2']),
n('it_0990',990,'cintura di sicurezza','seatbelt','feminine',null,['Allaccia la cintura.'],['a1']),
n('it_0991',991,'incidente','accident','masculine','incidenti',['C\'è stato un incidente.'],['a2']),
n('it_0992',992,'multa','fine/ticket','feminine','multe',['Ho preso una multa.'],['a2']),
n('it_0993',993,'patente','driving license','feminine','patenti',['Ho la patente.'],['a2']),
n('it_0994',994,'assicurazione','insurance','feminine','assicurazioni',['Ho l\'assicurazione.'],['a2']),
n('it_0995',995,'documento','document','masculine','documenti',['Mostra i documenti.'],['a2']),
n('it_0996',996,'carta d\'identità','identity card','feminine',null,['Ho la carta d\'identità.'],['a1']),
n('it_0997',997,'modulo','form','masculine','moduli',['Compila il modulo.'],['a2']),
n('it_0998',998,'firma','signature','feminine','firme',['Metti la firma.'],['a2']),
n('it_0999',999,'timbro','stamp/seal','masculine','timbri',['Metti il timbro.'],['a2']),
n('it_1000',1000,'burocrazia','bureaucracy','feminine',null,['La burocrazia italiana è lenta.'],['b1']),
];

// Filter out duplicates
const final=entries.filter(e=>!e.examples[0].startsWith('—'));
console.log(`Generated ${final.length} entries, ranks ${final[0].rank}-${final[final.length-1].rank}`);
const ranks=final.map(e=>e.rank);
const dups=ranks.filter((r,i)=>ranks.indexOf(r)!==i);
if(dups.length) console.warn('Duplicate ranks:',dups);
fs.writeFileSync(path.join(__dirname,'../src/data/words-004.json'),JSON.stringify(final,null,2));
console.log('words-004.json written.');
