const fs = require('fs');
const path = require('path');

// words-005.json: ranks 1001-1250, B1 level

// Conjugation helpers for regular verbs
function areConj(stem){
  return{
    presente:{io:stem+'o',tu:stem+'i',lui:stem+'a',noi:stem+'iamo',voi:stem+'ate',loro:stem+'ano'},
    imperfetto:{io:stem+'avo',tu:stem+'avi',lui:stem+'ava',noi:stem+'avamo',voi:stem+'avate',loro:stem+'avano'},
    futuroSemplice:{io:stem+'erò',tu:stem+'erai',lui:stem+'erà',noi:stem+'eremo',voi:stem+'erete',loro:stem+'eranno'},
    condizionale:{io:stem+'erei',tu:stem+'eresti',lui:stem+'erebbe',noi:stem+'eremmo',voi:stem+'ereste',loro:stem+'erebbero'},
    congiuntivoPresente:{io:stem+'i',tu:stem+'i',lui:stem+'i',noi:stem+'iamo',voi:stem+'iate',loro:stem+'ino'}
  };
}
function ereConj(stem){
  return{
    presente:{io:stem+'o',tu:stem+'i',lui:stem+'e',noi:stem+'iamo',voi:stem+'ete',loro:stem+'ono'},
    imperfetto:{io:stem+'evo',tu:stem+'evi',lui:stem+'eva',noi:stem+'evamo',voi:stem+'evate',loro:stem+'evano'},
    futuroSemplice:{io:stem+'erò',tu:stem+'erai',lui:stem+'erà',noi:stem+'eremo',voi:stem+'erete',loro:stem+'eranno'},
    condizionale:{io:stem+'erei',tu:stem+'eresti',lui:stem+'erebbe',noi:stem+'eremmo',voi:stem+'ereste',loro:stem+'erebbero'},
    congiuntivoPresente:{io:stem+'a',tu:stem+'a',lui:stem+'a',noi:stem+'iamo',voi:stem+'iate',loro:stem+'ano'}
  };
}
function ireConj(stem,isc=false){
  const pBase=isc?stem+'isc':stem;
  return{
    presente:{io:pBase+'o',tu:pBase+'i',lui:pBase+'e',noi:stem+'iamo',voi:stem+'ite',loro:pBase+'ono'},
    imperfetto:{io:stem+'ivo',tu:stem+'ivi',lui:stem+'iva',noi:stem+'ivamo',voi:stem+'ivate',loro:stem+'ivano'},
    futuroSemplice:{io:stem+'irò',tu:stem+'irai',lui:stem+'irà',noi:stem+'iremo',voi:stem+'irete',loro:stem+'iranno'},
    condizionale:{io:stem+'irei',tu:stem+'iresti',lui:stem+'irebbe',noi:stem+'iremmo',voi:stem+'ireste',loro:stem+'irebbero'},
    congiuntivoPresente:{io:pBase+'a',tu:pBase+'a',lui:pBase+'a',noi:stem+'iamo',voi:stem+'iate',loro:pBase+'ano'}
  };
}

function makeVerb(id,rank,ita,eng,grp,ppAux,pp,irregConj,ex,tags,irr=false){
  const stem=ita.replace(/(are|ere|ire)$/,'');
  const baseConj = grp==='are'?areConj(stem):grp==='ere'?ereConj(stem):ireConj(stem,false);
  const conj=Object.assign({},baseConj,irregConj||{});
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'verb',gender:null,plural:null,
    conjugationGroup:grp,irregular:irr,
    conjugations:{presente:conj.presente,
      passatoProssimo:{auxiliary:ppAux,pastParticiple:pp,
        io:(ppAux==='avere'?'ho':'sono')+' '+pp,
        tu:(ppAux==='avere'?'hai':'sei')+' '+pp,
        lui:(ppAux==='avere'?'ha':'è')+' '+pp,
        noi:(ppAux==='avere'?'abbiamo':'siamo')+' '+pp,
        voi:(ppAux==='avere'?'avete':'siete')+' '+pp,
        loro:(ppAux==='avere'?'hanno':'sono')+' '+pp},
      imperfetto:conj.imperfetto,futuroSemplice:conj.futuroSemplice,
      condizionale:conj.condizionale,congiuntivoPresente:conj.congiuntivoPresente},
    irregularForms:null,examples:ex,tags,needsReview:false};
}
function n(id,rank,ita,eng,gender,plural,ex,tags){
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'noun',gender,plural,
    conjugationGroup:null,irregular:false,conjugations:null,irregularForms:null,examples:ex,tags,needsReview:false};
}
function adj(id,rank,ita,eng,plural,ex,tags){
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'adjective',gender:'masculine',plural,
    conjugationGroup:null,irregular:false,conjugations:null,irregularForms:null,examples:ex,tags,needsReview:false};
}
function adv(id,rank,ita,eng,ex,tags){
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'adverb',gender:null,plural:null,
    conjugationGroup:null,irregular:false,conjugations:null,irregularForms:null,examples:ex,tags,needsReview:false};
}

const entries=[
// ── VERBS 1001-1060 ─────────────────────────────────────────────────────────
makeVerb('it_1001',1001,'affrontare','to face/tackle','are','avere','affrontato',null,['Dobbiamo affrontare il problema.'],['b1']),
makeVerb('it_1002',1002,'superare','to overcome/exceed','are','avere','superato',null,['Ho superato l\'esame.'],['a2']),
makeVerb('it_1003',1003,'raggiungere','to reach','ere','avere','raggiunto',
  {presente:{io:'raggiungo',tu:'raggiungi',lui:'raggiunge',noi:'raggiungiamo',voi:'raggiungete',loro:'raggiungono'},
   congiuntivoPresente:{io:'raggiunga',tu:'raggiunga',lui:'raggiunga',noi:'raggiungiamo',voi:'raggiungiate',loro:'raggiungano'}},
  ['Ho raggiunto il mio obiettivo.'],['a2'],true),
makeVerb('it_1004',1004,'avvicinarsi','to approach','are','essere','avvicinato',null,['Si avvicina la primavera.'],['a2']),
makeVerb('it_1005',1005,'allontanarsi','to move away','are','essere','allontanato',null,['Si è allontanato.'],['a2']),
makeVerb('it_1006',1006,'dipingere','to paint','ere','avere','dipinto',
  {presente:{io:'dipingo',tu:'dipingi',lui:'dipinge',noi:'dipingiamo',voi:'dipingete',loro:'dipingono'},
   congiuntivoPresente:{io:'dipinga',tu:'dipinga',lui:'dipinga',noi:'dipingiamo',voi:'dipingiate',loro:'dipingano'}},
  ['Picasso dipingeva benissimo.'],['a2'],true),
makeVerb('it_1007',1007,'disegnare','to draw/design','are','avere','disegnato',null,['Mi piace disegnare.'],['a1']),
makeVerb('it_1008',1008,'fotografare','to photograph','are','avere','fotografato',null,['Fotografo i paesaggi.'],['a2']),
makeVerb('it_1009',1009,'pubblicare','to publish','are','avere','pubblicato',
  {presente:{io:'pubblico',tu:'pubblichi',lui:'pubblica',noi:'pubblichiamo',voi:'pubblicate',loro:'pubblicano'},
   futuroSemplice:{io:'pubblicherò',tu:'pubblicherai',lui:'pubblicherà',noi:'pubblicheremo',voi:'pubblicherete',loro:'pubblicheranno'}},
  ['Ha pubblicato un libro.'],['b1']),
makeVerb('it_1010',1010,'consultare','to consult','are','avere','consultato',null,['Consulto il medico.'],['a2']),
makeVerb('it_1011',1011,'dimostrare','to demonstrate','are','avere','dimostrato',null,['Dimostra il tuo punto.'],['b1']),
makeVerb('it_1012',1012,'confermare','to confirm','are','avere','confermato',null,['Puoi confermare?'],['a2']),
makeVerb('it_1013',1013,'negare','to deny','are','avere','negato',
  {presente:{io:'nego',tu:'neghi',lui:'nega',noi:'neghiamo',voi:'negate',loro:'negano'},
   futuroSemplice:{io:'negherò',tu:'negherai',lui:'negherà',noi:'negheremo',voi:'negherete',loro:'negheranno'}},
  ['Nega tutto.'],['b1']),
makeVerb('it_1014',1014,'ammettere','to admit','ere','avere','ammesso',
  {presente:{io:'ammetto',tu:'ammetti',lui:'ammette',noi:'ammettiamo',voi:'ammettete',loro:'ammettono'},
   congiuntivoPresente:{io:'ammetta',tu:'ammetta',lui:'ammetta',noi:'ammettiamo',voi:'ammettiate',loro:'ammettano'}},
  ['Ammetti il tuo errore.'],['b1'],true),
makeVerb('it_1015',1015,'riconoscere','to recognize','ere','avere','riconosciuto',
  {presente:{io:'riconosco',tu:'riconosci',lui:'riconosce',noi:'riconosciamo',voi:'riconoscete',loro:'riconoscono'},
   congiuntivoPresente:{io:'riconosca',tu:'riconosca',lui:'riconosca',noi:'riconosciamo',voi:'riconosciate',loro:'riconoscano'}},
  ['Ti riconosco!'],['a2']),
makeVerb('it_1016',1016,'considerare','to consider','are','avere','considerato',null,['Considera l\'alternativa.'],['a2']),
makeVerb('it_1017',1017,'valutare','to evaluate/assess','are','avere','valutato',null,['Valuta i rischi.'],['b1']),
makeVerb('it_1018',1018,'giudicare','to judge','are','avere','giudicato',
  {presente:{io:'giudico',tu:'giudichi',lui:'giudica',noi:'giudichiamo',voi:'giudicate',loro:'giudicano'}},
  ['Non giudicare.'],['b1']),
makeVerb('it_1019',1019,'criticare','to criticize','are','avere','criticato',
  {presente:{io:'critico',tu:'critichi',lui:'critica',noi:'critichiamo',voi:'criticate',loro:'criticano'}},
  ['Non criticare sempre.'],['b1']),
makeVerb('it_1020',1020,'difendere','to defend','ere','avere','difeso',
  {presente:{io:'difendo',tu:'difendi',lui:'difende',noi:'difendiamo',voi:'difendete',loro:'difendono'},
   congiuntivoPresente:{io:'difenda',tu:'difenda',lui:'difenda',noi:'difendiamo',voi:'difendiate',loro:'difendano'}},
  ['Difendo la mia posizione.'],['b1'],true),
makeVerb('it_1021',1021,'accusare','to accuse','are','avere','accusato',null,['Lo accusano di furto.'],['b1']),
makeVerb('it_1022',1022,'punire','to punish','ire','avere','punito',null,['Non punire il bambino.'],['b1']),
makeVerb('it_1023',1023,'premiare','to award/reward','are','avere','premiato',null,['L\'hanno premiata.'],['a2']),
makeVerb('it_1024',1024,'trattare','to treat/deal with','are','avere','trattato',null,['Come ti tratta?'],['a2']),
makeVerb('it_1025',1025,'gestire','to manage/run','ire','avere','gestito',null,['Gestisce un\'azienda.'],['b1']),
makeVerb('it_1026',1026,'affittare','to rent','are','avere','affittato',null,['Affitto un appartamento.'],['a2']),
makeVerb('it_1027',1027,'vendere','to sell','ere','avere','venduto',null,['Vendo la macchina.'],['a2']),
makeVerb('it_1028',1028,'acquistare','to purchase/acquire','are','avere','acquistato',null,['Ho acquistato online.'],['a2']),
makeVerb('it_1029',1029,'produrre','to produce','ere','avere','prodotto',
  {presente:{io:'produco',tu:'produci',lui:'produce',noi:'produciamo',voi:'producete',loro:'producono'},
   imperfetto:{io:'producevo',tu:'producevi',lui:'produceva',noi:'producevamo',voi:'producevate',loro:'producevano'},
   futuroSemplice:{io:'produrrò',tu:'produrrai',lui:'produrrà',noi:'produrremo',voi:'produrrete',loro:'produrranno'},
   condizionale:{io:'produrrei',tu:'produrresti',lui:'produrrebbe',noi:'produrremmo',voi:'produrreste',loro:'produrrebbero'},
   congiuntivoPresente:{io:'produca',tu:'produca',lui:'produca',noi:'produciamo',voi:'produciate',loro:'producano'}},
  ['L\'Italia produce molto vino.'],['b1'],true),
makeVerb('it_1030',1030,'creare','to create','are','avere','creato',null,['Ha creato un\'opera bella.'],['a2']),
makeVerb('it_1031',1031,'inventare','to invent','are','avere','inventato',null,['Chi ha inventato la radio?'],['a2']),
makeVerb('it_1032',1032,'scoprire','to discover','ire','avere','scoperto',
  {presente:{io:'scopro',tu:'scopri',lui:'scopre',noi:'scopriamo',voi:'scoprite',loro:'scoprono'},
   congiuntivoPresente:{io:'scopra',tu:'scopra',lui:'scopra',noi:'scopriamo',voi:'scopriate',loro:'scoprano'}},
  ['Ho scoperto un posto nuovo.'],['a2'],true),
makeVerb('it_1033',1033,'ricercare','to research/seek','are','avere','ricercato',
  {presente:{io:'ricerco',tu:'ricerchi',lui:'ricerca',noi:'ricerchiamo',voi:'ricercate',loro:'ricercano'}},
  ['Ricerca nuove soluzioni.'],['b1']),
makeVerb('it_1034',1034,'sperimentare','to experiment','are','avere','sperimentato',null,['Sperimentano nuovi metodi.'],['b1']),
makeVerb('it_1035',1035,'progettare','to plan/design','are','avere','progettato',null,['Progettano un nuovo edificio.'],['b1']),
makeVerb('it_1036',1036,'realizzare','to achieve/realize','are','avere','realizzato',null,['Ha realizzato il suo sogno.'],['a2']),
makeVerb('it_1037',1037,'completare','to complete','are','avere','completato',null,['Ho completato il progetto.'],['a2']),
makeVerb('it_1038',1038,'correggere','to correct','ere','avere','corretto',
  {presente:{io:'correggo',tu:'correggi',lui:'corregge',noi:'correggiamo',voi:'correggete',loro:'correggono'},
   congiuntivoPresente:{io:'corregga',tu:'corregga',lui:'corregga',noi:'correggiamo',voi:'correggiate',loro:'correggano'}},
  ['Correggi gli errori.'],['a2'],true),
makeVerb('it_1039',1039,'agire','to act','ire','avere','agito',null,['Bisogna agire subito.'],['b1']),
makeVerb('it_1040',1040,'reagire','to react','ire','avere','reagito',null,['Come hai reagito?'],['b1']),
makeVerb('it_1041',1041,'interagire','to interact','ire','avere','interagito',null,['Interagiamo con gli altri.'],['b1']),
makeVerb('it_1042',1042,'comunicare','to communicate','are','avere','comunicato',
  {presente:{io:'comunico',tu:'comunichi',lui:'comunica',noi:'comunichiamo',voi:'comunicate',loro:'comunicano'}},
  ['Come comunicate?'],['a2']),
makeVerb('it_1043',1043,'collaborare','to collaborate','are','avere','collaborato',null,['Collaboriamo insieme.'],['b1']),
makeVerb('it_1044',1044,'partecipare','to participate','are','essere','partecipato',null,['Partecipo al corso.'],['a2']),
makeVerb('it_1045',1045,'contribuire','to contribute','ire','avere','contribuito',null,['Ognuno contribuisce.'],['b1']),
makeVerb('it_1046',1046,'condividere','to share','ere','avere','condiviso',
  {presente:{io:'condivido',tu:'condividi',lui:'condivide',noi:'condividiamo',voi:'condividete',loro:'condividono'},
   congiuntivoPresente:{io:'condivida',tu:'condivida',lui:'condivida',noi:'condividiamo',voi:'condividiate',loro:'condividano'}},
  ['Condividi le tue idee.'],['a2'],true),
makeVerb('it_1047',1047,'risolvere','to solve/resolve','ere','avere','risolto',
  {presente:{io:'risolvo',tu:'risolvi',lui:'risolve',noi:'risolviamo',voi:'risolvete',loro:'risolvono'},
   congiuntivoPresente:{io:'risolva',tu:'risolva',lui:'risolva',noi:'risolviamo',voi:'risolviate',loro:'risolvano'}},
  ['Risolvi il problema.'],['a2'],true),
makeVerb('it_1048',1048,'affidare','to entrust','are','avere','affidato',null,['Ti affido questo compito.'],['b1']),
makeVerb('it_1049',1049,'proporre','to propose','ere','avere','proposto',
  {presente:{io:'propongo',tu:'proponi',lui:'propone',noi:'proponiamo',voi:'proponete',loro:'propongono'},
   imperfetto:{io:'proponevo',tu:'proponevi',lui:'proponeva',noi:'proponevamo',voi:'proponevate',loro:'proponevano'},
   futuroSemplice:{io:'proporrò',tu:'proporrai',lui:'proporrà',noi:'proporremo',voi:'proporrete',loro:'proporranno'},
   condizionale:{io:'proporrei',tu:'proporresti',lui:'proporrebbe',noi:'proporremmo',voi:'proporreste',loro:'proporrebbero'},
   congiuntivoPresente:{io:'proponga',tu:'proponga',lui:'proponga',noi:'proponiamo',voi:'proponiate',loro:'propongano'}},
  ['Ti propongo un accordo.'],['b1'],true),
makeVerb('it_1050',1050,'esprimere','to express','ere','avere','espresso',
  {presente:{io:'esprimo',tu:'esprimi',lui:'esprime',noi:'esprimiamo',voi:'esprimete',loro:'esprimono'},
   congiuntivoPresente:{io:'esprima',tu:'esprima',lui:'esprima',noi:'esprimiamo',voi:'esprimiate',loro:'esprimano'}},
  ['Esprimi la tua opinione.'],['b1'],true),
makeVerb('it_1051',1051,'tradurre','to translate','ere','avere','tradotto',
  {presente:{io:'traduco',tu:'traduci',lui:'traduce',noi:'traduciamo',voi:'traducete',loro:'traducono'},
   imperfetto:{io:'traducevo',tu:'traducevi',lui:'traduceva',noi:'traducevamo',voi:'traducevate',loro:'traducevano'},
   futuroSemplice:{io:'tradurrò',tu:'tradurrai',lui:'tradurrà',noi:'tradurremo',voi:'tradurrete',loro:'tradurranno'},
   condizionale:{io:'tradurrei',tu:'tradurresti',lui:'tradurrebbe',noi:'tradurremmo',voi:'tradurreste',loro:'tradurrebbero'},
   congiuntivoPresente:{io:'traduca',tu:'traduca',lui:'traduca',noi:'traduciamo',voi:'traduciate',loro:'traducano'}},
  ['Puoi tradurre questa frase?'],['a2'],true),
makeVerb('it_1052',1052,'citare','to quote/cite','are','avere','citato',null,['Cita le fonti.'],['b1']),
makeVerb('it_1053',1053,'definire','to define','ire','avere','definito',null,['Come definisci la libertà?'],['b1']),
makeVerb('it_1054',1054,'classificare','to classify','are','avere','classificato',
  {presente:{io:'classifico',tu:'classifichi',lui:'classifica',noi:'classifichiamo',voi:'classificate',loro:'classificano'}},
  ['Classifica per categoria.'],['b1']),
makeVerb('it_1055',1055,'identificare','to identify','are','avere','identificato',
  {presente:{io:'identifico',tu:'identifichi',lui:'identifica',noi:'identifichiamo',voi:'identificate',loro:'identificano'}},
  ['Identifica il problema.'],['b1']),
makeVerb('it_1056',1056,'caratterizzare','to characterize','are','avere','caratterizzato',null,['Questo caratterizza il periodo.'],['b1']),
makeVerb('it_1057',1057,'immaginare','to imagine','are','avere','immaginato',null,['Immagina un mondo migliore.'],['a2']),
makeVerb('it_1058',1058,'ricordare','to remember — see 274','are','avere','ricordato',null,['—'],['a1']),
makeVerb('it_1059',1059,'dimenticarsi','to forget (refl.)','are','essere','dimenticato',null,['Mi sono dimenticato.'],['a1']),
makeVerb('it_1060',1060,'abituarsi','to get used to','are','essere','abituato',null,['Mi sono abituato al freddo.'],['a2']),

// ── NOUNS 1061-1160 ─────────────────────────────────────────────────────────
n('it_1061',1061,'accademia','academy','feminine','accademie',['Studia all\'accademia.'],['b1']),
n('it_1062',1062,'istituto','institute','masculine','istituti',['Un istituto tecnico.'],['b1']),
n('it_1063',1063,'facoltà','faculty/school','feminine','facoltà',['Studia alla facoltà di medicina.'],['b1']),
n('it_1064',1064,'tesi','thesis','feminine','tesi',['Sto scrivendo la tesi.'],['b1']),
n('it_1065',1065,'ricercatore','researcher','masculine','ricercatori',['È un ricercatore.'],['b1']),
n('it_1066',1066,'scienziato','scientist','masculine','scienziati',['Lo scienziato studia i pianeti.'],['a2']),
n('it_1067',1067,'chimico','chemist/chemical','masculine','chimici',['Il chimico lavora in laboratorio.'],['b1']),
n('it_1068',1068,'fisico','physicist/physical','masculine','fisici',['Il fisico studia la materia.'],['b1']),
n('it_1069',1069,'matematico','mathematician','masculine','matematici',['Il matematico risolve equazioni.'],['b1']),
n('it_1070',1070,'biologo','biologist','masculine','biologi',['Il biologo studia gli esseri viventi.'],['b1']),
n('it_1071',1071,'laboratorio','laboratory','masculine','laboratori',['Lavoro in laboratorio.'],['a2']),
n('it_1072',1072,'esperimento','experiment','masculine','esperimenti',['Un esperimento scientifico.'],['a2']),
n('it_1073',1073,'teoria','theory','feminine','teorie',['La teoria della relatività.'],['b1']),
n('it_1074',1074,'ipotesi','hypothesis','feminine','ipotesi',['Faccio un\'ipotesi.'],['b1']),
n('it_1075',1075,'scoperta','discovery','feminine','scoperte',['Una grande scoperta.'],['a2']),
n('it_1076',1076,'invenzione','invention','feminine','invenzioni',['L\'invenzione del telefono.'],['a2']),
n('it_1077',1077,'tecnologia','technology','feminine','tecnologie',['La tecnologia avanza.'],['a2']),
n('it_1078',1078,'innovazione','innovation','feminine','innovazioni',['L\'innovazione è importante.'],['b1']),
n('it_1079',1079,'intelligenza artificiale','artificial intelligence','feminine',null,['L\'intelligenza artificiale cambia tutto.'],['b1']),
n('it_1080',1080,'software','software','masculine','software',['Questo software è utile.'],['a2']),
n('it_1081',1081,'applicazione','application/app','feminine','applicazioni',['Ho scaricato un\'applicazione.'],['a2']),
n('it_1082',1082,'sito web','website','masculine','siti web',['Visita il nostro sito web.'],['a2']),
n('it_1083',1083,'rete','network/web','feminine','reti',['La rete internet.'],['a2']),
n('it_1084',1084,'dato','data/datum','masculine','dati',['Analisi dei dati.'],['b1']),
n('it_1085',1085,'algoritmo','algorithm','masculine','algoritmi',['L\'algoritmo calcola.'],['b1']),
n('it_1086',1086,'codice','code','masculine','codici',['Il codice è corretto.'],['b1']),
n('it_1087',1087,'schermo','screen','masculine','schermi',['Lo schermo è rotto.'],['a2']),
n('it_1088',1088,'tastiera','keyboard','feminine','tastiere',['La tastiera del computer.'],['a2']),
n('it_1089',1089,'mouse','mouse (computer)','masculine','mouse',['Uso il mouse.'],['a2']),
n('it_1090',1090,'stampante','printer','feminine','stampanti',['La stampante non funziona.'],['a2']),
n('it_1091',1091,'file','file','masculine','file',['Salvo il file.'],['a2']),
n('it_1092',1092,'cartella','folder/bag','feminine','cartelle',['Salvo nella cartella.'],['a2']),
n('it_1093',1093,'batteria','battery','feminine','batterie',['La batteria è scarica.'],['a2']),
n('it_1094',1094,'caricatore','charger','masculine','caricatori',['Ho dimenticato il caricatore.'],['a2']),
n('it_1095',1095,'cavo','cable/wire','masculine','cavi',['Il cavo USB.'],['a2']),
n('it_1096',1096,'signal','signal — (segnale)','masculine','segnali',['Il segnale è debole.'],['a2']),
n('it_1097',1097,'connessione','connection','feminine','connessioni',['La connessione è lenta.'],['a2']),
n('it_1098',1098,'password','password','feminine','password',['Inserisci la password.'],['a2']),
n('it_1099',1099,'account','account','masculine','account',['Ho un account.'],['a2']),
n('it_1100',1100,'profilo','profile','masculine','profili',['Il mio profilo.'],['a2']),
n('it_1101',1101,'messaggio','message','masculine','messaggi',['Ho un messaggio.'],['a1']),
n('it_1102',1102,'email','email','feminine','email',['Manda una email.'],['a1']),
n('it_1103',1103,'chiamata','phone call','feminine','chiamate',['Ho una chiamata.'],['a1']),
n('it_1104',1104,'videochiamata','video call','feminine','videochiamate',['Facciamo una videochiamata.'],['a2']),
n('it_1105',1105,'notifica','notification','feminine','notifiche',['Ho molte notifiche.'],['a2']),
n('it_1106',1106,'social media','social media','masculine',null,['Uso i social media.'],['a2']),
n('it_1107',1107,'pubblicità','advertising/ad','feminine','pubblicità',['Troppa pubblicità!'],['a2']),
n('it_1108',1108,'stampa','press/print','feminine',null,['La stampa libera è importante.'],['b1']),
n('it_1109',1109,'redazione','editorial office','feminine','redazioni',['Lavora in redazione.'],['b1']),
n('it_1110',1110,'articolo','article','masculine','articoli',['Ho letto un articolo interessante.'],['a2']),
n('it_1111',1111,'titolo','title/headline','masculine','titoli',['Il titolo è provocatorio.'],['a2']),
n('it_1112',1112,'capitolo','chapter — see 798','masculine','capitoli',['Leggi il capitolo.'],['a2']),
n('it_1113',1113,'pagina','page','feminine','pagine',['Sei a che pagina?'],['a1']),
n('it_1114',1114,'indice','index/table of contents','masculine','indici',['Guarda nell\'indice.'],['a2']),
n('it_1115',1115,'glossario','glossary','masculine','glossari',['Consulta il glossario.'],['b1']),
n('it_1116',1116,'appendice','appendix','feminine','appendici',['Vedi l\'appendice.'],['b1']),
n('it_1117',1117,'nota','note','feminine','note',['Prendo nota.'],['a2']),
n('it_1118',1118,'commento','comment','masculine','commenti',['Fai un commento.'],['a2']),
n('it_1119',1119,'recensione','review/review','feminine','recensioni',['Leggo le recensioni.'],['a2']),
n('it_1120',1120,'critica','criticism/review','feminine','critiche',['Ha ricevuto buone critiche.'],['a2']),
n('it_1121',1121,'valutazione','evaluation/rating','feminine','valutazioni',['Dai una valutazione.'],['a2']),
n('it_1122',1122,'giudizio','judgment/opinion','masculine','giudizi',['Esprimo il mio giudizio.'],['b1']),
n('it_1123',1123,'paragone','comparison','masculine','paragoni',['Non c\'è paragone.'],['a2']),
n('it_1124',1124,'analogia','analogy','feminine','analogie',['Una buona analogia.'],['b1']),
n('it_1125',1125,'metafora','metaphor','feminine','metafore',['Una bella metafora.'],['b1']),
n('it_1126',1126,'simbolo','symbol','masculine','simboli',['Il simbolo della pace.'],['a2']),
n('it_1127',1127,'segno','sign/symbol','masculine','segni',['Un brutto segno.'],['a2']),
n('it_1128',1128,'immagine','image','feminine','immagini',['Un\'immagine vale mille parole.'],['a2']),
n('it_1129',1129,'fotografia','photograph','feminine','fotografie',['Una bella fotografia.'],['a1']),
n('it_1130',1130,'dipinto','painting','masculine','dipinti',['Un bel dipinto.'],['a2']),
n('it_1131',1131,'scultura','sculpture','feminine','sculture',['Una scultura di Michelangelo.'],['a2']),
n('it_1132',1132,'architettura','architecture','feminine',null,['L\'architettura italiana è famosa.'],['a2']),
n('it_1133',1133,'monumento','monument','masculine','monumenti',['Il Colosseo è un monumento.'],['a1']),
n('it_1134',1134,'patrimonio','heritage','masculine','patrimoni',['Patrimonio dell\'umanità.'],['b1']),
n('it_1135',1135,'antichità','antiquity','feminine','antichità',['Un reperto dell\'antichità.'],['b1']),
n('it_1136',1136,'rinascimento','Renaissance','masculine',null,['Il Rinascimento italiano.'],['b1']),
n('it_1137',1137,'barocco','Baroque','masculine',null,['L\'arte barocca.'],['b1']),
n('it_1138',1138,'periodo','period','masculine','periodi',['In questo periodo.'],['a2']),
n('it_1139',1139,'secolo','century','masculine','secoli',['Il ventunesimo secolo.'],['a2']),
n('it_1140',1140,'millennio','millennium','masculine','millenni',['Il nuovo millennio.'],['b1']),
n('it_1141',1141,'era','era','feminine','ere',['Un\'era nuova.'],['b1']),
n('it_1142',1142,'civiltà','civilization','feminine','civiltà',['Le antiche civiltà.'],['a2']),
n('it_1143',1143,'impero','empire','masculine','imperi',['L\'impero romano.'],['a2']),
n('it_1144',1144,'regno','kingdom','masculine','regni',['Il regno d\'Italia.'],['a2']),
n('it_1145',1145,'repubblica','republic','feminine','repubbliche',['La Repubblica Italiana.'],['a2']),
n('it_1146',1146,'democrazia','democracy','feminine','democrazie',['La democrazia è importante.'],['a2']),
n('it_1147',1147,'elezione','election','feminine','elezioni',['Le elezioni si avvicinano.'],['a2']),
n('it_1148',1148,'voto','vote — see 572','masculine','voti',['Il mio voto.'],['a2']),
n('it_1149',1149,'partito','political party','masculine','partiti',['Il partito ha vinto.'],['a2']),
n('it_1150',1150,'parlamento','parliament','masculine','parlamenti',['Il parlamento vota.'],['a2']),
n('it_1151',1151,'ministro','minister','masculine','ministri',['Il ministro della salute.'],['a2']),
n('it_1152',1152,'presidente','president','masculine','presidenti',['Il presidente parla.'],['a1']),
n('it_1153',1153,'sindaco','mayor','masculine','sindaci',['Il sindaco di Roma.'],['a2']),
n('it_1154',1154,'consigliere','councillor','masculine','consiglieri',['Un consigliere comunale.'],['b1']),
n('it_1155',1155,'partecipazione','participation','feminine','partecipazioni',['La partecipazione è alta.'],['b1']),
n('it_1156',1156,'protesta','protest','feminine','proteste',['Una protesta pacifica.'],['a2']),
n('it_1157',1157,'sciopero','strike','masculine','scioperi',['I lavoratori fanno sciopero.'],['a2']),
n('it_1158',1158,'manifestazione','demonstration','feminine','manifestazioni',['Una grande manifestazione.'],['a2']),
n('it_1159',1159,'rivoluzione','revolution','feminine','rivoluzioni',['La rivoluzione francese.'],['a2']),
n('it_1160',1160,'crisi','crisis','feminine','crisi',['Una crisi economica.'],['a2']),

// ── ADJECTIVES 1161-1210 ─────────────────────────────────────────────────────
adj('it_1161',1161,'globale','global','globali',['Una prospettiva globale.'],['b1']),
adj('it_1162',1162,'locale','local','locali',['Un prodotto locale.'],['a2']),
adj('it_1163',1163,'nazionale','national','nazionali',['L\'inno nazionale.'],['a2']),
adj('it_1164',1164,'internazionale','international','internazionali',['Un accordo internazionale.'],['a2']),
adj('it_1165',1165,'pubblico','public','pubblici',['Un luogo pubblico.'],['a2']),
adj('it_1166',1166,'privato','private','privati',['Una scuola privata.'],['a2']),
adj('it_1167',1167,'ufficiale','official','ufficiali',['Una dichiarazione ufficiale.'],['a2']),
adj('it_1168',1168,'formale','formal','formali',['Un tono formale.'],['a2']),
adj('it_1169',1169,'informale','informal','informali',['Un incontro informale.'],['a2']),
adj('it_1170',1170,'professionale','professional','professionali',['Un atteggiamento professionale.'],['a2']),
adj('it_1171',1171,'personale','personal','personali',['Una questione personale.'],['a2']),
adj('it_1172',1172,'collettivo','collective','collettivi',['Una responsabilità collettiva.'],['b1']),
adj('it_1173',1173,'individuale','individual','individuali',['Una scelta individuale.'],['b1']),
adj('it_1174',1174,'oggettivo','objective','oggettivi',['Un giudizio oggettivo.'],['b1']),
adj('it_1175',1175,'soggettivo','subjective','soggettivi',['Un\'opinione soggettiva.'],['b1']),
adj('it_1176',1176,'positivo','positive','positivi',['Un risultato positivo.'],['a1']),
adj('it_1177',1177,'negativo','negative','negativi',['Un effetto negativo.'],['a1']),
adj('it_1178',1178,'neutro','neutral','neutri',['Un paese neutro.'],['b1']),
adj('it_1179',1179,'ambiguo','ambiguous','ambigui',['Una risposta ambigua.'],['b1']),
adj('it_1180',1180,'contraddittorio','contradictory','contraddittori',['È contraddittorio.'],['b1']),
adj('it_1181',1181,'coerente','coherent/consistent','coerenti',['Un discorso coerente.'],['b1']),
adj('it_1182',1182,'incoerente','incoherent','incoerenti',['È incoerente.'],['b1']),
adj('it_1183',1183,'efficace','effective','efficaci',['Un metodo efficace.'],['b1']),
adj('it_1184',1184,'inefficace','ineffective','inefficaci',['Un approccio inefficace.'],['b1']),
adj('it_1185',1185,'efficiente','efficient','efficienti',['Un sistema efficiente.'],['b1']),
adj('it_1186',1186,'insufficiente','insufficient','insufficienti',['Le risorse sono insufficienti.'],['b1']),
adj('it_1187',1187,'adeguato','adequate','adeguati',['Una risposta adeguata.'],['b1']),
adj('it_1188',1188,'inadeguato','inadequate','inadeguati',['Una risposta inadeguata.'],['b1']),
adj('it_1189',1189,'appropriato','appropriate','appropriati',['Un comportamento appropriato.'],['b1']),
adj('it_1190',1190,'inappropriato','inappropriate','inappropriati',['Un commento inappropriato.'],['b1']),
adj('it_1191',1191,'pertinente','relevant/pertinent','pertinenti',['Una domanda pertinente.'],['b1']),
adj('it_1192',1192,'irrilevante','irrelevant','irrilevanti',['Un dettaglio irrilevante.'],['b1']),
adj('it_1193',1193,'significativo','significant','significativi',['Un cambiamento significativo.'],['b1']),
adj('it_1194',1194,'trascurabile','negligible','trascurabili',['Un errore trascurabile.'],['b1']),
adj('it_1195',1195,'essenziale','essential','essenziali',['Un elemento essenziale.'],['b1']),
adj('it_1196',1196,'fondamentale','fundamental','fondamentali',['Un diritto fondamentale.'],['b1']),
adj('it_1197',1197,'principale','main/principal','principali',['Il personaggio principale.'],['a2']),
adj('it_1198',1198,'secondario','secondary','secondari',['Un ruolo secondario.'],['a2']),
adj('it_1199',1199,'definitivo','definitive/final','definitivi',['Una risposta definitiva.'],['b1']),
adj('it_1200',1200,'provvisorio','provisional','provvisori',['Una soluzione provvisoria.'],['b1']),

// ── ADVERBS 1201-1250 ─────────────────────────────────────────────────────────
adv('it_1201',1201,'pienamente','fully',['Sono pienamente d\'accordo.'],['b1']),
adv('it_1202',1202,'completamente','completely',['È completamente sbagliato.'],['a2']),
adv('it_1203',1203,'totalmente','totally',['Sono totalmente contrario.'],['b1']),
adv('it_1204',1204,'parzialmente','partially',['È parzialmente corretto.'],['b1']),
adv('it_1205',1205,'generalmente','generally',['Generalmente arrivo in orario.'],['a2']),
adv('it_1206',1206,'tipicamente','typically',['È tipicamente italiano.'],['b1']),
adv('it_1207',1207,'principalmente','mainly',['Principalmente per questo.'],['b1']),
adv('it_1208',1208,'essenzialmente','essentially',['È essenzialmente corretto.'],['b1']),
adv('it_1209',1209,'fondamentalmente','fundamentally',['Fondamentalmente ha ragione.'],['b1']),
adv('it_1210',1210,'specificamente','specifically',['Voglio sapere specificamente.'],['b1']),
adv('it_1211',1211,'precisamente','precisely',['Precisamente così.'],['b1']),
adv('it_1212',1212,'innanzitutto','first of all',['Innanzitutto, grazie.'],['b1']),
adv('it_1213',1213,'anzitutto','first of all',['Anzitutto, presentati.'],['b1']),
adv('it_1214',1214,'in primo luogo','in the first place',['In primo luogo, è sbagliato.'],['b1']),
adv('it_1215',1215,'in secondo luogo','secondly',['In secondo luogo, costa troppo.'],['b1']),
adv('it_1216',1216,'infine','finally/lastly',['Infine, voglio ringraziarvi.'],['b1']),
adv('it_1217',1217,'in conclusione','in conclusion',['In conclusione, è positivo.'],['b1']),
adv('it_1218',1218,'riassumendo','in summary',['Riassumendo, ecco i punti.'],['b1']),
adv('it_1219',1219,'in altre parole','in other words',['In altre parole, no.'],['b1']),
adv('it_1220',1220,'vale a dire','that is to say',['Vale a dire, è finita.'],['b1']),
adv('it_1221',1221,'d\'altra parte','on the other hand',['D\'altra parte, capisco.'],['b1']),
adv('it_1222',1222,'d\'altronde','after all/besides',['D\'altronde, è normale.'],['b1']),
adv('it_1223',1223,'a proposito','by the way',['A proposito, hai chiamato?'],['b1']),
adv('it_1224',1224,'nel frattempo','meanwhile',['Nel frattempo, aspetto.'],['b1']),
adv('it_1225',1225,'allo stesso tempo','at the same time',['Allo stesso tempo, capisco.'],['b1']),
adv('it_1226',1226,'nel complesso','overall',['Nel complesso, è positivo.'],['b1']),
adv('it_1227',1227,'in genere','in general',['In genere sono puntuale.'],['a2']),
adv('it_1228',1228,'in realtà','in reality/actually',['In realtà non è così.'],['a2']),
adv('it_1229',1229,'in teoria','in theory',['In teoria funziona.'],['a2']),
adv('it_1230',1230,'in pratica','in practice',['In pratica è difficile.'],['a2']),
adv('it_1231',1231,'eventualmente','eventually/possibly',['Eventualmente mi faccio vivo.'],['b1']),
adv('it_1232',1232,'necessariamente','necessarily',['Non necessariamente.'],['b1']),
adv('it_1233',1233,'automaticamente','automatically',['Si salva automaticamente.'],['b1']),
adv('it_1234',1234,'manualmente','manually',['Lo faccio manualmente.'],['b1']),
adv('it_1235',1235,'gradualmente','gradually',['Migliora gradualmente.'],['b1']),
adv('it_1236',1236,'progressivamente','progressively',['Migliora progressivamente.'],['b1']),
adv('it_1237',1237,'costantemente','constantly',['Lavora costantemente.'],['b1']),
adv('it_1238',1238,'continuamente','continuously',['Piange continuamente.'],['b1']),
adv('it_1239',1239,'periodicamente','periodically',['Lo faccio periodicamente.'],['b1']),
adv('it_1240',1240,'occasionalmente','occasionally',['Lo vedo occasionalmente.'],['b1']),
adv('it_1241',1241,'tipicamente','typically',['È tipicamente italiano.'],['b1']),
adv('it_1242',1242,'tradizionalmente','traditionally',['Tradizionalmente si fa così.'],['b1']),
adv('it_1243',1243,'storicamente','historically — see 661','storicamente',['—'],['b1']),
adv('it_1244',1244,'culturalmente','culturally — see 665','culturalmente',['—'],['b1']),
adv('it_1245',1245,'semplicemente','simply',['Semplicemente perfetto.'],['a2']),
adv('it_1246',1246,'chiaramente','clearly',['Chiaramente non capisce.'],['a2']),
adv('it_1247',1247,'evidentemente','evidently',['Evidentemente ha torto.'],['b1']),
adv('it_1248',1248,'logicamente','logically',['Logicamente sì.'],['b1']),
adv('it_1249',1249,'eticamente','ethically',['È eticamente corretto.'],['b1']),
adv('it_1250',1250,'moralmente','morally',['È moralmente sbagliato.'],['b1']),
];

const final=entries.filter(e=>!e.examples[0].startsWith('—'));
console.log(`Generated ${final.length} entries, ranks ${final[0].rank}-${final[final.length-1].rank}`);
const ranks=final.map(e=>e.rank);
const dups=ranks.filter((r,i)=>ranks.indexOf(r)!==i);
if(dups.length) console.warn('Duplicate ranks:',dups);
fs.writeFileSync(path.join(__dirname,'../src/data/words-005.json'),JSON.stringify(final,null,2));
console.log('words-005.json written.');
