const fs = require('fs');
const path = require('path');

// words-003.json: ranks 501-750, IDs it_0501-it_0750, A2/B1 level

function v(id,rank,ita,eng,grp,irr,pres,ppAux,pp,ppF,impf,fut,cond,cong,irregF,ex,tags){
  const ppFull={auxiliary:ppAux,pastParticiple:pp,...ppF};
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'verb',
    gender:null,plural:null,conjugationGroup:grp,irregular:irr,
    conjugations:{presente:pres,passatoProssimo:ppFull,imperfetto:impf,futuroSemplice:fut,condizionale:cond,congiuntivoPresente:cong},
    irregularForms:irregF||null,examples:ex,tags,needsReview:false};
}
function n(id,rank,ita,eng,gender,plural,ex,tags,irr=false){
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'noun',
    gender,plural,conjugationGroup:null,irregular:irr,
    conjugations:null,irregularForms:null,examples:ex,tags,needsReview:false};
}
function adj(id,rank,ita,eng,plural,ex,tags){
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'adjective',
    gender:'masculine',plural,conjugationGroup:null,irregular:false,
    conjugations:null,irregularForms:null,examples:ex,tags,needsReview:false};
}
function adv(id,rank,ita,eng,ex,tags){
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'adverb',
    gender:null,plural:null,conjugationGroup:null,irregular:false,
    conjugations:null,irregularForms:null,examples:ex,tags,needsReview:false};
}
function prep(id,rank,ita,eng,ex,tags){
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'preposition',
    gender:null,plural:null,conjugationGroup:null,irregular:false,
    conjugations:null,irregularForms:null,examples:ex,tags,needsReview:false};
}
function conj(id,rank,ita,eng,ex,tags){
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'conjunction',
    gender:null,plural:null,conjugationGroup:null,irregular:false,
    conjugations:null,irregularForms:null,examples:ex,tags,needsReview:false};
}

const entries=[
// ── VERBS 501-560 ──────────────────────────────────────────────────────────
v('it_0501',501,'partire','to leave/depart','ire',false,
  {io:'parto',tu:'parti',lui:'parte',noi:'partiamo',voi:'partite',loro:'partono'},
  'essere','partito',{io:'sono partito',tu:'sei partito',lui:'è partito',noi:'siamo partiti',voi:'siete partiti',loro:'sono partiti'},
  {io:'partivo',tu:'partivi',lui:'partiva',noi:'partivamo',voi:'partivate',loro:'partivano'},
  {io:'partirò',tu:'partirai',lui:'partirà',noi:'partiremo',voi:'partirete',loro:'partiranno'},
  {io:'partirei',tu:'partiresti',lui:'partirebbe',noi:'partiremmo',voi:'partireste',loro:'partirebbero'},
  {io:'parta',tu:'parta',lui:'parta',noi:'partiamo',voi:'partiate',loro:'partano'},
  null,['Quando parti?'],['a1']),

v('it_0502',502,'arrivare','to arrive','are',false,
  {io:'arrivo',tu:'arrivi',lui:'arriva',noi:'arriviamo',voi:'arrivate',loro:'arrivano'},
  'essere','arrivato',{io:'sono arrivato',tu:'sei arrivato',lui:'è arrivato',noi:'siamo arrivati',voi:'siete arrivati',loro:'sono arrivati'},
  {io:'arrivavo',tu:'arrivavi',lui:'arrivava',noi:'arrivavamo',voi:'arrivavate',loro:'arrivavano'},
  {io:'arriverò',tu:'arriverai',lui:'arriverà',noi:'arriveremo',voi:'arriverete',loro:'arriveranno'},
  {io:'arriverei',tu:'arriveresti',lui:'arriverebbe',noi:'arriveremmo',voi:'arrivereste',loro:'arriverebbero'},
  {io:'arrivi',tu:'arrivi',lui:'arrivi',noi:'arriviamo',voi:'arriviate',loro:'arrivino'},
  null,['A che ora arrivi?'],['a1']),

v('it_0503',503,'nascere','to be born','ere',false,
  {io:'nasco',tu:'nasci',lui:'nasce',noi:'nasciamo',voi:'nascete',loro:'nascono'},
  'essere','nato',{io:'sono nato',tu:'sei nato',lui:'è nato',noi:'siamo nati',voi:'siete nati',loro:'sono nati'},
  {io:'nascevo',tu:'nascevi',lui:'nasceva',noi:'nascevamo',voi:'nascevate',loro:'nascevano'},
  {io:'nascerò',tu:'nascerai',lui:'nascerà',noi:'nasceremo',voi:'nascerete',loro:'nasceranno'},
  {io:'nascerei',tu:'nasceresti',lui:'nascerebbe',noi:'nasceremmo',voi:'nascereste',loro:'nascerebbero'},
  {io:'nasca',tu:'nasca',lui:'nasca',noi:'nasciamo',voi:'nasciate',loro:'nascano'},
  {pastParticiple:'nato'},['Dove sei nato?'],['a1']),

v('it_0504',504,'morire','to die','ire',true,
  {io:'muoio',tu:'muori',lui:'muore',noi:'moriamo',voi:'morite',loro:'muoiono'},
  'essere','morto',{io:'sono morto',tu:'sei morto',lui:'è morto',noi:'siamo morti',voi:'siete morti',loro:'sono morti'},
  {io:'morivo',tu:'morivi',lui:'moriva',noi:'morivamo',voi:'morivate',loro:'morivano'},
  {io:'morrò',tu:'morrai',lui:'morrà',noi:'morremo',voi:'morrete',loro:'morranno'},
  {io:'morrei',tu:'morresti',lui:'morrebbi',noi:'morremmo',voi:'morreste',loro:'morrebbero'},
  {io:'muoia',tu:'muoia',lui:'muoia',noi:'moriamo',voi:'moriate',loro:'muoiano'},
  {presente:'muoio/muori/muore',futuro:'morrò'},['È morto ieri.'],['a2']),

v('it_0505',505,'crescere','to grow/grow up','ere',false,
  {io:'cresco',tu:'cresci',lui:'cresce',noi:'cresciamo',voi:'crescete',loro:'crescono'},
  'essere','cresciuto',{io:'sono cresciuto',tu:'sei cresciuto',lui:'è cresciuto',noi:'siamo cresciuti',voi:'siete cresciuti',loro:'sono cresciuti'},
  {io:'crescevo',tu:'crescevi',lui:'cresceva',noi:'crescevamo',voi:'crescevate',loro:'crescevano'},
  {io:'crescerò',tu:'crescerai',lui:'crescerà',noi:'cresceremo',voi:'crescerete',loro:'cresceranno'},
  {io:'crescerei',tu:'cresceresti',lui:'crescerebbe',noi:'cresceremmo',voi:'crescereste',loro:'crescerebbero'},
  {io:'cresca',tu:'cresca',lui:'cresca',noi:'cresciamo',voi:'cresciate',loro:'crescano'},
  null,['I bambini crescono in fretta.'],['a2']),

v('it_0506',506,'diventare','to become','are',false,
  {io:'divento',tu:'diventi',lui:'diventa',noi:'diventiamo',voi:'diventate',loro:'diventano'},
  'essere','diventato',{io:'sono diventato',tu:'sei diventato',lui:'è diventato',noi:'siamo diventati',voi:'siete diventati',loro:'sono diventati'},
  {io:'diventavo',tu:'diventavi',lui:'diventava',noi:'diventavamo',voi:'diventavate',loro:'diventavano'},
  {io:'diventerò',tu:'diventerai',lui:'diventerà',noi:'diventeremo',voi:'diventerete',loro:'diventeranno'},
  {io:'diventerei',tu:'diventeresti',lui:'diventerebbe',noi:'diventeremmo',voi:'diventereste',loro:'diventerebbero'},
  {io:'diventi',tu:'diventi',lui:'diventi',noi:'diventiamo',voi:'diventiate',loro:'diventino'},
  null,['Voglio diventare medico.'],['a1']),

v('it_0507',507,'sembrare','to seem/look like','are',false,
  {io:'sembro',tu:'sembri',lui:'sembra',noi:'sembriamo',voi:'sembrate',loro:'sembrano'},
  'essere','sembrato',{io:'sono sembrato',tu:'sei sembrato',lui:'è sembrato',noi:'siamo sembrati',voi:'siete sembrati',loro:'sono sembrati'},
  {io:'sembravo',tu:'sembravi',lui:'sembrava',noi:'sembravamo',voi:'sembravate',loro:'sembravano'},
  {io:'sembrerò',tu:'sembrerai',lui:'sembrerà',noi:'sembreremo',voi:'sembrerete',loro:'sembreranno'},
  {io:'sembrerei',tu:'sembreresti',lui:'sembrerebbe',noi:'sembreremmo',voi:'sembrereste',loro:'sembrerebbero'},
  {io:'sembri',tu:'sembri',lui:'sembri',noi:'sembriamo',voi:'sembrriate',loro:'sembrino'},
  null,['Sembra stanco.'],['a1']),

v('it_0508',508,'rimanere','to remain/stay','ere',true,
  {io:'rimango',tu:'rimani',lui:'rimane',noi:'rimaniamo',voi:'rimanete',loro:'rimangono'},
  'essere','rimasto',{io:'sono rimasto',tu:'sei rimasto',lui:'è rimasto',noi:'siamo rimasti',voi:'siete rimasti',loro:'sono rimasti'},
  {io:'rimanevo',tu:'rimanevi',lui:'rimaneva',noi:'rimanevamo',voi:'rimanevate',loro:'rimanevano'},
  {io:'rimarrò',tu:'rimarrai',lui:'rimarrà',noi:'rimarremo',voi:'rimarrete',loro:'rimarranno'},
  {io:'rimarrei',tu:'rimarresti',lui:'rimarrebbe',noi:'rimarremmo',voi:'rimarreste',loro:'rimarrebbero'},
  {io:'rimanga',tu:'rimanga',lui:'rimanga',noi:'rimaniamo',voi:'rimaniate',loro:'rimangano'},
  {presente:'rimango',futuro:'rimarrò',pastParticiple:'rimasto'},['Rimango a casa.'],['a2']),

v('it_0509',509,'riuscire','to succeed/manage to','ire',true,
  {io:'riesco',tu:'riesci',lui:'riesce',noi:'riusciamo',voi:'riuscite',loro:'riescono'},
  'essere','riuscito',{io:'sono riuscito',tu:'sei riuscito',lui:'è riuscito',noi:'siamo riusciti',voi:'siete riusciti',loro:'sono riusciti'},
  {io:'riuscivo',tu:'riuscivi',lui:'riusciva',noi:'riuscivamo',voi:'riuscivate',loro:'riuscivano'},
  {io:'riuscirò',tu:'riuscirai',lui:'riuscirà',noi:'riusciremo',voi:'riuscirete',loro:'riusciranno'},
  {io:'riuscirei',tu:'riusciresti',lui:'riuscirebbe',noi:'riusciremmo',voi:'riuscireste',loro:'riuscirebbero'},
  {io:'riesca',tu:'riesca',lui:'riesca',noi:'riusciamo',voi:'riusciate',loro:'riescano'},
  {presente:'riesco/riesci/riesce'},['Non riesco a dormire.'],['a2']),

v('it_0510',510,'succedere','to happen','ere',false,
  {io:'succedo',tu:'succedi',lui:'succede',noi:'succediamo',voi:'succedete',loro:'succedono'},
  'essere','successo',{io:'è successo',tu:'è successo',lui:'è successo',noi:'è successo',voi:'è successo',loro:'è successo'},
  {io:'succedevo',tu:'succedevi',lui:'succedeva',noi:'succedevamo',voi:'succedevate',loro:'succedevano'},
  {io:'succederò',tu:'succederai',lui:'succederà',noi:'succederemo',voi:'succederete',loro:'succederanno'},
  {io:'succederei',tu:'succederesti',lui:'succederebbe',noi:'succederemmo',voi:'succedereste',loro:'succederebbero'},
  {io:'succeda',tu:'succeda',lui:'succeda',noi:'succediamo',voi:'succediate',loro:'succedano'},
  {pastParticiple:'successo'},['Cosa è successo?'],['a1']),

v('it_0511',511,'provare','to try/prove','are',false,
  {io:'provo',tu:'provi',lui:'prova',noi:'proviamo',voi:'provate',loro:'provano'},
  'avere','provato',{io:'ho provato',tu:'hai provato',lui:'ha provato',noi:'abbiamo provato',voi:'avete provato',loro:'hanno provato'},
  {io:'provavo',tu:'provavi',lui:'provava',noi:'provavamo',voi:'provavate',loro:'provavano'},
  {io:'proverò',tu:'proverai',lui:'proverà',noi:'proveremo',voi:'proverete',loro:'proveranno'},
  {io:'proverei',tu:'proveresti',lui:'proverebbe',noi:'proveremmo',voi:'provereste',loro:'proverebbero'},
  {io:'provi',tu:'provi',lui:'provi',noi:'proviamo',voi:'proviate',loro:'provino'},
  null,['Prova ancora.'],['a1']),

v('it_0512',512,'visitare','to visit','are',false,
  {io:'visito',tu:'visiti',lui:'visita',noi:'visitiamo',voi:'visitate',loro:'visitano'},
  'avere','visitato',{io:'ho visitato',tu:'hai visitato',lui:'ha visitato',noi:'abbiamo visitato',voi:'avete visitato',loro:'hanno visitato'},
  {io:'visitavo',tu:'visitavi',lui:'visitava',noi:'visitavamo',voi:'visitavate',loro:'visitavano'},
  {io:'visiterò',tu:'visiterai',lui:'visiterà',noi:'visiteremo',voi:'visiterete',loro:'visiteranno'},
  {io:'visiterei',tu:'visiteresti',lui:'visiterebbe',noi:'visiteremmo',voi:'visitereste',loro:'visiterebbero'},
  {io:'visiti',tu:'visiti',lui:'visiti',noi:'visitiamo',voi:'visitiate',loro:'visitino'},
  null,['Ho visitato Roma.'],['a1']),

v('it_0513',513,'decidere','to decide','ere',false,
  {io:'decido',tu:'decidi',lui:'decide',noi:'decidiamo',voi:'decidete',loro:'decidono'},
  'avere','deciso',{io:'ho deciso',tu:'hai deciso',lui:'ha deciso',noi:'abbiamo deciso',voi:'avete deciso',loro:'hanno deciso'},
  {io:'decidevo',tu:'decidevi',lui:'decideva',noi:'decidevamo',voi:'decidevate',loro:'decidevano'},
  {io:'deciderò',tu:'deciderai',lui:'deciderà',noi:'decideremo',voi:'deciderete',loro:'decideranno'},
  {io:'deciderei',tu:'decideresti',lui:'deciderebbe',noi:'decideremmo',voi:'decidereste',loro:'deciderebbero'},
  {io:'decida',tu:'decida',lui:'decida',noi:'decidiamo',voi:'decidiate',loro:'decidano'},
  {pastParticiple:'deciso'},['Hai deciso?'],['a2']),

v('it_0514',514,'continuare','to continue','are',false,
  {io:'continuo',tu:'continui',lui:'continua',noi:'continuiamo',voi:'continuate',loro:'continuano'},
  'avere','continuato',{io:'ho continuato',tu:'hai continuato',lui:'ha continuato',noi:'abbiamo continuato',voi:'avete continuato',loro:'hanno continuato'},
  {io:'continuavo',tu:'continuavi',lui:'continuava',noi:'continuavamo',voi:'continuavate',loro:'continuavano'},
  {io:'continuerò',tu:'continuerai',lui:'continuerà',noi:'continueremo',voi:'continuerete',loro:'continueranno'},
  {io:'continuerei',tu:'continueresti',lui:'continuerebbe',noi:'continueremmo',voi:'continuereste',loro:'continuerebbero'},
  {io:'continui',tu:'continui',lui:'continui',noi:'continuiamo',voi:'continuiate',loro:'continuino'},
  null,['Continua così!'],['a1']),

v('it_0515',515,'fermare','to stop/arrest','are',false,
  {io:'fermo',tu:'fermi',lui:'ferma',noi:'fermiamo',voi:'fermate',loro:'fermano'},
  'avere','fermato',{io:'ho fermato',tu:'hai fermato',lui:'ha fermato',noi:'abbiamo fermato',voi:'avete fermato',loro:'hanno fermato'},
  {io:'fermavo',tu:'fermavi',lui:'fermava',noi:'fermavamo',voi:'fermavate',loro:'fermavano'},
  {io:'fermerò',tu:'fermerai',lui:'fermerà',noi:'fermeremo',voi:'fermerete',loro:'fermeranno'},
  {io:'fermerei',tu:'fermeresti',lui:'fermerebbe',noi:'fermeremmo',voi:'fermereste',loro:'fermerebbero'},
  {io:'fermi',tu:'fermi',lui:'fermi',noi:'fermiamo',voi:'fermiate',loro:'fermino'},
  null,['Fermati!'],['a1']),

v('it_0516',516,'alzare','to raise/lift','are',false,
  {io:'alzo',tu:'alzi',lui:'alza',noi:'alziamo',voi:'alzate',loro:'alzano'},
  'avere','alzato',{io:'ho alzato',tu:'hai alzato',lui:'ha alzato',noi:'abbiamo alzato',voi:'avete alzato',loro:'hanno alzato'},
  {io:'alzavo',tu:'alzavi',lui:'alzava',noi:'alzavamo',voi:'alzavate',loro:'alzavano'},
  {io:'alzerò',tu:'alzerai',lui:'alzerà',noi:'alzeremo',voi:'alzerete',loro:'alzeranno'},
  {io:'alzerei',tu:'alzeresti',lui:'alzerebbe',noi:'alzeremmo',voi:'alzereste',loro:'alzerebbero'},
  {io:'alzi',tu:'alzi',lui:'alzi',noi:'alziamo',voi:'alziate',loro:'alzino'},
  null,['Alza la mano.'],['a1']),

v('it_0517',517,'guardare','to watch/look at','are',false,
  {io:'guardo',tu:'guardi',lui:'guarda',noi:'guardiamo',voi:'guardate',loro:'guardano'},
  'avere','guardato',{io:'ho guardato',tu:'hai guardato',lui:'ha guardato',noi:'abbiamo guardato',voi:'avete guardato',loro:'hanno guardato'},
  {io:'guardavo',tu:'guardavi',lui:'guardava',noi:'guardavamo',voi:'guardavate',loro:'guardavano'},
  {io:'guarderò',tu:'guarderai',lui:'guarderà',noi:'guarderemo',voi:'guarderete',loro:'guarderanno'},
  {io:'guarderei',tu:'guarderesti',lui:'guarderebbe',noi:'guarderemmo',voi:'guardereste',loro:'guarderebbero'},
  {io:'guardi',tu:'guardi',lui:'guardi',noi:'guardiamo',voi:'guardiate',loro:'guardino'},
  null,['Guardo la TV.'],['a1']),

v('it_0518',518,'ascoltare','to listen','are',false,
  {io:'ascolto',tu:'ascolti',lui:'ascolta',noi:'ascoltiamo',voi:'ascoltate',loro:'ascoltano'},
  'avere','ascoltato',{io:'ho ascoltato',tu:'hai ascoltato',lui:'ha ascoltato',noi:'abbiamo ascoltato',voi:'avete ascoltato',loro:'hanno ascoltato'},
  {io:'ascoltavo',tu:'ascoltavi',lui:'ascoltava',noi:'ascoltavamo',voi:'ascoltavate',loro:'ascoltavano'},
  {io:'ascolterò',tu:'ascolterai',lui:'ascolterà',noi:'ascolteremo',voi:'ascolterete',loro:'ascolteranno'},
  {io:'ascolterei',tu:'ascolteresti',lui:'ascolterebbe',noi:'ascolteremmo',voi:'ascoltereste',loro:'ascolterebbero'},
  {io:'ascolti',tu:'ascolti',lui:'ascolti',noi:'ascoltiamo',voi:'ascoltiate',loro:'ascoltino'},
  null,['Ascolto la musica.'],['a1']),

v('it_0519',519,'toccare','to touch','are',false,
  {io:'tocco',tu:'tocchi',lui:'tocca',noi:'tocchiamo',voi:'toccate',loro:'toccano'},
  'avere','toccato',{io:'ho toccato',tu:'hai toccato',lui:'ha toccato',noi:'abbiamo toccato',voi:'avete toccato',loro:'hanno toccato'},
  {io:'toccavo',tu:'toccavi',lui:'toccava',noi:'toccavamo',voi:'toccavate',loro:'toccavano'},
  {io:'toccherò',tu:'toccherai',lui:'toccherà',noi:'toccheremo',voi:'toccherete',loro:'toccheranno'},
  {io:'toccrei',tu:'toccheresti',lui:'toccherebbe',noi:'toccheremmo',voi:'tocchereste',loro:'toccherebbero'},
  {io:'tocchi',tu:'tocchi',lui:'tocchi',noi:'tocchiamo',voi:'tocchiate',loro:'tocchino'},
  null,['Non toccare!'],['a1']),

v('it_0520',520,'seguire','to follow','ire',false,
  {io:'seguo',tu:'segui',lui:'segue',noi:'seguiamo',voi:'seguite',loro:'seguono'},
  'avere','seguito',{io:'ho seguito',tu:'hai seguito',lui:'ha seguito',noi:'abbiamo seguito',voi:'avete seguito',loro:'hanno seguito'},
  {io:'seguivo',tu:'seguivi',lui:'seguiva',noi:'seguivamo',voi:'seguivate',loro:'seguivano'},
  {io:'seguirò',tu:'seguirai',lui:'seguirà',noi:'seguiremo',voi:'seguirete',loro:'seguiranno'},
  {io:'seguirei',tu:'seguiresti',lui:'seguirebbe',noi:'seguiremmo',voi:'seguireste',loro:'seguirebbero'},
  {io:'segua',tu:'segua',lui:'segua',noi:'seguiamo',voi:'seguiate',loro:'seguano'},
  null,['Segui le istruzioni.'],['a2']),

v('it_0521',521,'permettere','to allow/permit','ere',false,
  {io:'permetto',tu:'permetti',lui:'permette',noi:'permettiamo',voi:'permettete',loro:'permettono'},
  'avere','permesso',{io:'ho permesso',tu:'hai permesso',lui:'ha permesso',noi:'abbiamo permesso',voi:'avete permesso',loro:'hanno permesso'},
  {io:'permettevo',tu:'permettevi',lui:'permetteva',noi:'permettevamo',voi:'permettevate',loro:'permettevano'},
  {io:'permetterò',tu:'permetterai',lui:'permetterà',noi:'permetteremo',voi:'permetterete',loro:'permetteranno'},
  {io:'permetterei',tu:'permetteresti',lui:'permetterebbe',noi:'permetteremmo',voi:'permettereste',loro:'permetterebbero'},
  {io:'permetta',tu:'permetta',lui:'permetta',noi:'permettiamo',voi:'permettiate',loro:'permettano'},
  {pastParticiple:'permesso'},['Non è permesso fumare.'],['a2']),

v('it_0522',522,'ricevere','to receive','ere',false,
  {io:'ricevo',tu:'ricevi',lui:'riceve',noi:'riceviamo',voi:'ricevete',loro:'ricevono'},
  'avere','ricevuto',{io:'ho ricevuto',tu:'hai ricevuto',lui:'ha ricevuto',noi:'abbiamo ricevuto',voi:'avete ricevuto',loro:'hanno ricevuto'},
  {io:'ricevevo',tu:'ricevevi',lui:'riceveva',noi:'ricevevamo',voi:'ricevevate',loro:'ricevevano'},
  {io:'riceverò',tu:'riceverai',lui:'riceverà',noi:'riceveremo',voi:'riceverete',loro:'riceveranno'},
  {io:'riceverei',tu:'riceveresti',lui:'riceverebbe',noi:'riceveremmo',voi:'ricevereste',loro:'riceverebbero'},
  {io:'riceva',tu:'riceva',lui:'riceva',noi:'riceviamo',voi:'riceviate',loro:'ricevano'},
  null,['Ho ricevuto una lettera.'],['a2']),

v('it_0523',523,'accettare','to accept','are',false,
  {io:'accetto',tu:'accetti',lui:'accetta',noi:'accettiamo',voi:'accettate',loro:'accettano'},
  'avere','accettato',{io:'ho accettato',tu:'hai accettato',lui:'ha accettato',noi:'abbiamo accettato',voi:'avete accettato',loro:'hanno accettato'},
  {io:'accettavo',tu:'accettavi',lui:'accettava',noi:'accettavamo',voi:'accettavate',loro:'accettavano'},
  {io:'accetterò',tu:'accetterai',lui:'accetterà',noi:'accetteremo',voi:'accetterete',loro:'accetteranno'},
  {io:'accetterei',tu:'accetteresti',lui:'accetterebbe',noi:'accetteremmo',voi:'accettereste',loro:'accetterebbero'},
  {io:'accetti',tu:'accetti',lui:'accetti',noi:'accettiamo',voi:'accettiate',loro:'accettino'},
  null,['Accetti la nostra offerta?'],['a2']),

v('it_0524',524,'rifiutare','to refuse','are',false,
  {io:'rifiuto',tu:'rifiuti',lui:'rifiuta',noi:'rifiutiamo',voi:'rifiutate',loro:'rifiutano'},
  'avere','rifiutato',{io:'ho rifiutato',tu:'hai rifiutato',lui:'ha rifiutato',noi:'abbiamo rifiutato',voi:'avete rifiutato',loro:'hanno rifiutato'},
  {io:'rifiutavo',tu:'rifiutavi',lui:'rifiutava',noi:'rifiutavamo',voi:'rifiutavate',loro:'rifiutavano'},
  {io:'rifiuterò',tu:'rifiuterai',lui:'rifiuterà',noi:'rifiuteremo',voi:'rifiuterete',loro:'rifiuteranno'},
  {io:'rifiuterei',tu:'rifiuteresti',lui:'rifiuterebbe',noi:'rifiuteremmo',voi:'rifiutereste',loro:'rifiuterebbero'},
  {io:'rifiuti',tu:'rifiuti',lui:'rifiuti',noi:'rifiutiamo',voi:'rifiutiate',loro:'rifiutino'},
  null,['Ha rifiutato l\'offerta.'],['a2']),

v('it_0525',525,'dimenticare','to forget','are',false,
  {io:'dimentico',tu:'dimentichi',lui:'dimentica',noi:'dimentichiamo',voi:'dimenticate',loro:'dimenticano'},
  'avere','dimenticato',{io:'ho dimenticato',tu:'hai dimenticato',lui:'ha dimenticato',noi:'abbiamo dimenticato',voi:'avete dimenticato',loro:'hanno dimenticato'},
  {io:'dimenticavo',tu:'dimenticavi',lui:'dimenticava',noi:'dimenticavamo',voi:'dimenticavate',loro:'dimenticavano'},
  {io:'dimenticherò',tu:'dimenticherai',lui:'dimenticherà',noi:'dimenticheremo',voi:'dimenticherete',loro:'dimenticheranno'},
  {io:'dimenticherei',tu:'dimenticheresti',lui:'dimenticherebbe',noi:'dimenticheremmo',voi:'dimentichereste',loro:'dimenticherebbero'},
  {io:'dimentichi',tu:'dimentichi',lui:'dimentichi',noi:'dimentichiamo',voi:'dimentichiate',loro:'dimentichino'},
  null,['Non dimenticare!'],['a1']),

v('it_0526',526,'mostrare','to show','are',false,
  {io:'mostro',tu:'mostri',lui:'mostra',noi:'mostriamo',voi:'mostrate',loro:'mostrano'},
  'avere','mostrato',{io:'ho mostrato',tu:'hai mostrato',lui:'ha mostrato',noi:'abbiamo mostrato',voi:'avete mostrato',loro:'hanno mostrato'},
  {io:'mostravo',tu:'mostravi',lui:'mostrava',noi:'mostravamo',voi:'mostravate',loro:'mostravano'},
  {io:'mostrerò',tu:'mostrerai',lui:'mostrerà',noi:'mostreremo',voi:'mostrerete',loro:'mostreranno'},
  {io:'mostrerei',tu:'mostreresti',lui:'mostrerebbe',noi:'mostreremo',voi:'mostrereste',loro:'mostrerebbero'},
  {io:'mostri',tu:'mostri',lui:'mostri',noi:'mostriamo',voi:'mostriate',loro:'mostrino'},
  null,['Mi mostri la strada?'],['a1']),

v('it_0527',527,'sorridere','to smile','ere',false,
  {io:'sorrido',tu:'sorridi',lui:'sorride',noi:'sorridiamo',voi:'sorridete',loro:'sorridono'},
  'avere','sorriso',{io:'ho sorriso',tu:'hai sorriso',lui:'ha sorriso',noi:'abbiamo sorriso',voi:'avete sorriso',loro:'hanno sorriso'},
  {io:'sorridevo',tu:'sorridevi',lui:'sorrideva',noi:'sorridevamo',voi:'sorridevate',loro:'sorridevano'},
  {io:'sorriderò',tu:'sorriderai',lui:'sorriderà',noi:'sorrideremo',voi:'sorriderete',loro:'sorrideranno'},
  {io:'sorriderei',tu:'sorrideresti',lui:'sorriderebbe',noi:'sorrideremmo',voi:'sorridereste',loro:'sorriderebbero'},
  {io:'sorrida',tu:'sorrida',lui:'sorrida',noi:'sorridiamo',voi:'sorridiate',loro:'sorridano'},
  {pastParticiple:'sorriso'},['Sorridi!'],['a2']),

v('it_0528',528,'piangere','to cry','ere',false,
  {io:'piango',tu:'piangi',lui:'piange',noi:'piangiamo',voi:'piangete',loro:'piangono'},
  'avere','pianto',{io:'ho pianto',tu:'hai pianto',lui:'ha pianto',noi:'abbiamo pianto',voi:'avete pianto',loro:'hanno pianto'},
  {io:'piangevo',tu:'piangevi',lui:'piangeva',noi:'piangevamo',voi:'piangevate',loro:'piangevano'},
  {io:'piangerò',tu:'piangerai',lui:'piangerà',noi:'piangeremo',voi:'piangerete',loro:'piangeranno'},
  {io:'piangerei',tu:'piangeresti',lui:'piangerebbe',noi:'piangeremmo',voi:'piangereste',loro:'piangerebbero'},
  {io:'pianga',tu:'pianga',lui:'pianga',noi:'piangiamo',voi:'piangiate',loro:'piangano'},
  {pastParticiple:'pianto'},['Non piangere.'],['a2']),

v('it_0529',529,'ridere','to laugh','ere',false,
  {io:'rido',tu:'ridi',lui:'ride',noi:'ridiamo',voi:'ridete',loro:'ridono'},
  'avere','riso',{io:'ho riso',tu:'hai riso',lui:'ha riso',noi:'abbiamo riso',voi:'avete riso',loro:'hanno riso'},
  {io:'ridevo',tu:'ridevi',lui:'rideva',noi:'ridevamo',voi:'ridevate',loro:'ridevano'},
  {io:'riderò',tu:'riderai',lui:'riderà',noi:'rideremo',voi:'riderete',loro:'rideranno'},
  {io:'riderei',tu:'rideresti',lui:'riderebbe',noi:'rideremmo',voi:'ridereste',loro:'riderebbero'},
  {io:'rida',tu:'rida',lui:'rida',noi:'ridiamo',voi:'ridiate',loro:'ridano'},
  {pastParticiple:'riso'},['Rido sempre.'],['a2']),

v('it_0530',530,'sognare','to dream','are',false,
  {io:'sogno',tu:'sogni',lui:'sogna',noi:'sogniamo',voi:'sognate',loro:'sognano'},
  'avere','sognato',{io:'ho sognato',tu:'hai sognato',lui:'ha sognato',noi:'abbiamo sognato',voi:'avete sognato',loro:'hanno sognato'},
  {io:'sognavo',tu:'sognavi',lui:'sognava',noi:'sognavamo',voi:'sognavate',loro:'sognavano'},
  {io:'sognerò',tu:'sognerai',lui:'sognerà',noi:'sogneremo',voi:'sognerete',loro:'sogneranno'},
  {io:'sognerei',tu:'sogneresti',lui:'sognerebbe',noi:'sogneremmo',voi:'sognereste',loro:'sognerebbero'},
  {io:'sogni',tu:'sogni',lui:'sogni',noi:'sogniamo',voi:'sogniate',loro:'sognino'},
  null,['Sogno di viaggiare.'],['a1']),

// Reflexive verbs
v('it_0531',531,'svegliarsi','to wake up','are',false,
  {io:'mi sveglio',tu:'ti svegli',lui:'si sveglia',noi:'ci svegliamo',voi:'vi svegliate',loro:'si svegliano'},
  'essere','svegliato',{io:'mi sono svegliato',tu:'ti sei svegliato',lui:'si è svegliato',noi:'ci siamo svegliati',voi:'vi siete svegliati',loro:'si sono svegliati'},
  {io:'mi svegliavo',tu:'ti svegliavi',lui:'si svegliava',noi:'ci svegliavamo',voi:'vi svegliavate',loro:'si svegliavano'},
  {io:'mi sveglierò',tu:'ti sveglierai',lui:'si sveglierà',noi:'ci sveglieremo',voi:'vi sveglierete',loro:'si sveglieranno'},
  {io:'mi sveglierei',tu:'ti sveglieresti',lui:'si sveglierebbe',noi:'ci sveglieremmo',voi:'vi svegliereste',loro:'si sveglierebbero'},
  {io:'mi svegli',tu:'ti svegli',lui:'si svegli',noi:'ci svegliamo',voi:'vi svegliate',loro:'si sveglino'},
  null,['A che ora ti svegli?'],['a1']),

v('it_0532',532,'alzarsi','to get up','are',false,
  {io:'mi alzo',tu:'ti alzi',lui:'si alza',noi:'ci alziamo',voi:'vi alzate',loro:'si alzano'},
  'essere','alzato',{io:'mi sono alzato',tu:'ti sei alzato',lui:'si è alzato',noi:'ci siamo alzati',voi:'vi siete alzati',loro:'si sono alzati'},
  {io:'mi alzavo',tu:'ti alzavi',lui:'si alzava',noi:'ci alzavamo',voi:'vi alzavate',loro:'si alzavano'},
  {io:'mi alzerò',tu:'ti alzerai',lui:'si alzerà',noi:'ci alzeremo',voi:'vi alzerete',loro:'si alzeranno'},
  {io:'mi alzerei',tu:'ti alzeresti',lui:'si alzerebbe',noi:'ci alzeremmo',voi:'vi alzereste',loro:'si alzerebbero'},
  {io:'mi alzi',tu:'ti alzi',lui:'si alzi',noi:'ci alziamo',voi:'vi alziate',loro:'si alzino'},
  null,['Mi alzo alle sette.'],['a1']),

v('it_0533',533,'lavarsi','to wash (oneself)','are',false,
  {io:'mi lavo',tu:'ti lavi',lui:'si lava',noi:'ci laviamo',voi:'vi lavate',loro:'si lavano'},
  'essere','lavato',{io:'mi sono lavato',tu:'ti sei lavato',lui:'si è lavato',noi:'ci siamo lavati',voi:'vi siete lavati',loro:'si sono lavati'},
  {io:'mi lavavo',tu:'ti lavavi',lui:'si lavava',noi:'ci lavavamo',voi:'vi lavavate',loro:'si lavavano'},
  {io:'mi laverò',tu:'ti laverai',lui:'si laverà',noi:'ci laveremo',voi:'vi laverete',loro:'si laveranno'},
  {io:'mi laverei',tu:'ti laveresti',lui:'si laverebbe',noi:'ci laveremmo',voi:'vi lavereste',loro:'si laverebbero'},
  {io:'mi lavi',tu:'ti lavi',lui:'si lavi',noi:'ci laviamo',voi:'vi laviate',loro:'si lavino'},
  null,['Mi lavo le mani.'],['a1']),

v('it_0534',534,'vestirsi','to get dressed','ire',false,
  {io:'mi vesto',tu:'ti vesti',lui:'si veste',noi:'ci vestiamo',voi:'vi vestite',loro:'si vestono'},
  'essere','vestito',{io:'mi sono vestito',tu:'ti sei vestito',lui:'si è vestito',noi:'ci siamo vestiti',voi:'vi siete vestiti',loro:'si sono vestiti'},
  {io:'mi vestivo',tu:'ti vestivi',lui:'si vestiva',noi:'ci vestivamo',voi:'vi vestivate',loro:'si vestivano'},
  {io:'mi vestirò',tu:'ti vestirai',lui:'si vestirà',noi:'ci vestiremo',voi:'vi vestirete',loro:'si vestiranno'},
  {io:'mi vestirei',tu:'ti vestiresti',lui:'si vestirebbe',noi:'ci vestiremmo',voi:'vi vestireste',loro:'si vestirebbero'},
  {io:'mi vesta',tu:'ti vesta',lui:'si vesta',noi:'ci vestiamo',voi:'vi vestiate',loro:'si vestano'},
  null,['Mi vesto in fretta.'],['a1']),

v('it_0535',535,'addormentarsi','to fall asleep','are',false,
  {io:'mi addormento',tu:'ti addormenti',lui:'si addormenta',noi:'ci addormentiamo',voi:'vi addormentate',loro:'si addormentano'},
  'essere','addormentato',{io:'mi sono addormentato',tu:'ti sei addormentato',lui:'si è addormentato',noi:'ci siamo addormentati',voi:'vi siete addormentati',loro:'si sono addormentati'},
  {io:'mi addormentavo',tu:'ti addormentavi',lui:'si addormentava',noi:'ci addormentavamo',voi:'vi addormentavate',loro:'si addormentavano'},
  {io:'mi addormenterò',tu:'ti addormenterai',lui:'si addormenterà',noi:'ci addormenteremo',voi:'vi addormenterete',loro:'si addormenteranno'},
  {io:'mi addormenterei',tu:'ti addormenteresti',lui:'si addormenterebbe',noi:'ci addormentemmo',voi:'vi addormentereste',loro:'si addormenterebbero'},
  {io:'mi addormenta',tu:'ti addormenta',lui:'si addormenta',noi:'ci addormentiamo',voi:'vi addormentiate',loro:'si addormentino'},
  null,['Mi addormento subito.'],['a1']),

v('it_0536',536,'sedersi','to sit down','ere',true,
  {io:'mi siedo',tu:'ti siedi',lui:'si siede',noi:'ci sediamo',voi:'vi sedete',loro:'si siedono'},
  'essere','seduto',{io:'mi sono seduto',tu:'ti sei seduto',lui:'si è seduto',noi:'ci siamo seduti',voi:'vi siete seduti',loro:'si sono seduti'},
  {io:'mi sedevo',tu:'ti sedevi',lui:'si sedeva',noi:'ci sedevamo',voi:'vi sedevate',loro:'si sedevano'},
  {io:'mi siederò',tu:'ti siederai',lui:'si siederà',noi:'ci siederemo',voi:'vi siederete',loro:'si siederanno'},
  {io:'mi siederei',tu:'ti siederesti',lui:'si siederebbe',noi:'ci siederemmo',voi:'vi siedereste',loro:'si siederebbero'},
  {io:'mi sieda',tu:'ti sieda',lui:'si sieda',noi:'ci sediamo',voi:'vi sediate',loro:'si siedano'},
  {presente:'mi siedo/ti siedi/si siede'},['Siediti qui.'],['a1']),

v('it_0537',537,'sposarsi','to get married','are',false,
  {io:'mi sposo',tu:'ti sposi',lui:'si sposa',noi:'ci sposiamo',voi:'vi sposate',loro:'si sposano'},
  'essere','sposato',{io:'mi sono sposato',tu:'ti sei sposato',lui:'si è sposato',noi:'ci siamo sposati',voi:'vi siete sposati',loro:'si sono sposati'},
  {io:'mi sposavo',tu:'ti sposavi',lui:'si sposava',noi:'ci sposavamo',voi:'vi sposavate',loro:'si sposavano'},
  {io:'mi sposerò',tu:'ti sposerai',lui:'si sposerà',noi:'ci sposeremo',voi:'vi sposerete',loro:'si sposeranno'},
  {io:'mi sposerei',tu:'ti sposeresti',lui:'si sposerebbe',noi:'ci sposeremmo',voi:'vi sposereste',loro:'si sposerebbero'},
  {io:'mi sposi',tu:'ti sposi',lui:'si sposi',noi:'ci sposiamo',voi:'vi sposiate',loro:'si sposino'},
  null,['Si sono sposati l\'anno scorso.'],['a2']),

v('it_0538',538,'sentirsi','to feel (state)','ire',false,
  {io:'mi sento',tu:'ti senti',lui:'si sente',noi:'ci sentiamo',voi:'vi sentite',loro:'si sentono'},
  'essere','sentito',{io:'mi sono sentito',tu:'ti sei sentito',lui:'si è sentito',noi:'ci siamo sentiti',voi:'vi siete sentiti',loro:'si sono sentiti'},
  {io:'mi sentivo',tu:'ti sentivi',lui:'si sentiva',noi:'ci sentivamo',voi:'vi sentivate',loro:'si sentivano'},
  {io:'mi sentirò',tu:'ti sentirai',lui:'si sentirà',noi:'ci sentiremo',voi:'vi sentirete',loro:'si sentiranno'},
  {io:'mi sentirei',tu:'ti sentiresti',lui:'si sentirebbe',noi:'ci sentiremmo',voi:'vi sentireste',loro:'si sentirebbero'},
  {io:'mi senta',tu:'ti senta',lui:'si senta',noi:'ci sentiamo',voi:'vi sentiate',loro:'si sentano'},
  null,['Come ti senti oggi?'],['a1']),

v('it_0539',539,'preoccuparsi','to worry','are',false,
  {io:'mi preoccupo',tu:'ti preoccupi',lui:'si preoccupa',noi:'ci preoccupiamo',voi:'vi preoccupate',loro:'si preoccupano'},
  'essere','preoccupato',{io:'mi sono preoccupato',tu:'ti sei preoccupato',lui:'si è preoccupato',noi:'ci siamo preoccupati',voi:'vi siete preoccupati',loro:'si sono preoccupati'},
  {io:'mi preoccupavo',tu:'ti preoccupavi',lui:'si preoccupava',noi:'ci preoccupavamo',voi:'vi preoccupavate',loro:'si preoccupavano'},
  {io:'mi preoccuperò',tu:'ti preoccuperai',lui:'si preoccuperà',noi:'ci preoccuperemo',voi:'vi preoccuperete',loro:'si preoccuperanno'},
  {io:'mi preoccuperei',tu:'ti preoccuperesti',lui:'si preoccuperebbe',noi:'ci preoccuperemmo',voi:'vi preoccupereste',loro:'si preoccuperebbero'},
  {io:'mi preoccupi',tu:'ti preoccupi',lui:'si preoccupi',noi:'ci preoccupiamo',voi:'vi preoccupiate',loro:'si preoccupino'},
  null,['Non preoccuparti!'],['a2']),

v('it_0540',540,'annoiarsi','to get bored','are',false,
  {io:'mi annoio',tu:'ti annoi',lui:'si annoia',noi:'ci annoiamo',voi:'vi annoiate',loro:'si annoiano'},
  'essere','annoiato',{io:'mi sono annoiato',tu:'ti sei annoiato',lui:'si è annoiato',noi:'ci siamo annoiati',voi:'vi siete annoiati',loro:'si sono annoiati'},
  {io:'mi annoiavo',tu:'ti annoiavi',lui:'si annoiava',noi:'ci annoiavamo',voi:'vi annoiavate',loro:'si annoiavano'},
  {io:'mi annoierò',tu:'ti annoierai',lui:'si annoierà',noi:'ci annoieremo',voi:'vi annoierete',loro:'si annoieranno'},
  {io:'mi annoierei',tu:'ti annoieresti',lui:'si annoierebbe',noi:'ci annoieremmo',voi:'vi annoiereste',loro:'si annoierebbero'},
  {io:'mi annoi',tu:'ti annoi',lui:'si annoi',noi:'ci annoiamo',voi:'vi annoiate',loro:'si annoino'},
  null,['Mi annoio a casa.'],['a1']),

// ── NOUNS 541-640 ──────────────────────────────────────────────────────────
n('it_0541',541,'salute','health','feminine',null,['Salute! (toast) / Come va la salute?'],['a1']),
n('it_0542',542,'malattia','illness/disease','feminine','malattie',['Ha una malattia grave.'],['a2']),
n('it_0543',543,'dolore','pain','masculine','dolori',['Ho un dolore alla schiena.'],['a1']),
n('it_0544',544,'medicina','medicine','feminine','medicine',['Prendo la medicina.'],['a1']),
n('it_0545',545,'pillola','pill','feminine','pillole',['Prendo una pillola.'],['a1']),
n('it_0546',546,'febbre','fever','feminine','febbri',['Ho la febbre.'],['a1']),
n('it_0547',547,'tosse','cough','feminine',null,['Ho la tosse.'],['a1']),
n('it_0548',548,'raffreddore','cold (illness)','masculine','raffreddori',['Ho il raffreddore.'],['a1']),
n('it_0549',549,'allergia','allergy','feminine','allergie',['Ho un\'allergia.'],['a2']),
n('it_0550',550,'operazione','operation/surgery','feminine','operazioni',['Ha subito un\'operazione.'],['a2']),
n('it_0551',551,'schiena','back (body)','feminine','schiene',['Mi fa male la schiena.'],['a1']),
n('it_0552',552,'stomaco','stomach','masculine','stomaci',['Ho mal di stomaco.'],['a1']),
n('it_0553',553,'gamba','leg','feminine','gambe',['Mi fa male una gamba.'],['a1']),
n('it_0554',554,'naso','nose','masculine','nasi',['Ho il naso chiuso.'],['a1']),
n('it_0555',555,'orecchio','ear','masculine','orecchi',['Mi fa male un orecchio.'],['a1'],true),
n('it_0556',556,'spalla','shoulder','feminine','spalle',['Ho dolore alla spalla.'],['a1']),
n('it_0557',557,'ginocchio','knee','masculine','ginocchi',['Mi fa male il ginocchio.'],['a1'],true),
n('it_0558',558,'dito','finger','masculine','dita',['Ho tagliato il dito.'],['a1'],true),
n('it_0559',559,'unghia','nail (finger)','feminine','unghie',['Si taglia le unghie.'],['a2']),
n('it_0560',560,'pelle','skin','feminine',null,['Ha la pelle sensibile.'],['a2']),
n('it_0561',561,'sangue','blood','masculine',null,['Il sangue è rosso.'],['a2']),
n('it_0562',562,'osso','bone','masculine','ossa',['Mi sono rotto un osso.'],['a2'],true),
n('it_0563',563,'muscolo','muscle','masculine','muscoli',['Ho i muscoli tesi.'],['a2']),
n('it_0564',564,'polmone','lung','masculine','polmoni',['I polmoni sono vitali.'],['a2']),
n('it_0565',565,'rene','kidney','masculine','reni',['Ho problemi ai reni.'],['a2']),
n('it_0566',566,'fegato','liver','masculine','fegati',['Il fegato elabora l\'alcol.'],['a2']),
n('it_0567',567,'cuore','heart — see 121','masculine','cuori',['—'],['a1']),
n('it_0568',568,'cervello','brain','masculine','cervelli',['Il cervello è complesso.'],['a2']),
n('it_0569',569,'nervo','nerve','masculine','nervi',['Stai sui nervi!'],['a2']),
n('it_0570',570,'esame','exam','masculine','esami',['Ho superato l\'esame.'],['a1']),
n('it_0571',571,'corso','course/class','masculine','corsi',['Seguo un corso di italiano.'],['a1']),
n('it_0572',572,'voto','grade/vote','masculine','voti',['Ho preso un bel voto.'],['a1']),
n('it_0573',573,'materia','subject (school)','feminine','materie',['Qual è la tua materia preferita?'],['a1']),
n('it_0574',574,'università','university','feminine','università',['Studio all\'università.'],['a1']),
n('it_0575',575,'laurea','degree','feminine','lauree',['Ho la laurea in italiano.'],['a2']),
n('it_0576',576,'diploma','diploma','masculine','diplomi',['Ho preso il diploma.'],['a2']),
n('it_0577',577,'ricerca','research/search','feminine','ricerche',['Faccio ricerca.'],['a2']),
n('it_0578',578,'esperienza','experience','feminine','esperienze',['Ho molta esperienza.'],['a2']),
n('it_0579',579,'abilità','skill/ability','feminine','abilità',['Ha molte abilità.'],['a2']),
n('it_0580',580,'conoscenza','knowledge','feminine','conoscenze',['Ha una buona conoscenza dell\'italiano.'],['a2']),
n('it_0581',581,'informazione','information','feminine','informazioni',['Ho bisogno di informazioni.'],['a1']),
n('it_0582',582,'notizia','news — see 316','feminine','notizie',['—'],['a2']),
n('it_0583',583,'programma','program/show','masculine','programmi',['Qual è il programma?'],['a2']),
n('it_0584',584,'progetto','project/plan','masculine','progetti',['Lavoro a un progetto.'],['a2']),
n('it_0585',585,'obiettivo','goal/objective','masculine','obiettivi',['Qual è il tuo obiettivo?'],['a2']),
n('it_0586',586,'scopo','purpose/aim','masculine','scopi',['A che scopo?'],['a2']),
n('it_0587',587,'motivo','reason/motive','masculine','motivi',['Per quale motivo?'],['a1']),
n('it_0588',588,'vantaggio','advantage','masculine','vantaggi',['Qual è il vantaggio?'],['a2']),
n('it_0589',589,'svantaggio','disadvantage','masculine','svantaggi',['Qual è lo svantaggio?'],['a2']),
n('it_0590',590,'regola','rule','feminine','regole',['Segui le regole.'],['a1']),
n('it_0591',591,'legge','law','feminine','leggi',['La legge è uguale per tutti.'],['a2']),
n('it_0592',592,'diritto','right/law','masculine','diritti',['Ho diritto di sapere.'],['a2']),
n('it_0593',593,'dovere','duty/must','masculine','doveri',['È un mio dovere.'],['a2']),
n('it_0594',594,'libertà','freedom','feminine','libertà',['Viva la libertà!'],['a2']),
n('it_0595',595,'giustizia','justice','feminine',null,['Voglio giustizia.'],['a2']),
n('it_0596',596,'potere','power','masculine','poteri',['Il potere corrompe.'],['a2']),
n('it_0597',597,'forza','strength/force','feminine','forze',['Ho bisogno di forze.'],['a1']),
n('it_0598',598,'energia','energy','feminine','energie',['Ho poca energia.'],['a2']),
n('it_0599',599,'salario','salary','masculine','salari',['Il mio salario è basso.'],['a2']),
n('it_0600',600,'stipendio','salary/wage','masculine','stipendi',['Quando prendo lo stipendio?'],['a2']),
n('it_0601',601,'azienda','company/firm','feminine','aziende',['Lavoro in un\'azienda.'],['a2']),
n('it_0602',602,'impresa','enterprise/company','feminine','imprese',['È una grande impresa.'],['a2']),
n('it_0603',603,'prodotto','product','masculine','prodotti',['Questo prodotto è buono.'],['a2']),
n('it_0604',604,'servizio','service','masculine','servizi',['Il servizio è ottimo.'],['a2']),
n('it_0605',605,'cliente','customer/client','masculine','clienti',['Il cliente ha sempre ragione.'],['a2']),
n('it_0606',606,'contratto','contract','masculine','contratti',['Ho firmato il contratto.'],['a2']),
n('it_0607',607,'accordo','agreement/deal','masculine','accordi',['Siamo d\'accordo.'],['a2']),
n('it_0608',608,'affitto','rent','masculine','affitti',['Pago l\'affitto.'],['a2']),
n('it_0609',609,'prenotazione','reservation/booking','feminine','prenotazioni',['Ho una prenotazione.'],['a2']),
n('it_0610',610,'ricetta','recipe/prescription','feminine','ricette',['Seguo la ricetta.'],['a2']),

// ── ADJECTIVES 611-660 ──────────────────────────────────────────────────────
adj('it_0611',611,'attuale','current/present','attuali',['La situazione attuale è difficile.'],['a2']),
adj('it_0612',612,'futuro','future','futuri',['I progetti futuri sono belli.'],['a2']),
adj('it_0613',613,'passato','past','passati',['Negli anni passati era diverso.'],['a2']),
adj('it_0614',614,'presente','present','presenti',['Sono tutti presenti.'],['a2']),
adj('it_0615',615,'recente','recent','recenti',['È una notizia recente.'],['a2']),
adj('it_0616',616,'tradizionale','traditional','tradizionali',['È un piatto tradizionale.'],['a2']),
adj('it_0617',617,'originale','original','originali',['È un\'idea originale.'],['a2']),
adj('it_0618',618,'unico','unique','unici',['Sei unico!'],['a2']),
adj('it_0619',619,'comune','common/shared','comuni',['È un problema comune.'],['a2']),
adj('it_0620',620,'raro','rare','rari',['È un caso raro.'],['a2']),
adj('it_0621',621,'frequente','frequent','frequenti',['I treni sono frequenti.'],['a2']),
adj('it_0622',622,'completo','complete','completi',['Il lavoro è completo.'],['a2']),
adj('it_0623',623,'vuoto','empty — see 368','vuoti',['—'],['a1']),
adj('it_0624',624,'pieno','full — see 367','pieni',['—'],['a1']),
adj('it_0625',625,'corretto','correct','corretti',['La risposta è corretta.'],['a1']),
adj('it_0626',626,'scorretto','incorrect','scorretti',['La risposta è scorretta.'],['a2']),
adj('it_0627',627,'preciso','precise/exact','precisi',['Sii preciso.'],['a2']),
adj('it_0628',628,'esatto','exact/correct','esatti',['Esatto!'],['a1']),
adj('it_0629',629,'vago','vague','vaghi',['È una risposta vaga.'],['b1']),
adj('it_0630',630,'chiaro','clear','chiari',['È chiaro?'],['a1']),
adj('it_0631',631,'oscuro','dark/obscure','oscuri',['Un momento oscuro.'],['b1']),
adj('it_0632',632,'profondo','deep/profound','profondi',['Il lago è profondo.'],['a2']),
adj('it_0633',633,'superficiale','superficial/shallow','superficiali',['È una persona superficiale.'],['b1']),
adj('it_0634',634,'ampio','wide/broad','ampi',['Un ampio spazio.'],['a2']),
adj('it_0635',635,'stretto','narrow/tight','stretti',['La strada è stretta.'],['a2']),
adj('it_0636',636,'rotondo','round','rotondi',['Una tavola rotonda.'],['a2']),
adj('it_0637',637,'quadrato','square','quadrati',['Un tavolo quadrato.'],['a2']),
adj('it_0638',638,'piatto','flat','piatti',['Il terreno è piatto.'],['a2']),
adj('it_0639',639,'curvo','curved','curvi',['Una linea curva.'],['b1']),
adj('it_0640',640,'dritto','straight','dritti',['Va dritto.'],['a1']),

// ── ADVERBS, PREPOSITIONS, CONJUNCTIONS 641-700 ────────────────────────────
adv('it_0641',641,'già','already — see 23','già',['—'],['a1']),
adv('it_0642',642,'ancora','still/yet/again — see 34','ancora',['—'],['a1']),
adv('it_0643',643,'mai','never/ever — see 51','mai',['—'],['a1']),
adv('it_0644',644,'sempre','always — see 37','sempre',['—'],['a1']),
adv('it_0645',645,'circa','approximately',['Ci vogliono circa due ore.'],['a2']),
adv('it_0646',646,'almeno','at least',['Almeno un\'ora.'],['a1']),
adv('it_0647',647,'massimo','maximum/at most',['Al massimo un\'ora.'],['a2']),
adv('it_0648',648,'appena','just/as soon as',['Sono appena arrivato.'],['a2']),
adv('it_0649',649,'inoltre','furthermore/also',['Inoltre, devo dirti una cosa.'],['b1']),
adv('it_0650',650,'tuttavia','however/nevertheless',['Tuttavia, non sono d\'accordo.'],['b1']),
adv('it_0651',651,'pertanto','therefore',['Pertanto, ho deciso di partire.'],['b1']),
adv('it_0652',652,'quindi','so/therefore — see 73','quindi',['—'],['a1']),
adv('it_0653',653,'dunque','therefore/so',['Dunque, cosa facciamo?'],['b1']),
adv('it_0654',654,'altrimenti','otherwise',['Sbrigati, altrimenti perdiamo il treno.'],['a2']),
adv('it_0655',655,'comunque','anyway — see 203','comunque',['—'],['a2']),
adv('it_0656',656,'forse','perhaps — see 197','forse',['—'],['a1']),
adv('it_0657',657,'purtroppo','unfortunately — see 215','purtroppo',['—'],['a2']),
adv('it_0658',658,'fortunatamente','fortunately',['Fortunatamente non si è fatto male.'],['a2']),
adv('it_0659',659,'recentemente','recently — see 397','recentemente',['—'],['a2']),
adv('it_0660',660,'attualmente','currently',['Attualmente lavoro a Milano.'],['a2']),
adv('it_0661',661,'storicamente','historically',['Storicamente è importante.'],['b1']),
adv('it_0662',662,'politicamente','politically',['È politicamente corretto.'],['b1']),
adv('it_0663',663,'socialmente','socially',['È socialmente accettato.'],['b1']),
adv('it_0664',664,'economicamente','economically',['È economicamente vantaggioso.'],['b1']),
adv('it_0665',665,'culturalmente','culturally',['È culturalmente ricco.'],['b1']),
prep('it_0666',666,'tramite','through/via',['Ti contatto tramite email.'],['b1']),
prep('it_0667',667,'mediante','by means of',['Mediante il telefono.'],['b1']),
prep('it_0668',668,'nonostante','despite/notwithstanding',['Nonostante la pioggia, è venuto.'],['b1']),
prep('it_0669',669,'grazie a','thanks to',['Grazie al tuo aiuto ce l\'ho fatta.'],['a2']),
prep('it_0670',670,'a causa di','because of',['A causa della pioggia non esco.'],['a2']),
conj('it_0671',671,'sebbene','although (subj)',['Sebbene piova, esco.'],['b1']),
conj('it_0672',672,'benché','although (subj)',['Benché sia stanco, lavoro.'],['b1']),
conj('it_0673',673,'affinché','so that (subj)',['Ti dico questo affinché tu capisca.'],['b1']),
conj('it_0674',674,'purché','provided that',['Vengo purché tu venga.'],['b1']),
conj('it_0675',675,'a meno che','unless',['Vengo, a meno che non piova.'],['b1']),
conj('it_0676',676,'nel caso in cui','in case',['Nel caso in cui non venga, chiama.'],['b1']),
conj('it_0677',677,'nel momento in cui','at the moment when',['Nel momento in cui arriva, chiamami.'],['b1']),
conj('it_0678',678,'non appena','as soon as',['Non appena arrivi, chiamami.'],['a2']),
conj('it_0679',679,'poiché','since/because',['Poiché sei stanco, riposa.'],['b1']),
conj('it_0680',680,'giacché','since (formal)',['Giacché sei qui, aiutami.'],['b1']),

// ── MORE NOUNS 681-750 ──────────────────────────────────────────────────────
n('it_0681',681,'sogno','dream','masculine','sogni',['Ho fatto un bel sogno.'],['a1']),
n('it_0682',682,'pensiero','thought','masculine','pensieri',['Un pensiero gentile.'],['a2']),
n('it_0683',683,'ricordo','memory/souvenir','masculine','ricordi',['Ho bei ricordi.'],['a1']),
n('it_0684',684,'futuro','future','masculine',null,['Il futuro è incerto.'],['a2']),
n('it_0685',685,'passato','past','masculine',null,['Il passato è passato.'],['a2']),
n('it_0686',686,'presente','present (time)','masculine',null,['Vivi nel presente.'],['a2']),
n('it_0687',687,'scelta','choice','feminine','scelte',['È una buona scelta.'],['a2']),
n('it_0688',688,'opportunità','opportunity','feminine','opportunità',['È una grande opportunità.'],['a2']),
n('it_0689',689,'pericolo','danger','masculine','pericoli',['È in pericolo.'],['a2']),
n('it_0690',690,'rischio','risk','masculine','rischi',['È un rischio.'],['a2']),
n('it_0691',691,'successo','success','masculine','successi',['Ha avuto successo.'],['a2']),
n('it_0692',692,'fallimento','failure','masculine','fallimenti',['È stato un fallimento.'],['a2']),
n('it_0693',693,'vittoria','victory','feminine','vittorie',['Abbiamo vinto. È una vittoria!'],['a2']),
n('it_0694',694,'sconfitta','defeat','feminine','sconfitte',['È una sconfitta amara.'],['a2']),
n('it_0695',695,'cambiamento','change','masculine','cambiamenti',['I cambiamenti sono necessari.'],['a2']),
n('it_0696',696,'miglioramento','improvement','masculine','miglioramenti',['C\'è un miglioramento.'],['a2']),
n('it_0697',697,'peggioramento','worsening','masculine','peggioramenti',['C\'è un peggioramento.'],['a2']),
n('it_0698',698,'soluzione','solution','feminine','soluzioni',['Ho trovato la soluzione.'],['a2']),
n('it_0699',699,'alternativa','alternative','feminine','alternative',['Non c\'è alternativa.'],['a2']),
n('it_0700',700,'possibilità','possibility','feminine','possibilità',['C\'è una possibilità.'],['a2']),
n('it_0701',701,'probabilità','probability','feminine','probabilità',['La probabilità è alta.'],['b1']),
n('it_0702',702,'capacità','capacity/ability','feminine','capacità',['Ha grande capacità.'],['a2']),
n('it_0703',703,'qualità','quality','feminine','qualità',['È di alta qualità.'],['a2']),
n('it_0704',704,'quantità','quantity','feminine','quantità',['In grande quantità.'],['a2']),
n('it_0705',705,'velocità','speed','feminine','velocità',['A grande velocità.'],['a2']),
n('it_0706',706,'distanza','distance','feminine','distanze',['A grande distanza.'],['a2']),
n('it_0707',707,'lunghezza','length','feminine','lunghezze',['La lunghezza è di tre metri.'],['a2']),
n('it_0708',708,'altezza','height','feminine','altezze',['L\'altezza è di due metri.'],['a2']),
n('it_0709',709,'larghezza','width','feminine','larghezze',['La larghezza è di un metro.'],['a2']),
n('it_0710',710,'peso','weight','masculine','pesi',['Qual è il tuo peso?'],['a2']),
n('it_0711',711,'misura','measure/size','feminine','misure',['Qual è la tua misura?'],['a2']),
n('it_0712',712,'colore','color — see 319','masculine','colori',['—'],['a1']),
n('it_0713',713,'rosso','red (noun/adj)','masculine','rossi',['Il rosso mi piace.'],['a1']),
n('it_0714',714,'blu','blue','masculine','blu',['Il cielo è blu.'],['a1']),
n('it_0715',715,'verde','green','masculine','verdi',['L\'erba è verde.'],['a1']),
n('it_0716',716,'giallo','yellow','masculine','gialli',['Il limone è giallo.'],['a1']),
n('it_0717',717,'arancione','orange (color)','masculine','arancioni',['L\'arancia è arancione.'],['a1']),
n('it_0718',718,'viola','purple','masculine','viola',['Il viola è bello.'],['a1']),
n('it_0719',719,'rosa','pink','masculine','rosa',['Mi piace il rosa.'],['a1']),
n('it_0720',720,'bianco','white','masculine','bianchi',['La neve è bianca.'],['a1']),
n('it_0721',721,'nero','black','masculine','neri',['Il cielo è nero di notte.'],['a1']),
n('it_0722',722,'grigio','grey','masculine','grigi',['Le nuvole sono grigie.'],['a1']),
n('it_0723',723,'marrone','brown','masculine','marroni',['Il cioccolato è marrone.'],['a1']),
n('it_0724',724,'beige','beige','masculine','beige',['Il cappotto è beige.'],['a2']),
n('it_0725',725,'cappotto','coat','masculine','cappotti',['Ho comprato un cappotto.'],['a1']),
n('it_0726',726,'giacca','jacket','feminine','giacche',['Indossa una giacca.'],['a1']),
n('it_0727',727,'vestito','dress/suit','masculine','vestiti',['Ha un bel vestito.'],['a1']),
n('it_0728',728,'pantaloni','trousers','masculine',null,['I pantaloni sono neri.'],['a1']),
n('it_0729',729,'gonna','skirt','feminine','gonne',['Ha una gonna rossa.'],['a1']),
n('it_0730',730,'maglietta','t-shirt','feminine','magliette',['Indossa una maglietta bianca.'],['a1']),
n('it_0731',731,'camicia','shirt','feminine','camicie',['Ha una camicia blu.'],['a1']),
n('it_0732',732,'maglione','sweater','masculine','maglioni',['Porto un maglione d\'inverno.'],['a1']),
n('it_0733',733,'scarpa','shoe','feminine','scarpe',['Ho comprato delle scarpe.'],['a1']),
n('it_0734',734,'calza','sock/stocking','feminine','calze',['Calze colorate.'],['a1']),
n('it_0735',735,'cappello','hat','masculine','cappelli',['Porto il cappello.'],['a1']),
n('it_0736',736,'sciarpa','scarf','feminine','sciarpe',['Porto la sciarpa d\'inverno.'],['a1']),
n('it_0737',737,'guanto','glove','masculine','guanti',['Ho perso un guanto.'],['a1']),
n('it_0738',738,'borsa','bag/purse','feminine','borse',['Ho la borsa.'],['a1']),
n('it_0739',739,'zaino','backpack','masculine','zaini',['Porto lo zaino a scuola.'],['a1']),
n('it_0740',740,'cintura','belt','feminine','cinture',['La cintura è stretta.'],['a1']),
n('it_0741',741,'portafoglio','wallet','masculine','portafogli',['Ho perso il portafoglio.'],['a1']),
n('it_0742',742,'occhiali','glasses','masculine',null,['Porto gli occhiali.'],['a1']),
n('it_0743',743,'orologio','watch/clock','masculine','orologi',['Guarda l\'orologio.'],['a1']),
n('it_0744',744,'anello','ring','masculine','anelli',['Porta un anello d\'oro.'],['a1']),
n('it_0745',745,'collana','necklace','feminine','collane',['Ha una collana d\'argento.'],['a2']),
n('it_0746',746,'orecchino','earring','masculine','orecchini',['Ha gli orecchini d\'oro.'],['a2']),
n('it_0747',747,'profumo','perfume/fragrance','masculine','profumi',['Che bel profumo!'],['a2']),
n('it_0748',748,'specchio','mirror','masculine','specchi',['Si guarda allo specchio.'],['a1']),
n('it_0749',749,'sapone','soap','masculine','saponi',['Lava con il sapone.'],['a1']),
n('it_0750',750,'asciugamano','towel','masculine','asciugamani',['Prendo un asciugamano.'],['a1']),
];

// Filter out duplicates (marked with '—')
const clean=entries.filter(e=>!e.examples[0].includes('—') || e.examples[0]==='—' ? !e.examples[0].includes('—') : true);
const final=entries.filter(e=>!e.examples[0].startsWith('—'));

console.log(`Generated ${final.length} entries, ranks ${final[0].rank}-${final[final.length-1].rank}`);
const ranks=final.map(e=>e.rank);
const dups=ranks.filter((r,i)=>ranks.indexOf(r)!==i);
if(dups.length) console.warn('Duplicate ranks:',dups);

fs.writeFileSync(path.join(__dirname,'../src/data/words-003.json'),JSON.stringify(final,null,2));
console.log('words-003.json written.');
