const fs=require('fs'),path=require('path');
// words-006.json: ranks 1251-1500, B1 level

function makeVerb(id,rank,ita,eng,grp,ppAux,pp,pres,impf,fut,cond,cong,ex,tags){
  const aux=ppAux==='avere';
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'verb',gender:null,plural:null,
    conjugationGroup:grp,irregular:true,
    conjugations:{presente:pres,
      passatoProssimo:{auxiliary:ppAux,pastParticiple:pp,
        io:(aux?'ho':'sono')+' '+pp,tu:(aux?'hai':'sei')+' '+pp,
        lui:(aux?'ha':'è')+' '+pp,noi:(aux?'abbiamo':'siamo')+' '+pp,
        voi:(aux?'avete':'siete')+' '+pp,loro:(aux?'hanno':'sono')+' '+pp},
      imperfetto:impf,futuroSemplice:fut,condizionale:cond,congiuntivoPresente:cong},
    irregularForms:null,examples:ex,tags,needsReview:false};
}
function rV(id,rank,ita,eng,grp,ppAux,pp,ex,tags){
  // regular verb — auto-conjugate
  const s=ita.replace(/(are|ere|ire)$/,'');
  let pres,impf,fut,cond,cong;
  if(grp==='are'){
    pres={io:s+'o',tu:s+'i',lui:s+'a',noi:s+'iamo',voi:s+'ate',loro:s+'ano'};
    impf={io:s+'avo',tu:s+'avi',lui:s+'ava',noi:s+'avamo',voi:s+'avate',loro:s+'avano'};
    fut={io:s+'erò',tu:s+'erai',lui:s+'erà',noi:s+'eremo',voi:s+'erete',loro:s+'eranno'};
    cond={io:s+'erei',tu:s+'eresti',lui:s+'erebbe',noi:s+'eremmo',voi:s+'ereste',loro:s+'erebbero'};
    cong={io:s+'i',tu:s+'i',lui:s+'i',noi:s+'iamo',voi:s+'iate',loro:s+'ino'};
  }else if(grp==='ere'){
    pres={io:s+'o',tu:s+'i',lui:s+'e',noi:s+'iamo',voi:s+'ete',loro:s+'ono'};
    impf={io:s+'evo',tu:s+'evi',lui:s+'eva',noi:s+'evamo',voi:s+'evate',loro:s+'evano'};
    fut={io:s+'erò',tu:s+'erai',lui:s+'erà',noi:s+'eremo',voi:s+'erete',loro:s+'eranno'};
    cond={io:s+'erei',tu:s+'eresti',lui:s+'erebbe',noi:s+'eremmo',voi:s+'ereste',loro:s+'erebbero'};
    cong={io:s+'a',tu:s+'a',lui:s+'a',noi:s+'iamo',voi:s+'iate',loro:s+'ano'};
  }else{
    pres={io:s+'o',tu:s+'i',lui:s+'e',noi:s+'iamo',voi:s+'ite',loro:s+'ono'};
    impf={io:s+'ivo',tu:s+'ivi',lui:s+'iva',noi:s+'ivamo',voi:s+'ivate',loro:s+'ivano'};
    fut={io:s+'irò',tu:s+'irai',lui:s+'irà',noi:s+'iremo',voi:s+'irete',loro:s+'iranno'};
    cond={io:s+'irei',tu:s+'iresti',lui:s+'irebbe',noi:s+'iremmo',voi:s+'ireste',loro:s+'irebbero'};
    cong={io:s+'a',tu:s+'a',lui:s+'a',noi:s+'iamo',voi:s+'iate',loro:s+'ano'};
  }
  const aux=ppAux==='avere';
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'verb',gender:null,plural:null,
    conjugationGroup:grp,irregular:false,
    conjugations:{presente:pres,passatoProssimo:{auxiliary:ppAux,pastParticiple:pp,
      io:(aux?'ho':'sono')+' '+pp,tu:(aux?'hai':'sei')+' '+pp,
      lui:(aux?'ha':'è')+' '+pp,noi:(aux?'abbiamo':'siamo')+' '+pp,
      voi:(aux?'avete':'siete')+' '+pp,loro:(aux?'hanno':'sono')+' '+pp},
      imperfetto:impf,futuroSemplice:fut,condizionale:cond,congiuntivoPresente:cong},
    irregularForms:null,examples:ex,tags,needsReview:false};
}
function n(id,rank,ita,eng,gender,plural,ex,tags){
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'noun',gender,plural,
    conjugationGroup:null,irregular:false,conjugations:null,irregularForms:null,examples:ex,tags,needsReview:false};
}
function adj(id,rank,ita,eng,plural,ex,tags){
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'adjective',gender:'masculine',plural,
    conjugationGroup:null,irregular:false,conjugations:null,irregularForms:null,examples:ex,tags,needsReview:false};
}
function adv(id,rank,ita,eng,ex,tags){
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'adverb',gender:null,plural:null,
    conjugationGroup:null,irregular:false,conjugations:null,irregularForms:null,examples:ex,tags,needsReview:false};
}

const e=[
// VERBS 1251-1300
rV('it_1251',1251,'adattare','to adapt','are','avere','adattato',['Adatta il piano.'],['b1']),
rV('it_1252',1252,'adattarsi','to adapt (refl.)','are','essere','adattato',['Mi adatto alla situazione.'],['b1']),
rV('it_1253',1253,'modificare','to modify','are','avere','modificato',['Modifica il documento.'],['b1']),
rV('it_1254',1254,'aggiornare','to update','are','avere','aggiornato',['Aggiorna il software.'],['a2']),
rV('it_1255',1255,'migliorare','to improve — see 774','are','avere','migliorato',['—'],['a2']),
rV('it_1256',1256,'ottimizzare','to optimize','are','avere','ottimizzato',['Ottimizza i tempi.'],['b1']),
rV('it_1257',1257,'semplificare','to simplify','are','avere','semplificato',['Semplifica il processo.'],['b1']),
rV('it_1258',1258,'complicare','to complicate','are','avere','complicato',['Non complicare le cose.'],['b1']),
rV('it_1259',1259,'facilitare','to facilitate','are','avere','facilitato',['Ciò facilita il lavoro.'],['b1']),
rV('it_1260',1260,'bloccare','to block/jam','are','avere','bloccato',['Il traffico blocca la strada.'],['a2']),
rV('it_1261',1261,'sbloccare','to unblock','are','avere','sbloccato',['Sblocca il telefono.'],['a2']),
rV('it_1262',1262,'attivare','to activate','are','avere','attivato',['Attiva il servizio.'],['a2']),
rV('it_1263',1263,'disattivare','to deactivate','are','avere','disattivato',['Disattiva le notifiche.'],['a2']),
rV('it_1264',1264,'installare','to install','are','avere','installato',['Installa il programma.'],['a2']),
rV('it_1265',1265,'collegare','to connect/link','are','avere','collegato',['Collega il cavo.'],['a2']),
rV('it_1266',1266,'scaricare','to download/unload','are','avere','scaricato',['Scarica l\'app.'],['a2']),
rV('it_1267',1267,'caricare','to upload/load','are','avere','caricato',['Carica la foto.'],['a2']),
rV('it_1268',1268,'condividere','to share — see 1046','ere','avere','condiviso',['—'],['a2']),
rV('it_1269',1269,'salvare','to save','are','avere','salvato',['Salva il documento.'],['a2']),
rV('it_1270',1270,'eliminare','to delete/eliminate','are','avere','eliminato',['Elimina il file.'],['a2']),
rV('it_1271',1271,'recuperare','to recover/retrieve','are','avere','recuperato',['Recupera il file cancellato.'],['a2']),
rV('it_1272',1272,'archiviare','to archive','are','avere','archiviato',['Archivia i vecchi documenti.'],['b1']),
rV('it_1273',1273,'registrare','to register/record','are','avere','registrato',['Registra la riunione.'],['a2']),
rV('it_1274',1274,'trasmettere','to transmit/broadcast','ere','avere','trasmesso',['Trasmettono il discorso.'],['b1']),
rV('it_1275',1275,'ricevere','to receive — see 522','ere','avere','ricevuto',['—'],['a2']),
rV('it_1276',1276,'inviare','to send','are','avere','inviato',['Invia il documento.'],['a2']),
rV('it_1277',1277,'spedire','to send/mail','ire','avere','spedito',['Spedisco il pacco.'],['a2']),
rV('it_1278',1278,'consegnare','to deliver','are','avere','consegnato',['Consegna il pacco.'],['a2']),
rV('it_1279',1279,'ritirare','to withdraw/collect','are','avere','ritirato',['Ritiro il pacco.'],['a2']),
rV('it_1280',1280,'ordinare','to order/organize','are','avere','ordinato',['Ordino la pizza.'],['a2']),
rV('it_1281',1281,'prenotare','to book/reserve','are','avere','prenotato',['Prenoto un tavolo.'],['a2']),
rV('it_1282',1282,'cancellare','to cancel/erase','are','avere','cancellato',['Cancello la prenotazione.'],['a2']),
rV('it_1283',1283,'confermare','to confirm — see 1012','are','avere','confermato',['—'],['a2']),
rV('it_1284',1284,'rifiutare','to refuse — see 524','are','avere','rifiutato',['—'],['a2']),
rV('it_1285',1285,'avvisare','to notify/warn','are','avere','avvisato',['Avvisami se arrivi tardi.'],['a2']),
rV('it_1286',1286,'informare','to inform','are','avere','informato',['Informami del risultato.'],['a2']),
rV('it_1287',1287,'avvertire','to warn','ire','avere','avvertito',['Ti avverto: è pericoloso.'],['b1']),
rV('it_1288',1288,'segnalare','to signal/report','are','avere','segnalato',['Segnala il problema.'],['b1']),
rV('it_1289',1289,'denunciare','to report (to police)','are','avere','denunciato',['Ha denunciato il furto.'],['b1']),
rV('it_1290',1290,'richiedere','to request/require','ere','avere','richiesto',['Richiedo un\'informazione.'],['a2']),
rV('it_1291',1291,'presentare','to present/introduce','are','avere','presentato',['Ti presento il mio amico.'],['a2']),
rV('it_1292',1292,'introdurre','to introduce','ere','avere','introdotto',['Ha introdotto una nuova legge.'],['b1']),
rV('it_1293',1293,'avanzare','to advance/put forward','are','essere','avanzato',['Avanziamo verso la meta.'],['b1']),
rV('it_1294',1294,'procedere','to proceed','ere','essere','proceduto',['Procediamo con il piano.'],['b1']),
rV('it_1295',1295,'proseguire','to continue/proceed','ire','avere','proseguito',['Prosegui dritto.'],['b1']),
rV('it_1296',1296,'completare','to complete — see 1037','are','avere','completato',['—'],['a2']),
rV('it_1297',1297,'terminare','to end/terminate','are','avere','terminato',['Il corso termina domani.'],['b1']),
rV('it_1298',1298,'concludere','to conclude','ere','avere','concluso',['Concludiamo la riunione.'],['b1']),
rV('it_1299',1299,'riassumere','to summarize','ere','avere','riassunto',['Riassumi i punti principali.'],['b1']),
rV('it_1300',1300,'sintetizzare','to synthesize','are','avere','sintetizzato',['Sintetizza il testo.'],['b1']),

// NOUNS 1301-1420
n('it_1301',1301,'materia prima','raw material','feminine','materie prime',['Importiamo materie prime.'],['b1']),
n('it_1302',1302,'risorsa','resource','feminine','risorse',['Le risorse disponibili.'],['b1']),
n('it_1303',1303,'carburante','fuel','masculine','carburanti',['Il prezzo del carburante.'],['b1']),
n('it_1304',1304,'petrolio','petroleum/oil','masculine',null,['Il prezzo del petrolio.'],['b1']),
n('it_1305',1305,'gas','gas','masculine','gas',['Il gas naturale.'],['a2']),
n('it_1306',1306,'elettricità','electricity','feminine',null,['La bolletta dell\'elettricità.'],['a2']),
n('it_1307',1307,'bolletta','bill (utility)','feminine','bollette',['Pago la bolletta.'],['a2']),
n('it_1308',1308,'tassa','tax','feminine','tasse',['Pago le tasse.'],['a2']),
n('it_1309',1309,'imposta','tax/duty','feminine','imposte',['Le imposte sul reddito.'],['b1']),
n('it_1310',1310,'reddito','income','masculine','redditi',['Il reddito annuo.'],['b1']),
n('it_1311',1311,'spesa','expense — see 488','feminine','spese',['Le spese mensili.'],['a2']),
n('it_1312',1312,'budget','budget','masculine','budget',['Rispetto il budget.'],['a2']),
n('it_1313',1313,'bilancio','balance/budget','masculine','bilanci',['Il bilancio statale.'],['b1']),
n('it_1314',1314,'profitto','profit','masculine','profitti',['Il margine di profitto.'],['b1']),
n('it_1315',1315,'perdita','loss','feminine','perdite',['Una perdita economica.'],['b1']),
n('it_1316',1316,'investimento','investment','masculine','investimenti',['Un buon investimento.'],['b1']),
n('it_1317',1317,'finanziamento','financing','masculine','finanziamenti',['Cerco finanziamenti.'],['b1']),
n('it_1318',1318,'prestito','loan','masculine','prestiti',['Chiedo un prestito in banca.'],['b1']),
n('it_1319',1319,'mutuo','mortgage','masculine','mutui',['Ho un mutuo sulla casa.'],['b1']),
n('it_1320',1320,'interesse','interest','masculine','interessi',['Il tasso di interesse.'],['b1']),
n('it_1321',1321,'inflazione','inflation','feminine',null,['L\'inflazione è alta.'],['b1']),
n('it_1322',1322,'deflazione','deflation','feminine',null,['Il periodo di deflazione.'],['b1']),
n('it_1323',1323,'mercato','market — see 294','masculine','mercati',['Il mercato azionario.'],['a2']),
n('it_1324',1324,'borsa','stock exchange/bag','feminine','borse',['La borsa di Milano.'],['b1']),
n('it_1325',1325,'azione','stock share/action','feminine','azioni',['Compro azioni.'],['b1']),
n('it_1326',1326,'obbligazione','bond/obligation','feminine','obbligazioni',['Emette obbligazioni.'],['b1']),
n('it_1327',1327,'valuta','currency','feminine','valute',['La valuta europea.'],['b1']),
n('it_1328',1328,'euro','euro','masculine','euro',['Costa dieci euro.'],['a1']),
n('it_1329',1329,'dollaro','dollar','masculine','dollari',['Il tasso dollaro/euro.'],['a2']),
n('it_1330',1330,'cambio','exchange rate/change','masculine','cambi',['Il tasso di cambio.'],['b1']),
n('it_1331',1331,'commercio','commerce/trade','masculine',null,['Il commercio internazionale.'],['b1']),
n('it_1332',1332,'importazione','import','feminine','importazioni',['Le importazioni crescono.'],['b1']),
n('it_1333',1333,'esportazione','export','feminine','esportazioni',['Le esportazioni italiane.'],['b1']),
n('it_1334',1334,'dogana','customs','feminine','dogane',['Passo la dogana.'],['b1']),
n('it_1335',1335,'trasporto','transport','masculine','trasporti',['Il sistema di trasporto.'],['a2']),
n('it_1336',1336,'logistica','logistics','feminine',null,['La logistica è complessa.'],['b1']),
n('it_1337',1337,'spedizione','shipment','feminine','spedizioni',['La spedizione è in ritardo.'],['b1']),
n('it_1338',1338,'magazzino','warehouse','masculine','magazzini',['Il prodotto è in magazzino.'],['b1']),
n('it_1339',1339,'inventario','inventory','masculine','inventari',['Faccio l\'inventario.'],['b1']),
n('it_1340',1340,'catena di fornitura','supply chain','feminine',null,['La catena di fornitura.'],['b1']),
n('it_1341',1341,'settore','sector','masculine','settori',['Il settore pubblico.'],['b1']),
n('it_1342',1342,'industria','industry','feminine','industrie',['L\'industria automobilistica.'],['a2']),
n('it_1343',1343,'manifattura','manufacturing','feminine',null,['La manifattura italiana.'],['b1']),
n('it_1344',1344,'agricoltura','agriculture','feminine',null,['L\'agricoltura biologica.'],['a2']),
n('it_1345',1345,'turismo','tourism','masculine',null,['Il turismo è importante.'],['a2']),
n('it_1346',1346,'ospitalità','hospitality','feminine',null,['Il settore dell\'ospitalità.'],['b1']),
n('it_1347',1347,'alloggio','accommodation','masculine','alloggi',['Cerco alloggio.'],['a2']),
n('it_1348',1348,'pensione','guesthouse/pension','feminine','pensioni',['Dormo in una pensione.'],['a2']),
n('it_1349',1349,'ostello','hostel','masculine','ostelli',['Dormo in un ostello.'],['a2']),
n('it_1350',1350,'campeggio','campsite','masculine','campeggi',['Vado in campeggio.'],['a2']),
n('it_1351',1351,'tenda','tent','feminine','tende',['Montiamo la tenda.'],['a2']),
n('it_1352',1352,'sacco a pelo','sleeping bag','masculine',null,['Ho il sacco a pelo.'],['a2']),
n('it_1353',1353,'zaino','backpack — see 739','masculine','zaini',['—'],['a1']),
n('it_1354',1354,'escursione','excursion/hike','feminine','escursioni',['Faccio un\'escursione.'],['a2']),
n('it_1355',1355,'sentiero','path/trail','masculine','sentieri',['Seguo il sentiero.'],['a2']),
n('it_1356',1356,'percorso','route/path','masculine','percorsi',['Qual è il percorso?'],['a2']),
n('it_1357',1357,'itinerario','itinerary','masculine','itinerari',['Pianifichiamo l\'itinerario.'],['b1']),
n('it_1358',1358,'meta','destination/goal','feminine','mete',['La mia meta è Roma.'],['a2']),
n('it_1359',1359,'frontiera','frontier/border','feminine','frontiere',['Attraverso la frontiera.'],['b1']),
n('it_1360',1360,'dogana','customs — see 1334','feminine','dogane',['—'],['b1']),
n('it_1361',1361,'visto','visa','masculine','visti',['Ho il visto per entrare.'],['a2']),
n('it_1362',1362,'permesso di soggiorno','residence permit','masculine',null,['Ho il permesso di soggiorno.'],['b1']),
n('it_1363',1363,'consolato','consulate','masculine','consolati',['Vado al consolato.'],['b1']),
n('it_1364',1364,'ambasciata','embassy','feminine','ambasciate',['L\'ambasciata italiana.'],['b1']),
n('it_1365',1365,'diplomatico','diplomat','masculine','diplomatici',['È un diplomatico.'],['b1']),
n('it_1366',1366,'trattato','treaty','masculine','trattati',['Firmano un trattato.'],['b1']),
n('it_1367',1367,'alleanza','alliance','feminine','alleanze',['Un\'alleanza strategica.'],['b1']),
n('it_1368',1368,'conflitto','conflict','masculine','conflitti',['Un conflitto armato.'],['a2']),
n('it_1369',1369,'pace','peace — see 152','feminine','paci',['—'],['a1']),
n('it_1370',1370,'negoziato','negotiation','masculine','negoziati',['Il negoziato è in corso.'],['b1']),
n('it_1371',1371,'accordo','agreement — see 607','masculine','accordi',['—'],['a2']),
n('it_1372',1372,'sanzione','sanction','feminine','sanzioni',['Le sanzioni economiche.'],['b1']),
n('it_1373',1373,'embargo','embargo','masculine','embargo',['Un embargo commerciale.'],['b1']),
n('it_1374',1374,'profugo','refugee','masculine','profughi',['I profughi cercano asilo.'],['b1']),
n('it_1375',1375,'asilo','asylum/nursery','masculine','asili',['Chiedono asilo politico.'],['b1']),
n('it_1376',1376,'integrazione','integration','feminine','integrazioni',['L\'integrazione è un processo.'],['b1']),
n('it_1377',1377,'discriminazione','discrimination','feminine','discriminazioni',['Lotta alla discriminazione.'],['b1']),
n('it_1378',1378,'razzismo','racism','masculine',null,['Il razzismo è sbagliato.'],['b1']),
n('it_1379',1379,'stereotipo','stereotype','masculine','stereotipi',['Gli stereotipi fanno male.'],['b1']),
n('it_1380',1380,'pregiudizio','prejudice','masculine','pregiudizi',['I pregiudizi vanno superati.'],['b1']),
n('it_1381',1381,'uguaglianza','equality','feminine',null,['L\'uguaglianza tra generi.'],['b1']),
n('it_1382',1382,'parità','parity/equality','feminine',null,['La parità salariale.'],['b1']),
n('it_1383',1383,'diversità','diversity','feminine','diversità',['La diversità è una ricchezza.'],['b1']),
n('it_1384',1384,'inclusione','inclusion','feminine','inclusioni',['Inclusione sociale.'],['b1']),
n('it_1385',1385,'esclusione','exclusion','feminine','esclusioni',['L\'esclusione sociale.'],['b1']),
n('it_1386',1386,'welfare','welfare','masculine',null,['Il welfare state.'],['b1']),
n('it_1387',1387,'sussidio','subsidy/benefit','masculine','sussidi',['Riceve un sussidio.'],['b1']),
n('it_1388',1388,'pensione','pension — see 1348','feminine','pensioni',['Va in pensione.'],['a2']),
n('it_1389',1389,'previdenza sociale','social security','feminine',null,['Pago la previdenza sociale.'],['b1']),
n('it_1390',1390,'sindicato','trade union','masculine','sindicati',['Il sindacato tutela i lavoratori.'],['b1']),
n('it_1391',1391,'contratto di lavoro','work contract','masculine',null,['Ho un contratto a tempo determinato.'],['b1']),
n('it_1392',1392,'orario di lavoro','working hours','masculine',null,['L\'orario di lavoro è otto ore.'],['a2']),
n('it_1393',1393,'ferie','vacation/annual leave','feminine',null,['Sono in ferie.'],['a2']),
n('it_1394',1394,'congedo','leave of absence','masculine','congedi',['Sono in congedo.'],['b1']),
n('it_1395',1395,'malattia','sick leave/illness — see 542','feminine','malattie',['Sono in malattia.'],['a2']),
n('it_1396',1396,'colloquio','interview/talk','masculine','colloqui',['Ho un colloquio domani.'],['b1']),
n('it_1397',1397,'candidatura','candidacy/application','feminine','candidature',['Presento la mia candidatura.'],['b1']),
n('it_1398',1398,'curriculum','curriculum vitae/resume','masculine','curriculum',['Mando il curriculum.'],['b1']),
n('it_1399',1399,'lettera di presentazione','cover letter','feminine',null,['Scrivo una lettera di presentazione.'],['b1']),
n('it_1400',1400,'assunzione','hiring','feminine','assunzioni',['È in cerca di assunzione.'],['b1']),
n('it_1401',1401,'licenziamento','dismissal','masculine','licenziamenti',['Ha ricevuto il licenziamento.'],['b1']),
n('it_1402',1402,'pensionamento','retirement','masculine','pensionamenti',['Va in pensionamento.'],['b1']),
n('it_1403',1403,'carriera','career — see 578','feminine','carriere',['Ha fatto carriera.'],['a2']),
n('it_1404',1404,'promozione','promotion','feminine','promozioni',['Ha ottenuto una promozione.'],['a2']),
n('it_1405',1405,'aggiornamento','update/training','masculine','aggiornamenti',['Corso di aggiornamento.'],['b1']),
n('it_1406',1406,'formazione','training/formation','feminine','formazioni',['La formazione professionale.'],['b1']),
n('it_1407',1407,'tirocinio','internship','masculine','tirocini',['Faccio un tirocinio.'],['b1']),
n('it_1408',1408,'stage','internship (from French)','masculine','stage',['Faccio uno stage.'],['b1']),
n('it_1409',1409,'volontariato','volunteering','masculine',null,['Faccio volontariato.'],['a2']),
n('it_1410',1410,'associazione','association','feminine','associazioni',['Partecipo all\'associazione.'],['a2']),
n('it_1411',1411,'fondazione','foundation','feminine','fondazioni',['Una fondazione culturale.'],['b1']),
n('it_1412',1412,'organizzazione non profit','non-profit organization','feminine',null,['Un\'organizzazione non profit.'],['b1']),
n('it_1413',1413,'donazione','donation','feminine','donazioni',['Faccio una donazione.'],['a2']),
n('it_1414',1414,'raccolta fondi','fundraising','feminine',null,['Una raccolta fondi.'],['b1']),
n('it_1415',1415,'evento','event','masculine','eventi',['Un grande evento.'],['a2']),
n('it_1416',1416,'fiera','fair/trade show','feminine','fiere',['La fiera del libro.'],['a2']),
n('it_1417',1417,'festival','festival','masculine','festival',['Il festival della musica.'],['a2']),
n('it_1418',1418,'cerimonia','ceremony','feminine','cerimonie',['Una cerimonia formale.'],['a2']),
n('it_1419',1419,'festività','holiday/festivity','feminine','festività',['Le festività natalizie.'],['a2']),
n('it_1420',1420,'anniversario','anniversary','masculine','anniversari',['Buon anniversario!'],['a2']),

// ADJECTIVES 1421-1470
adj('it_1421',1421,'abbondante','abundant','abbondanti',['Una quantità abbondante.'],['b1']),
adj('it_1422',1422,'scarso','scarce/poor','scarsi',['Le risorse sono scarse.'],['b1']),
adj('it_1423',1423,'sufficiente','sufficient','sufficienti',['Non è sufficiente.'],['a2']),
adj('it_1424',1424,'eccessivo','excessive','eccessivi',['Un costo eccessivo.'],['b1']),
adj('it_1425',1425,'moderato','moderate','moderati',['Una posizione moderata.'],['b1']),
adj('it_1426',1426,'estremo','extreme','estremi',['Condizioni estreme.'],['b1']),
adj('it_1427',1427,'medio','average/medium','medi',['Un reddito medio.'],['a2']),
adj('it_1428',1428,'superiore','superior/upper','superiori',['Di qualità superiore.'],['b1']),
adj('it_1429',1429,'inferiore','inferior/lower','inferiori',['Di qualità inferiore.'],['b1']),
adj('it_1430',1430,'uguale','equal — see 371','uguali',['—'],['a2']),
adj('it_1431',1431,'proporzionale','proportional','proporzionali',['È proporzionale.'],['b1']),
adj('it_1432',1432,'sproporzionato','disproportionate','sproporzionati',['È sproporzionato.'],['b1']),
adj('it_1433',1433,'equilibrato','balanced','equilibrati',['Un\'alimentazione equilibrata.'],['b1']),
adj('it_1434',1434,'sbilanciato','unbalanced','sbilanciati',['Una valutazione sbilanciata.'],['b1']),
adj('it_1435',1435,'coerente','coherent — see 1181','coerenti',['—'],['b1']),
adj('it_1436',1436,'solido','solid/sturdy','solidi',['Una base solida.'],['a2']),
adj('it_1437',1437,'fragile','fragile','fragili',['È molto fragile.'],['a2']),
adj('it_1438',1438,'resistente','resistant/sturdy','resistenti',['Un materiale resistente.'],['b1']),
adj('it_1439',1439,'flessibile','flexible','flessibili',['Orario flessibile.'],['b1']),
adj('it_1440',1440,'rigido','rigid/strict','rigidi',['Le regole sono rigide.'],['b1']),
adj('it_1441',1441,'adattabile','adaptable','adattabili',['È molto adattabile.'],['b1']),
adj('it_1442',1442,'versatile','versatile','versatili',['Un attore versatile.'],['b1']),
adj('it_1443',1443,'dinamico','dynamic','dinamici',['Una persona dinamica.'],['b1']),
adj('it_1444',1444,'statico','static','statici',['Una situazione statica.'],['b1']),
adj('it_1445',1445,'attivo','active','attivi',['Uno stile di vita attivo.'],['a2']),
adj('it_1446',1446,'passivo','passive','passivi',['Un atteggiamento passivo.'],['b1']),
adj('it_1447',1447,'aggressivo','aggressive','aggressivi',['Un tono aggressivo.'],['b1']),
adj('it_1448',1448,'assertivo','assertive','assertivi',['Sii assertivo.'],['b1']),
adj('it_1449',1449,'competitivo','competitive','competitivi',['Un mercato competitivo.'],['b1']),
adj('it_1450',1450,'cooperativo','cooperative','cooperativi',['Un approccio cooperativo.'],['b1']),
adj('it_1451',1451,'autonomo','autonomous/independent','autonomi',['Lavora in modo autonomo.'],['b1']),
adj('it_1452',1452,'dipendente','dependent','dipendenti',['È dipendente dagli altri.'],['b1']),
adj('it_1453',1453,'responsabile','responsible','responsabili',['È responsabile.'],['a2']),
adj('it_1454',1454,'irresponsabile','irresponsible','irresponsabili',['È irresponsabile.'],['a2']),
adj('it_1455',1455,'affidabile','reliable','affidabili',['È una persona affidabile.'],['b1']),
adj('it_1456',1456,'inaffidabile','unreliable','inaffidabili',['È inaffidabile.'],['b1']),
adj('it_1457',1457,'ambizioso','ambitious','ambiziosi',['È molto ambizioso.'],['b1']),
adj('it_1458',1458,'motivato','motivated','motivati',['È motivato al lavoro.'],['b1']),
adj('it_1459',1459,'appassionato','passionate','appassionati',['È appassionato di musica.'],['a2']),
adj('it_1460',1460,'entusiasta','enthusiastic','entusiasti',['Sono entusiasta del progetto.'],['a2']),
adj('it_1461',1461,'ottimista','optimistic','ottimisti',['Sono ottimista.'],['a2']),
adj('it_1462',1462,'pessimista','pessimistic','pessimisti',['È sempre pessimista.'],['a2']),
adj('it_1463',1463,'realista','realistic','realisti',['Sii realista.'],['a2']),
adj('it_1464',1464,'idealista','idealistic','idealisti',['È un idealista.'],['b1']),
adj('it_1465',1465,'pragmatico','pragmatic','pragmatici',['Un approccio pragmatico.'],['b1']),
adj('it_1466',1466,'utopico','utopian','utopici',['Un ideale utopico.'],['b1']),
adj('it_1467',1467,'conservatore','conservative','conservatori',['Un punto di vista conservatore.'],['b1']),
adj('it_1468',1468,'progressista','progressive','progressisti',['Una politica progressista.'],['b1']),
adj('it_1469',1469,'liberale','liberal','liberali',['Una visione liberale.'],['b1']),
adj('it_1470',1470,'radicale','radical','radicali',['Una posizione radicale.'],['b1']),

// ADVERBS 1471-1500
adv('it_1471',1471,'al contrario','on the contrary',['Al contrario, sono d\'accordo.'],['b1']),
adv('it_1472',1472,'viceversa','vice versa',['E viceversa.'],['b1']),
adv('it_1473',1473,'a mano a mano','gradually/as',['A mano a mano che passa.'],['b1']),
adv('it_1474',1474,'man mano','gradually',['Man mano capirò.'],['b1']),
adv('it_1475',1475,'via via','progressively',['Via via migliorerò.'],['b1']),
adv('it_1476',1476,'in seguito','subsequently',['In seguito ho capito.'],['b1']),
adv('it_1477',1477,'successivamente','subsequently',['Successivamente decise.'],['b1']),
adv('it_1478',1478,'precedentemente','previously',['Precedentemente aveva lavorato lì.'],['b1']),
adv('it_1479',1479,'contemporaneamente','simultaneously',['Lo faccio contemporaneamente.'],['b1']),
adv('it_1480',1480,'parallelamente','in parallel',['Lavoriamo parallelamente.'],['b1']),
adv('it_1481',1481,'indipendentemente','independently',['Lavora indipendentemente.'],['b1']),
adv('it_1482',1482,'reciprocamente','reciprocally',['Si aiutano reciprocamente.'],['b1']),
adv('it_1483',1483,'mutuamente','mutually',['Si rispettano mutuamente.'],['b1']),
adv('it_1484',1484,'volontariamente','voluntarily',['L\'ha fatto volontariamente.'],['b1']),
adv('it_1485',1485,'involontariamente','involuntarily',['L\'ha fatto involontariamente.'],['b1']),
adv('it_1486',1486,'deliberatamente','deliberately',['L\'ha fatto deliberatamente.'],['b1']),
adv('it_1487',1487,'accidentalmente','accidentally',['È successo accidentalmente.'],['b1']),
adv('it_1488',1488,'intenzionalmente','intentionally',['L\'ha fatto intenzionalmente.'],['b1']),
adv('it_1489',1489,'spontaneamente','spontaneously',['L\'ha fatto spontaneamente.'],['b1']),
adv('it_1490',1490,'naturalmente','naturally',['Naturalmente sì.'],['a2']),
adv('it_1491',1491,'artificialmente','artificially',['È prodotto artificialmente.'],['b1']),
adv('it_1492',1492,'organicamente','organically',['Coltivato organicamente.'],['b1']),
adv('it_1493',1493,'scientificamente','scientifically',['È provato scientificamente.'],['b1']),
adv('it_1494',1494,'tecnicamente','technically',['Tecnicamente è corretto.'],['b1']),
adv('it_1495',1495,'giuridicamente','legally/juridically',['È giuridicamente valido.'],['b1']),
adv('it_1496',1496,'economicamente','economically — see 664','economicamente',['—'],['b1']),
adv('it_1497',1497,'finanziariamente','financially',['È finanziariamente stabile.'],['b1']),
adv('it_1498',1498,'statisticamente','statistically',['Statisticamente improbabile.'],['b1']),
adv('it_1499',1499,'matematicamente','mathematically',['È matematicamente impossibile.'],['b1']),
adv('it_1500',1500,'fisicamente','physically',['È fisicamente forte.'],['b1']),
];

const final=e.filter(x=>!x.examples[0].startsWith('—'));
console.log(`Generated ${final.length} entries, ranks ${final[0].rank}-${final[final.length-1].rank}`);
const ranks=final.map(x=>x.rank);
const dups=ranks.filter((r,i)=>ranks.indexOf(r)!==i);
if(dups.length) console.warn('Duplicate ranks:',dups);
fs.writeFileSync(path.join(__dirname,'../src/data/words-006.json'),JSON.stringify(final,null,2));
console.log('words-006.json written.');
