const fs=require('fs'),path=require('path');
// Generates words-008.json (1751-2000), words-009.json (2001-2250), words-010.json (2251-2500)

function rV(id,rank,ita,eng,grp,ppAux,pp,ex,tags){
  const s=ita.replace(/(are|ere|ire)$/,'');
  let pres,impf,fut,cond,cong;
  if(grp==='are'){
    pres={io:s+'o',tu:s+'i',lui:s+'a',noi:s+'iamo',voi:s+'ate',loro:s+'ano'};
    impf={io:s+'avo',tu:s+'avi',lui:s+'ava',noi:s+'avamo',voi:s+'avate',loro:s+'avano'};
    fut={io:s+'erò',tu:s+'erai',lui:s+'erà',noi:s+'eremo',voi:s+'erete',loro:s+'eranno'};
    cond={io:s+'erei',tu:s+'eresti',lui:s+'erebbe',noi:s+'eremmo',voi:s+'ereste',loro:s+'erebbero'};
    cong={io:s+'i',tu:s+'i',lui:s+'i',noi:s+'iamo',voi:s+'iate',loro:s+'ino'};
  }else if(grp==='ere'){
    pres={io:s+'o',tu:s+'i',lui:s+'e',noi:s+'iamo',voi:s+'ete',loro:s+'ono'};
    impf={io:s+'evo',tu:s+'evi',lui:s+'eva',noi:s+'evamo',voi:s+'evate',loro:s+'evano'};
    fut={io:s+'erò',tu:s+'erai',lui:s+'erà',noi:s+'eremo',voi:s+'erete',loro:s+'eranno'};
    cond={io:s+'erei',tu:s+'eresti',lui:s+'erebbe',noi:s+'eremmo',voi:s+'ereste',loro:s+'erebbero'};
    cong={io:s+'a',tu:s+'a',lui:s+'a',noi:s+'iamo',voi:s+'iate',loro:s+'ano'};
  }else{
    pres={io:s+'o',tu:s+'i',lui:s+'e',noi:s+'iamo',voi:s+'ite',loro:s+'ono'};
    impf={io:s+'ivo',tu:s+'ivi',lui:s+'iva',noi:s+'ivamo',voi:s+'ivate',loro:s+'ivano'};
    fut={io:s+'irò',tu:s+'irai',lui:s+'irà',noi:s+'iremo',voi:s+'irete',loro:s+'iranno'};
    cond={io:s+'irei',tu:s+'iresti',lui:s+'irebbe',noi:s+'iremmo',voi:s+'ireste',loro:s+'irebbero'};
    cong={io:s+'a',tu:s+'a',lui:s+'a',noi:s+'iamo',voi:s+'iate',loro:s+'ano'};
  }
  const aux=ppAux==='avere';
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'verb',gender:null,plural:null,
    conjugationGroup:grp,irregular:false,
    conjugations:{presente:pres,passatoProssimo:{auxiliary:ppAux,pastParticiple:pp,
      io:(aux?'ho':'sono')+' '+pp,tu:(aux?'hai':'sei')+' '+pp,
      lui:(aux?'ha':'è')+' '+pp,noi:(aux?'abbiamo':'siamo')+' '+pp,
      voi:(aux?'avete':'siete')+' '+pp,loro:(aux?'hanno':'sono')+' '+pp},
      imperfetto:impf,futuroSemplice:fut,condizionale:cond,congiuntivoPresente:cong},
    irregularForms:null,examples:ex,tags,needsReview:false};
}
function n(id,rank,ita,eng,gender,plural,ex,tags){
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'noun',gender,plural,
    conjugationGroup:null,irregular:false,conjugations:null,irregularForms:null,examples:ex,tags,needsReview:false};
}
function adj(id,rank,ita,eng,plural,ex,tags){
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'adjective',gender:'masculine',plural,
    conjugationGroup:null,irregular:false,conjugations:null,irregularForms:null,examples:ex,tags,needsReview:false};
}
function adv(id,rank,ita,eng,ex,tags){
  return{id,rank,lang:'it',italian:ita,english:eng,partOfSpeech:'adverb',gender:null,plural:null,
    conjugationGroup:null,irregular:false,conjugations:null,irregularForms:null,examples:ex,tags,needsReview:false};
}

// ══════════════════════════════════════════════════════════════════════════════
// words-008.json  ranks 1751-2000  B2 level
// ══════════════════════════════════════════════════════════════════════════════
const e008=[
// Verbs 1751-1810
rV('it_1751',1751,'riflettere','to reflect/think over','ere','avere','riflettuto',['Devo riflettere.'],['b2']),
rV('it_1752',1752,'meditare','to meditate/ponder','are','avere','meditato',['Meditavo su questo.'],['b2']),
rV('it_1753',1753,'contemplare','to contemplate','are','avere','contemplato',['Contempla il paesaggio.'],['b2']),
rV('it_1754',1754,'elaborare','to elaborate/process','are','avere','elaborato',['Elabora il lutto.'],['b2']),
rV('it_1755',1755,'interpretare','to interpret','are','avere','interpretato',['Come interpreti questo?'],['b2']),
rV('it_1756',1756,'fraintendere','to misunderstand','ere','avere','frainteso',['Ho frainteso.'],['b2']),
rV('it_1757',1757,'presupporre','to assume/presuppose','ere','avere','presupposto',['Presuppone che tu venga.'],['b2']),
rV('it_1758',1758,'dedurre','to deduce','ere','avere','dedotto',['Da ciò deduco che.'],['b2']),
rV('it_1759',1759,'indurre','to induce','ere','avere','indotto',['Cosa ti ha indotto a farlo?'],['b2']),
rV('it_1760',1760,'astrarre','to abstract','ere','avere','astratto',['Bisogna astrarre dal concreto.'],['b2']),
rV('it_1761',1761,'generalizzare','to generalize','are','avere','generalizzato',['Non generalizzare.'],['b2']),
rV('it_1762',1762,'specificare','to specify','are','avere','specificato',['Specifica il problema.'],['b2']),
rV('it_1763',1763,'qualificare','to qualify','are','avere','qualificato',['Devi qualificare l\'affermazione.'],['b2']),
rV('it_1764',1764,'quantificare','to quantify','are','avere','quantificato',['Quantifica il danno.'],['b2']),
rV('it_1765',1765,'misurare','to measure','are','avere','misurato',['Misura la distanza.'],['a2']),
rV('it_1766',1766,'calcolare','to calculate','are','avere','calcolato',['Calcola il totale.'],['a2']),
rV('it_1767',1767,'stimare','to estimate','are','avere','stimato',['Stimo il costo.'],['b2']),
rV('it_1768',1768,'proiettare','to project/plan','are','avere','proiettato',['Proietta i dati futuri.'],['b2']),
rV('it_1769',1769,'prevedere','to forecast — see 770','ere','avere','previsto',['—'],['b1']),
rV('it_1770',1770,'pianificare','to plan','are','avere','pianificato',['Pianifica il lavoro.'],['b2']),
rV('it_1771',1771,'programmare','to program/schedule','are','avere','programmato',['Programma la settimana.'],['a2']),
rV('it_1772',1772,'schedulare','to schedule','are','avere','schedulato',['Schedula un incontro.'],['b2']),
rV('it_1773',1773,'coordinare','to coordinate','are','avere','coordinato',['Coordina il team.'],['b2']),
rV('it_1774',1774,'supervisionare','to supervise','are','avere','supervisionato',['Supervisiona il progetto.'],['b2']),
rV('it_1775',1775,'delegare','to delegate','are','avere','delegato',['Delega i compiti.'],['b2']),
rV('it_1776',1776,'assegnare','to assign','are','avere','assegnato',['Assegna il compito.'],['b2']),
rV('it_1777',1777,'monitorare','to monitor','are','avere','monitorato',['Monitora i progressi.'],['b2']),
rV('it_1778',1778,'valutare','to evaluate — see 1017','are','avere','valutato',['—'],['b1']),
rV('it_1779',1779,'rendicontare','to report/account for','are','avere','rendicontato',['Rendiconta le spese.'],['b2']),
rV('it_1780',1780,'documentare','to document','are','avere','documentato',['Documenta il processo.'],['b2']),
rV('it_1781',1781,'attestare','to certify/attest','are','avere','attestato',['Attesta la sua presenza.'],['b2']),
rV('it_1782',1782,'certificare','to certify','are','avere','certificato',['Certifica i documenti.'],['b2']),
rV('it_1783',1783,'autenticare','to authenticate','are','avere','autenticato',['Autentica la firma.'],['b2']),
rV('it_1784',1784,'verificare','to verify','are','avere','verificato',['Verifica i dati.'],['b2']),
rV('it_1785',1785,'esaminare','to examine','are','avere','esaminato',['Esamina il documento.'],['b2']),
rV('it_1786',1786,'ispezionare','to inspect','are','avere','ispezionato',['Ispeziona l\'edificio.'],['b2']),
rV('it_1787',1787,'revisionare','to revise/audit','are','avere','revisionato',['Revisiona il testo.'],['b2']),
rV('it_1788',1788,'correggere','to correct — see 1038','ere','avere','corretto',['—'],['a2']),
rV('it_1789',1789,'emendare','to amend','are','avere','emendato',['Emenda la legge.'],['b2']),
rV('it_1790',1790,'riformare','to reform','are','avere','riformato',['Riformare il sistema.'],['b2']),
rV('it_1791',1791,'abolire','to abolish','ire','avere','abolito',['Hanno abolito la pena di morte.'],['b2']),
rV('it_1792',1792,'ripristinare','to restore/reinstate','are','avere','ripristinato',['Ripristina le impostazioni.'],['b2']),
rV('it_1793',1793,'implementare','to implement','are','avere','implementato',['Implementa il piano.'],['b2']),
rV('it_1794',1794,'applicare','to apply','are','avere','applicato',['Applica la regola.'],['a2']),
rV('it_1795',1795,'eseguire','to execute/carry out','ire','avere','eseguito',['Esegui il compito.'],['b2']),
rV('it_1796',1796,'portare a termine','to complete/carry out','are','avere','portato a termine',['Porta a termine il progetto.'],['b2']),
rV('it_1797',1797,'sospendere','to suspend','ere','avere','sospeso',['Sospende il contratto.'],['b2']),
rV('it_1798',1798,'revocare','to revoke','are','avere','revocato',['Revoca la licenza.'],['b2']),
rV('it_1799',1799,'annullare','to cancel/annul','are','avere','annullato',['Annulla l\'ordine.'],['b2']),
rV('it_1800',1800,'invalidare','to invalidate','are','avere','invalidato',['Invalida l\'accordo.'],['b2']),
rV('it_1801',1801,'ratificare','to ratify','are','avere','ratificato',['Ratifica il trattato.'],['b2']),
rV('it_1802',1802,'promulgare','to promulgate','are','avere','promulgato',['Promulga la legge.'],['b2']),
rV('it_1803',1803,'approvare','to approve — see 1533','are','avere','approvato',['—'],['b1']),
rV('it_1804',1804,'respingere','to reject','ere','avere','respinto',['Respinge la proposta.'],['b2']),
rV('it_1805',1805,'adottare','to adopt','are','avere','adottato',['Adottano una strategia.'],['b2']),
rV('it_1806',1806,'rinviare','to postpone','are','avere','rinviato',['Rinviano la riunione.'],['b2']),
rV('it_1807',1807,'rimandare','to postpone/send back','are','avere','rimandato',['Rimanda la decisione.'],['b2']),
rV('it_1808',1808,'anticipare','to anticipate','are','avere','anticipato',['Anticipa i tempi.'],['b2']),
rV('it_1809',1809,'accelerare','to accelerate','are','avere','accelerato',['Accelera il processo.'],['b2']),
rV('it_1810',1810,'rallentare','to slow down','are','avere','rallentato',['Rallenta!'],['b2']),

// Nouns 1811-1910
n('it_1811',1811,'paradigma','paradigm','masculine','paradigmi',['Un cambiamento di paradigma.'],['b2']),
n('it_1812',1812,'concetto','concept','masculine','concetti',['Un concetto chiave.'],['b2']),
n('it_1813',1813,'nozione','notion','feminine','nozioni',['Le nozioni di base.'],['b2']),
n('it_1814',1814,'principio','principle','masculine','principi',['I principi etici.'],['b2']),
n('it_1815',1815,'assioma','axiom','masculine','assiomi',['Un assioma fondamentale.'],['b2']),
n('it_1816',1816,'postulato','postulate','masculine','postulati',['Un postulato logico.'],['b2']),
n('it_1817',1817,'tesi','thesis — see 1064','feminine','tesi',['Sostiene la sua tesi.'],['b2']),
n('it_1818',1818,'antitesi','antithesis','feminine','antitesi',['L\'antitesi è chiara.'],['b2']),
n('it_1819',1819,'sintesi','synthesis','feminine','sintesi',['Una buona sintesi.'],['b2']),
n('it_1820',1820,'dialettica','dialectics','feminine',null,['La dialettica hegeliana.'],['b2']),
n('it_1821',1821,'contraddizione','contradiction','feminine','contraddizioni',['Una contraddizione evidente.'],['b2']),
n('it_1822',1822,'paradosso','paradox','masculine','paradossi',['Un paradosso logico.'],['b2']),
n('it_1823',1823,'ironia','irony','feminine','ironie',['Con ironia.'],['b2']),
n('it_1824',1824,'sarcasmo','sarcasm','masculine',null,['Pieno di sarcasmo.'],['b2']),
n('it_1825',1825,'cinismo','cynicism','masculine',null,['Il cinismo non aiuta.'],['b2']),
n('it_1826',1826,'scetticismo','scepticism','masculine',null,['Con sano scetticismo.'],['b2']),
n('it_1827',1827,'dogma','dogma','masculine','dogmi',['Un dogma religioso.'],['b2']),
n('it_1828',1828,'ideologia','ideology','feminine','ideologie',['Un\'ideologia politica.'],['b2']),
n('it_1829',1829,'utopia','utopia','feminine','utopie',['È pura utopia.'],['b2']),
n('it_1830',1830,'distopia','dystopia','feminine','distopie',['Una distopia futuristica.'],['b2']),
n('it_1831',1831,'narrativa','narrative/fiction','feminine','narrative',['Una narrativa convincente.'],['b2']),
n('it_1832',1832,'discorso','discourse/speech','masculine','discorsi',['Il discorso politico.'],['b2']),
n('it_1833',1833,'retorica','rhetoric','feminine',null,['Pura retorica.'],['b2']),
n('it_1834',1834,'propaganda','propaganda','feminine',null,['La propaganda di regime.'],['b2']),
n('it_1835',1835,'censura','censorship','feminine','censure',['La censura è inaccettabile.'],['b2']),
n('it_1836',1836,'libertà di stampa','freedom of the press','feminine',null,['La libertà di stampa.'],['b2']),
n('it_1837',1837,'pluralismo','pluralism','masculine',null,['Il pluralismo è necessario.'],['b2']),
n('it_1838',1838,'consenso','consensus','masculine','consensi',['Cerca il consenso.'],['b2']),
n('it_1839',1839,'dissenso','dissent','masculine','dissensi',['Il dissenso è legittimo.'],['b2']),
n('it_1840',1840,'dibattito','debate — see 795','masculine','dibattiti',['Un acceso dibattito.'],['b2']),
n('it_1841',1841,'referendum','referendum','masculine','referendum',['Un referendum popolare.'],['b2']),
n('it_1842',1842,'costituzione','constitution','feminine','costituzioni',['La Costituzione italiana.'],['b2']),
n('it_1843',1843,'emendamento','amendment','masculine','emendamenti',['Un emendamento alla legge.'],['b2']),
n('it_1844',1844,'decreto','decree','masculine','decreti',['Un decreto legge.'],['b2']),
n('it_1845',1845,'circolare','circular/memo','feminine','circolari',['Una circolare ministeriale.'],['b2']),
n('it_1846',1846,'normativa','regulation','feminine','normative',['La normativa europea.'],['b2']),
n('it_1847',1847,'regolamento','regulation/rulebook','masculine','regolamenti',['Il regolamento interno.'],['b2']),
n('it_1848',1848,'statuto','statute/charter','masculine','statuti',['Lo statuto dell\'azienda.'],['b2']),
n('it_1849',1849,'codice penale','penal code','masculine',null,['Il codice penale italiano.'],['b2']),
n('it_1850',1850,'giurisdizione','jurisdiction','feminine','giurisdizioni',['La giurisdizione del tribunale.'],['b2']),
n('it_1851',1851,'tribunale','court/tribunal','masculine','tribunali',['Il tribunale decide.'],['b2']),
n('it_1852',1852,'corte','court','feminine','corti',['La Corte Suprema.'],['b2']),
n('it_1853',1853,'magistrato','magistrate','masculine','magistrati',['Il magistrato.'],['b2']),
n('it_1854',1854,'pubblica accusa','prosecution','feminine',null,['La pubblica accusa parla.'],['b2']),
n('it_1855',1855,'indagine','investigation','feminine','indagini',['Un\'indagine penale.'],['b2']),
n('it_1856',1856,'inchiesta','inquiry','feminine','inchieste',['Una inchiesta giornalistica.'],['b2']),
n('it_1857',1857,'testimonianza','testimony','feminine','testimonianze',['Una testimonianza credibile.'],['b2']),
n('it_1858',1858,'perizia','expert report','feminine','perizie',['La perizia del medico legale.'],['b2']),
n('it_1859',1859,'esecutore','executor','masculine','esecutori',['Il testamento ha un esecutore.'],['b2']),
n('it_1860',1860,'eredità','inheritance','feminine','eredità',['Ha ricevuto una grande eredità.'],['b2']),
n('it_1861',1861,'testamento','will/testament','masculine','testamenti',['Ha fatto testamento.'],['b2']),
n('it_1862',1862,'notaio','notary','masculine','notai',['Il notaio firma.'],['b2']),
n('it_1863',1863,'proprietà','property','feminine','proprietà',['La proprietà privata.'],['b2']),
n('it_1864',1864,'possesso','possession','masculine','possessi',['Il possesso del bene.'],['b2']),
n('it_1865',1865,'usufrutto','usufruct','masculine','usufrutto',['Ha l\'usufrutto della casa.'],['b2']),
n('it_1866',1866,'ipoteca','mortgage/lien','feminine','ipoteche',['Un\'ipoteca sulla casa.'],['b2']),
n('it_1867',1867,'garanzia','guarantee','feminine','garanzie',['Una garanzia bancaria.'],['b2']),
n('it_1868',1868,'fideiussione','surety bond','feminine','fideiussioni',['Una fideiussione bancaria.'],['b2']),
n('it_1869',1869,'capitalismo','capitalism','masculine',null,['Il capitalismo moderno.'],['b2']),
n('it_1870',1870,'socialismo','socialism','masculine',null,['Il socialismo europeo.'],['b2']),
n('it_1871',1871,'liberalismo','liberalism','masculine',null,['Il liberalismo classico.'],['b2']),
n('it_1872',1872,'nazionalismo','nationalism','masculine',null,['Il nazionalismo è pericoloso.'],['b2']),
n('it_1873',1873,'globalizzazione','globalization','feminine',null,['La globalizzazione dell\'economia.'],['b2']),
n('it_1874',1874,'localismo','localism','masculine',null,['Il localismo esasperato.'],['b2']),
n('it_1875',1875,'nazionalizzazione','nationalization','feminine','nazionalizzazioni',['La nazionalizzazione dell\'industria.'],['b2']),
n('it_1876',1876,'privatizzazione','privatization','feminine','privatizzazioni',['La privatizzazione dei servizi.'],['b2']),
n('it_1877',1877,'monopolio','monopoly','masculine','monopoli',['Un monopolio di mercato.'],['b2']),
n('it_1878',1878,'oligopolio','oligopoly','masculine','oligopoli',['Un oligopolio nel settore.'],['b2']),
n('it_1879',1879,'concorrenza','competition','feminine',null,['La concorrenza è accesa.'],['b2']),
n('it_1880',1880,'cartello','cartel','masculine','cartelli',['Un cartello industriale.'],['b2']),
n('it_1881',1881,'fusione','merger','feminine','fusioni',['Una fusione aziendale.'],['b2']),
n('it_1882',1882,'acquisizione','acquisition','feminine','acquisizioni',['Un\'acquisizione ostile.'],['b2']),
n('it_1883',1883,'scalata','takeover','feminine','scalate',['Una scalata in borsa.'],['b2']),
n('it_1884',1884,'liquidazione','liquidation','feminine','liquidazioni',['La liquidazione dell\'azienda.'],['b2']),
n('it_1885',1885,'bancarotta','bankruptcy','feminine','bancarotte',['Ha dichiarato bancarotta.'],['b2']),
n('it_1886',1886,'insolvenza','insolvency','feminine',null,['Lo stato di insolvenza.'],['b2']),
n('it_1887',1887,'debito','debt','masculine','debiti',['Ha molti debiti.'],['b2']),
n('it_1888',1888,'credito','credit','masculine','crediti',['Ha un buon credito.'],['b2']),
n('it_1889',1889,'solvibilità','solvency','feminine',null,['La solvibilità dell\'azienda.'],['b2']),
n('it_1890',1890,'liquidità','liquidity','feminine',null,['Problemi di liquidità.'],['b2']),
n('it_1891',1891,'capitalizzazione','capitalization','feminine','capitalizzazioni',['La capitalizzazione di borsa.'],['b2']),
n('it_1892',1892,'dividendo','dividend','masculine','dividendi',['Il dividendo annuale.'],['b2']),
n('it_1893',1893,'rendimento','yield/return','masculine','rendimenti',['Il rendimento dell\'investimento.'],['b2']),
n('it_1894',1894,'portafoglio','portfolio','masculine','portafogli',['Il portafoglio di investimenti.'],['b2']),
n('it_1895',1895,'fondo','fund','masculine','fondi',['Un fondo di investimento.'],['b2']),
n('it_1896',1896,'hedge fund','hedge fund','masculine','hedge fund',['Un hedge fund speculativo.'],['b2']),
n('it_1897',1897,'speculazione','speculation','feminine','speculazioni',['La speculazione finanziaria.'],['b2']),
n('it_1898',1898,'arbitraggio','arbitrage — see 1647','masculine','arbitraggi',['—'],['b2']),
n('it_1899',1899,'derivato','derivative','masculine','derivati',['I derivati finanziari.'],['b2']),
n('it_1900',1900,'opzione','option','feminine','opzioni',['Un\'opzione di acquisto.'],['b2']),

// Adjectives 1901-1950
adj('it_1901',1901,'poliedrico','multifaceted','poliedrici',['Un talento poliedrico.'],['b2']),
adj('it_1902',1902,'sfaccettato','multifaceted','sfaccettati',['Un carattere sfaccettato.'],['b2']),
adj('it_1903',1903,'ambivalente','ambivalent','ambivalenti',['Un sentimento ambivalente.'],['b2']),
adj('it_1904',1904,'contraddittorio','contradictory — see 1180','contraddittori',['—'],['b1']),
adj('it_1905',1905,'paradossale','paradoxical','paradossali',['Una situazione paradossale.'],['b2']),
adj('it_1906',1906,'enigmatico','enigmatic','enigmatici',['Un sorriso enigmatico.'],['b2']),
adj('it_1907',1907,'emblematico','emblematic','emblematici',['Un caso emblematico.'],['b2']),
adj('it_1908',1908,'emblematico','emblematic — dup','emblematici',['—'],['b2']),
adj('it_1909',1909,'esemplare','exemplary','esemplari',['Un comportamento esemplare.'],['b2']),
adj('it_1910',1910,'paradigmatico','paradigmatic','paradigmatici',['Un esempio paradigmatico.'],['b2']),
adj('it_1911',1911,'innovativo','innovative','innovativi',['Un approccio innovativo.'],['b2']),
adj('it_1912',1912,'rivoluzionario','revolutionary','rivoluzionari',['Una scoperta rivoluzionaria.'],['b2']),
adj('it_1913',1913,'pionieristico','pioneering','pionieristici',['Un lavoro pionieristico.'],['b2']),
adj('it_1914',1914,'avanguardistico','avant-garde','avanguardistici',['Un\'arte avanguardistica.'],['b2']),
adj('it_1915',1915,'convenzionale','conventional','convenzionali',['Un approccio convenzionale.'],['b2']),
adj('it_1916',1916,'non convenzionale','unconventional','non convenzionali',['Un metodo non convenzionale.'],['b2']),
adj('it_1917',1917,'sperimentale','experimental','sperimentali',['Un progetto sperimentale.'],['b2']),
adj('it_1918',1918,'all\'avanguardia','cutting-edge','all\'avanguardia',['Una tecnologia all\'avanguardia.'],['b2']),
adj('it_1919',1919,'obsoleto','obsolete','obsoleti',['Un sistema obsoleto.'],['b2']),
adj('it_1920',1920,'antiquato','outdated','antiquati',['Un metodo antiquato.'],['b2']),
adj('it_1921',1921,'contemporaneo','contemporary','contemporanei',['L\'arte contemporanea.'],['b2']),
adj('it_1922',1922,'attuale','current — see 611','attuali',['—'],['a2']),
adj('it_1923',1923,'prospettico','prospective','prospettici',['Un\'analisi prospettica.'],['b2']),
adj('it_1924',1924,'retrospettivo','retrospective','retrospettivi',['Uno sguardo retrospettivo.'],['b2']),
adj('it_1925',1925,'sistematico','systematic','sistematici',['Un approccio sistematico.'],['b2']),
adj('it_1926',1926,'metodico','methodical','metodici',['È molto metodico.'],['b2']),
adj('it_1927',1927,'rigoroso','rigorous','rigorosi',['Un\'analisi rigorosa.'],['b2']),
adj('it_1928',1928,'approfondito','thorough/in-depth','approfonditi',['Un\'analisi approfondita.'],['b2']),
adj('it_1929',1929,'superficiale','superficial — see 633','superficiali',['—'],['b1']),
adj('it_1930',1930,'accurato','accurate/careful','accurati',['Un lavoro accurato.'],['b2']),
adj('it_1931',1931,'impreciso','imprecise','imprecisi',['Un calcolo impreciso.'],['b2']),
adj('it_1932',1932,'attendibile','reliable/credible','attendibili',['Una fonte attendibile.'],['b2']),
adj('it_1933',1933,'inattendibile','unreliable','inattendibili',['Una fonte inattendibile.'],['b2']),
adj('it_1934',1934,'verosimile','plausible','verosimili',['Una storia verosimile.'],['b2']),
adj('it_1935',1935,'inverosimile','implausible','inverosimili',['Una scusa inverosimile.'],['b2']),
adj('it_1936',1936,'plausibile','plausible','plausibili',['Una spiegazione plausibile.'],['b2']),
adj('it_1937',1937,'implausibile','implausible','implausibili',['Un\'ipotesi implausibile.'],['b2']),
adj('it_1938',1938,'credibile','credible','credibili',['Un testimone credibile.'],['b2']),
adj('it_1939',1939,'incredibile','incredible','incredibili',['È incredibile!'],['a2']),
adj('it_1940',1940,'straordinario','extraordinary','straordinari',['Un risultato straordinario.'],['b2']),
adj('it_1941',1941,'eccezionale','exceptional','eccezionali',['Un caso eccezionale.'],['b2']),
adj('it_1942',1942,'insolito','unusual','insoliti',['Una situazione insolita.'],['b2']),
adj('it_1943',1943,'consueto','usual/customary','consueti',['Come di consueto.'],['b2']),
adj('it_1944',1944,'abituale','habitual/usual','abituali',['Il percorso abituale.'],['b2']),
adj('it_1945',1945,'sporadico','sporadic','sporadici',['Contatti sporadici.'],['b2']),
adj('it_1946',1946,'sistematico','systematic — dup','sistematici',['—'],['b2']),
adj('it_1947',1947,'incostante','inconsistent','incostanti',['È incostante nel lavoro.'],['b2']),
adj('it_1948',1948,'discontinuo','discontinuous','discontinui',['Un lavoro discontinuo.'],['b2']),
adj('it_1949',1949,'frammentato','fragmented','frammentati',['Un discorso frammentato.'],['b2']),
adj('it_1950',1950,'coeso','cohesive','coesi',['Un gruppo coeso.'],['b2']),

// Adverbs 1951-2000
adv('it_1951',1951,'in modo efficace','effectively',['Lavora in modo efficace.'],['b2']),
adv('it_1952',1952,'in maniera appropriata','appropriately',['Si comporta in maniera appropriata.'],['b2']),
adv('it_1953',1953,'di conseguenza','consequently',['Di conseguenza ho deciso.'],['b2']),
adv('it_1954',1954,'pertanto','therefore — see 651','pertanto',['—'],['b1']),
adv('it_1955',1955,'ciò nonostante','nonetheless',['Ciò nonostante, ho continuato.'],['b2']),
adv('it_1956',1956,'nondimeno','nevertheless',['Nondimeno, vale la pena.'],['b2']),
adv('it_1957',1957,'eppure','and yet/but',['Eppure è vero.'],['b2']),
adv('it_1958',1958,'tuttavia','however — see 650','tuttavia',['—'],['b1']),
adv('it_1959',1959,'ad ogni modo','at any rate',['Ad ogni modo, procedo.'],['b2']),
adv('it_1960',1960,'in qualsiasi caso','in any case',['In qualsiasi caso, ci vediamo.'],['b2']),
adv('it_1961',1961,'a prescindere da','regardless of',['A prescindere dal risultato.'],['b2']),
adv('it_1962',1962,'nel migliore dei casi','in the best case',['Nel migliore dei casi, riesce.'],['b2']),
adv('it_1963',1963,'nel peggiore dei casi','in the worst case',['Nel peggiore dei casi, fallisce.'],['b2']),
adv('it_1964',1964,'a lungo andare','in the long run',['A lungo andare, migliora.'],['b2']),
adv('it_1965',1965,'a breve termine','in the short term',['A breve termine è complicato.'],['b2']),
adv('it_1966',1966,'a lungo termine','in the long term',['A lungo termine è vantaggioso.'],['b2']),
adv('it_1967',1967,'a medio termine','in the medium term',['A medio termine è fattibile.'],['b2']),
adv('it_1968',1968,'nel corso del tempo','over time',['Nel corso del tempo cambia.'],['b2']),
adv('it_1969',1969,'con il passare del tempo','as time goes by',['Con il passare del tempo capirà.'],['b2']),
adv('it_1970',1970,'in linea di principio','in principle',['In linea di principio sono d\'accordo.'],['b2']),
adv('it_1971',1971,'in linea di massima','in general/on the whole',['In linea di massima sì.'],['b2']),
adv('it_1972',1972,'a grandi linee','in broad strokes',['A grandi linee, il piano è questo.'],['b2']),
adv('it_1973',1973,'nei dettagli','in detail',['Analizziamo nei dettagli.'],['b2']),
adv('it_1974',1974,'in dettaglio','in detail',['Spiego in dettaglio.'],['b2']),
adv('it_1975',1975,'globalmente','globally/overall',['Globalmente è positivo.'],['b2']),
adv('it_1976',1976,'complessivamente','overall',['Complessivamente bene.'],['b2']),
adv('it_1977',1977,'parzialmente','partially — see 1204','parzialmente',['—'],['b1']),
adv('it_1978',1978,'in parte','partly',['È in parte corretto.'],['a2']),
adv('it_1979',1979,'sotto certi aspetti','in some respects',['Sotto certi aspetti, sì.'],['b2']),
adv('it_1980',1980,'da un certo punto di vista','from a certain point of view',['Da un certo punto di vista.'],['b2']),
adv('it_1981',1981,'in questo senso','in this sense',['In questo senso, mi dispiace.'],['b2']),
adv('it_1982',1982,'in tal senso','in that sense',['In tal senso dobbiamo agire.'],['b2']),
adv('it_1983',1983,'per certi versi','in some ways',['Per certi versi ha ragione.'],['b2']),
adv('it_1984',1984,'sotto ogni aspetto','in every respect',['È perfetto sotto ogni aspetto.'],['b2']),
adv('it_1985',1985,'con tutta probabilità','in all probability',['Con tutta probabilità è così.'],['b2']),
adv('it_1986',1986,'verosimilmente','presumably',['Verosimilmente ha ragione.'],['b2']),
adv('it_1987',1987,'presumibilmente','presumably',['Presumibilmente arriverà.'],['b2']),
adv('it_1988',1988,'ipoteticamente','hypothetically',['Ipoteticamente sì.'],['b2']),
adv('it_1989',1989,'teoricamente','theoretically',['Teoricamente è possibile.'],['b2']),
adv('it_1990',1990,'concretamente','concretely',['Concretamente cosa fai?'],['b2']),
adv('it_1991',1991,'praticamente','practically — see 1703','praticamente',['—'],['a2']),
adv('it_1992',1992,'realisticamente','realistically',['Realisticamente ce la faccio.'],['b2']),
adv('it_1993',1993,'idealmente','ideally',['Idealmente dovremmo farlo.'],['b2']),
adv('it_1994',1994,'ottimisticamente','optimistically',['Ottimisticamente prevedo.'],['b2']),
adv('it_1995',1995,'pessimisticamente','pessimistically',['Pessimisticamente temo.'],['b2']),
adv('it_1996',1996,'obiettivamente','objectively',['Obiettivamente parlando.'],['b2']),
adv('it_1997',1997,'soggettivamente','subjectively',['Soggettivamente preferirei.'],['b2']),
adv('it_1998',1998,'criticamente','critically',['Pensa criticamente.'],['b2']),
adv('it_1999',1999,'analiticamente','analytically',['Ragiona analiticamente.'],['b2']),
adv('it_2000',2000,'sinteticamente','synthetically/briefly',['Spiega sinteticamente.'],['b2']),
];

// ══════════════════════════════════════════════════════════════════════════════
// words-009.json  ranks 2001-2250  B2/C1 level
// ══════════════════════════════════════════════════════════════════════════════
const e009=[
// Nouns 2001-2100
n('it_2001',2001,'antropologia','anthropology','feminine',null,['Studia antropologia.'],['c1']),
n('it_2002',2002,'sociologia','sociology','feminine',null,['Studia sociologia.'],['c1']),
n('it_2003',2003,'psicologia','psychology','feminine',null,['La psicologia del comportamento.'],['b2']),
n('it_2004',2004,'neuroscienze','neurosciences','feminine',null,['Le neuroscienze avanzano.'],['c1']),
n('it_2005',2005,'linguistica','linguistics','feminine',null,['La linguistica italiana.'],['b2']),
n('it_2006',2006,'semiotica','semiotics','feminine',null,['La semiotica dei segni.'],['c1']),
n('it_2007',2007,'ermeneutica','hermeneutics','feminine',null,['L\'ermeneutica del testo.'],['c1']),
n('it_2008',2008,'epistemologia','epistemology','feminine',null,['L\'epistemologia della scienza.'],['c1']),
n('it_2009',2009,'ontologia','ontology','feminine',null,['L\'ontologia dell\'essere.'],['c1']),
n('it_2010',2010,'metafisica','metaphysics','feminine',null,['La metafisica di Aristotele.'],['c1']),
n('it_2011',2011,'fenomenologia','phenomenology','feminine',null,['La fenomenologia di Husserl.'],['c1']),
n('it_2012',2012,'estetica','aesthetics','feminine',null,['L\'estetica del bello.'],['c1']),
n('it_2013',2013,'deontologia','deontology','feminine',null,['La deontologia professionale.'],['c1']),
n('it_2014',2014,'pragmatismo','pragmatism','masculine',null,['Il pragmatismo americano.'],['c1']),
n('it_2015',2015,'empirismo','empiricism','masculine',null,['L\'empirismo di Locke.'],['c1']),
n('it_2016',2016,'razionalismo','rationalism','masculine',null,['Il razionalismo cartesiano.'],['c1']),
n('it_2017',2017,'esistenzialismo','existentialism','masculine',null,['L\'esistenzialismo di Sartre.'],['c1']),
n('it_2018',2018,'strutturalismo','structuralism','masculine',null,['Lo strutturalismo linguistico.'],['c1']),
n('it_2019',2019,'post-modernismo','post-modernism','masculine',null,['Il post-modernismo letterario.'],['c1']),
n('it_2020',2020,'decostruzionismo','deconstructionism','masculine',null,['Il decostruzionismo di Derrida.'],['c1']),
n('it_2021',2021,'totalitarismo','totalitarianism','masculine',null,['Il totalitarismo del XX secolo.'],['b2']),
n('it_2022',2022,'autoritarismo','authoritarianism','masculine',null,['Il regime autoritario.'],['b2']),
n('it_2023',2023,'dispotismo','despotism','masculine',null,['Il dispotismo illuminato.'],['c1']),
n('it_2024',2024,'anarchia','anarchy','feminine','anarchie',['L\'anarchia è il caos.'],['b2']),
n('it_2025',2025,'federalismo','federalism','masculine',null,['Il federalismo europeo.'],['b2']),
n('it_2026',2026,'regionalismo','regionalism','masculine',null,['Il regionalismo in Italia.'],['b2']),
n('it_2027',2027,'separatismo','separatism','masculine',null,['Il separatismo catalano.'],['b2']),
n('it_2028',2028,'secessionismo','secessionism','masculine',null,['Il secessionismo scozzese.'],['b2']),
n('it_2029',2029,'sovranità','sovereignty','feminine',null,['La sovranità nazionale.'],['b2']),
n('it_2030',2030,'autodeterminazione','self-determination','feminine',null,['Il principio di autodeterminazione.'],['b2']),
n('it_2031',2031,'decolonizzazione','decolonization','feminine',null,['Il processo di decolonizzazione.'],['b2']),
n('it_2032',2032,'imperialismo','imperialism','masculine',null,['L\'imperialismo occidentale.'],['b2']),
n('it_2033',2033,'colonialismo','colonialism','masculine',null,['Il colonialismo europeo.'],['b2']),
n('it_2034',2034,'neocolonialismo','neocolonialism','masculine',null,['Il neocolonialismo economico.'],['c1']),
n('it_2035',2035,'geopolitica','geopolitics','feminine',null,['La geopolitica moderna.'],['b2']),
n('it_2036',2036,'multilateralismo','multilateralism','masculine',null,['Il multilateralismo funziona.'],['c1']),
n('it_2037',2037,'bilateralismo','bilateralism','masculine',null,['Gli accordi bilaterali.'],['c1']),
n('it_2038',2038,'deterrenza','deterrence','feminine',null,['La deterrenza nucleare.'],['c1']),
n('it_2039',2039,'disarmo','disarmament','masculine',null,['Il disarmo nucleare.'],['b2']),
n('it_2040',2040,'proliferazione','proliferation','feminine','proliferazioni',['La proliferazione nucleare.'],['c1']),
n('it_2041',2041,'terrorismo','terrorism','masculine',null,['Il terrorismo internazionale.'],['b2']),
n('it_2042',2042,'fondamentalismo','fundamentalism','masculine',null,['Il fondamentalismo religioso.'],['b2']),
n('it_2043',2043,'radicalizzazione','radicalization','feminine',null,['La radicalizzazione on line.'],['b2']),
n('it_2044',2044,'estremismo','extremism','masculine',null,['L\'estremismo politico.'],['b2']),
n('it_2045',2045,'populismo','populism','masculine',null,['Il populismo cresce.'],['b2']),
n('it_2046',2046,'demagogia','demagogy','feminine',null,['La demagogia dei politici.'],['b2']),
n('it_2047',2047,'opportunismo','opportunism','masculine',null,['L\'opportunismo politico.'],['b2']),
n('it_2048',2048,'clientelismo','patronage','masculine',null,['Il clientelismo è diffuso.'],['b2']),
n('it_2049',2049,'nepotismo','nepotism','masculine',null,['Il nepotismo è inaccettabile.'],['b2']),
n('it_2050',2050,'corporativismo','corporatism','masculine',null,['Il corporativismo sindacale.'],['c1']),
n('it_2051',2051,'lobby','lobby','feminine','lobby',['Le lobby industriali.'],['b2']),
n('it_2052',2052,'gruppo di pressione','pressure group','masculine',null,['Un gruppo di pressione.'],['b2']),
n('it_2053',2053,'think tank','think tank','masculine','think tank',['Un think tank indipendente.'],['b2']),
n('it_2054',2054,'forum','forum','masculine','forum',['Un forum di discussione.'],['b2']),
n('it_2055',2055,'panel','panel','masculine','panel',['Un panel di esperti.'],['b2']),
n('it_2056',2056,'simposio','symposium','masculine','simposi',['Un simposio internazionale.'],['c1']),
n('it_2057',2057,'colloquio','colloquium/interview','masculine','colloqui',['Un colloquio accademico.'],['b2']),
n('it_2058',2058,'workshop','workshop','masculine','workshop',['Un workshop pratico.'],['b2']),
n('it_2059',2059,'webinar','webinar','masculine','webinar',['Partecipo a un webinar.'],['b2']),
n('it_2060',2060,'hackathon','hackathon','masculine','hackathon',['Un hackathon tecnologico.'],['b2']),
n('it_2061',2061,'ecosistema','ecosystem','masculine','ecosistemi',['L\'ecosistema digitale.'],['b2']),
n('it_2062',2062,'biodiversità','biodiversity','feminine',null,['La biodiversità è minacciata.'],['b2']),
n('it_2063',2063,'deforestazione','deforestation','feminine',null,['La deforestazione amazzonica.'],['b2']),
n('it_2064',2064,'desertificazione','desertification','feminine',null,['La desertificazione avanza.'],['b2']),
n('it_2065',2065,'cambiamento climatico','climate change','masculine',null,['Il cambiamento climatico è reale.'],['b2']),
n('it_2066',2066,'effetto serra','greenhouse effect','masculine',null,['L\'effetto serra aumenta.'],['b2']),
n('it_2067',2067,'gas serra','greenhouse gas','masculine','gas serra',['I gas serra sono pericolosi.'],['b2']),
n('it_2068',2068,'emissione','emission','feminine','emissioni',['Ridurre le emissioni.'],['b2']),
n('it_2069',2069,'impronta di carbonio','carbon footprint','feminine',null,['Riduci l\'impronta di carbonio.'],['b2']),
n('it_2070',2070,'sostenibilità','sustainability','feminine',null,['La sostenibilità ambientale.'],['b2']),
n('it_2071',2071,'rinnovabilità','renewability','feminine',null,['La rinnovabilità delle risorse.'],['b2']),
n('it_2072',2072,'eolico','wind (energy)','masculine',null,['L\'energia eolica.'],['b2']),
n('it_2073',2073,'solare','solar (energy)','masculine',null,['Il pannello solare.'],['b2']),
n('it_2074',2074,'geotermico','geothermal','masculine',null,['L\'energia geotermica.'],['c1']),
n('it_2075',2075,'idroelettrico','hydroelectric','masculine',null,['Una centrale idroelettrica.'],['c1']),
n('it_2076',2076,'nucleare','nuclear (energy)','masculine',null,['L\'energia nucleare è controversa.'],['b2']),
n('it_2077',2077,'trasizione energetica','energy transition','feminine',null,['La transizione energetica.'],['b2']),
n('it_2078',2078,'decarbonizzazione','decarbonization','feminine',null,['La decarbonizzazione dell\'economia.'],['b2']),
n('it_2079',2079,'neutralità carbonica','carbon neutrality','feminine',null,['Obiettivo di neutralità carbonica.'],['b2']),
n('it_2080',2080,'compensazione di carbonio','carbon offset','feminine',null,['La compensazione di carbonio.'],['b2']),
n('it_2081',2081,'economia circolare','circular economy','feminine',null,['L\'economia circolare.'],['b2']),
n('it_2082',2082,'upcycling','upcycling','masculine',null,['L\'upcycling dei materiali.'],['b2']),
n('it_2083',2083,'obsolescenza programmata','planned obsolescence','feminine',null,['L\'obsolescenza programmata.'],['b2']),
n('it_2084',2084,'consumismo','consumerism','masculine',null,['Il consumismo sfrenato.'],['b2']),
n('it_2085',2085,'materialismo','materialism','masculine',null,['Il materialismo moderno.'],['b2']),
n('it_2086',2086,'minimalismo','minimalism','masculine',null,['Il minimalismo nel design.'],['b2']),
n('it_2087',2087,'decrescita','degrowth','feminine',null,['La teoria della decrescita.'],['b2']),
n('it_2088',2088,'well-being','well-being','masculine',null,['Il benessere psicologico.'],['b2']),
n('it_2089',2089,'resilienza','resilience','feminine',null,['La resilienza della comunità.'],['b2']),
n('it_2090',2090,'antifragilità','antifragility','feminine',null,['Il concetto di antifragilità.'],['c1']),
n('it_2091',2091,'vulnerabilità','vulnerability','feminine',null,['La vulnerabilità del sistema.'],['b2']),
n('it_2092',2092,'fragilità','fragility','feminine',null,['La fragilità del sistema.'],['b2']),
n('it_2093',2093,'sostenibilità sociale','social sustainability','feminine',null,['La sostenibilità sociale.'],['b2']),
n('it_2094',2094,'coesione sociale','social cohesion','feminine',null,['La coesione sociale è importante.'],['b2']),
n('it_2095',2095,'mobilità sociale','social mobility','feminine',null,['La mobilità sociale è bassa.'],['b2']),
n('it_2096',2096,'ineguaglianza','inequality','feminine','ineguaglianze',['L\'ineguaglianza cresce.'],['b2']),
n('it_2097',2097,'divario','gap/divide','masculine','divari',['Il divario nord-sud.'],['b2']),
n('it_2098',2098,'digital divide','digital divide','masculine',null,['Il digital divide è reale.'],['b2']),
n('it_2099',2099,'esclusione digitale','digital exclusion','feminine',null,['L\'esclusione digitale degli anziani.'],['b2']),
n('it_2100',2100,'accesso equo','equitable access','masculine',null,['L\'accesso equo alla salute.'],['b2']),
// Adjectives 2101-2150
adj('it_2101',2101,'multidisciplinare','multidisciplinary','multidisciplinari',['Un approccio multidisciplinare.'],['b2']),
adj('it_2102',2102,'interdisciplinare','interdisciplinary','interdisciplinari',['Una ricerca interdisciplinare.'],['b2']),
adj('it_2103',2103,'transdisciplinare','transdisciplinary','transdisciplinari',['Un progetto transdisciplinare.'],['c1']),
adj('it_2104',2104,'olistico','holistic','olistici',['Una visione olistica.'],['b2']),
adj('it_2105',2105,'sistemico','systemic','sistemici',['Un problema sistemico.'],['b2']),
adj('it_2106',2106,'strutturale','structural','strutturali',['Una riforma strutturale.'],['b2']),
adj('it_2107',2107,'congiunturale','cyclical/conjunctural','congiunturali',['Una crisi congiunturale.'],['c1']),
adj('it_2108',2108,'ciclico','cyclical','ciclici',['Un andamento ciclico.'],['b2']),
adj('it_2109',2109,'stagnante','stagnant','stagnanti',['Un\'economia stagnante.'],['b2']),
adj('it_2110',2110,'recessivo','recessionary','recessivi',['Una fase recessiva.'],['b2']),
adj('it_2111',2111,'espansivo','expansive','espansivi',['Una politica espansiva.'],['c1']),
adj('it_2112',2112,'restrittivo','restrictive','restrittivi',['Una politica restrittiva.'],['c1']),
adj('it_2113',2113,'redistributivo','redistributive','redistributivi',['Una politica redistributiva.'],['c1']),
adj('it_2114',2114,'progressivo','progressive','progressivi',['Una tassa progressiva.'],['b2']),
adj('it_2115',2115,'regressivo','regressive','regressivi',['Una tassa regressiva.'],['c1']),
adj('it_2116',2116,'proporzionale','proportional — see 1431','proporzionali',['—'],['b1']),
adj('it_2117',2117,'sostenibile','sustainable','sostenibili',['Un modello sostenibile.'],['b2']),
adj('it_2118',2118,'insostenibile','unsustainable','insostenibili',['Un debito insostenibile.'],['b2']),
adj('it_2119',2119,'rinnovabile','renewable','rinnovabili',['Energia rinnovabile.'],['b2']),
adj('it_2120',2120,'esauribile','exhaustible','esauribili',['Risorse esauribili.'],['b2']),
adj('it_2121',2121,'biodegradabile','biodegradable','biodegradabili',['Materiali biodegradabili.'],['b2']),
adj('it_2122',2122,'eco-compatibile','eco-compatible','eco-compatibili',['Un prodotto eco-compatibile.'],['b2']),
adj('it_2123',2123,'ecologico','ecological','ecologici',['Un approccio ecologico.'],['b2']),
adj('it_2124',2124,'inquinante','polluting','inquinanti',['Sostanze inquinanti.'],['b2']),
adj('it_2125',2125,'tossico','toxic','tossici',['Una sostanza tossica.'],['b2']),
adj('it_2126',2126,'cancerogeno','carcinogenic','cancerogeni',['Una sostanza cancerogena.'],['b2']),
adj('it_2127',2127,'nocivo','harmful','nocivi',['Un effetto nocivo.'],['b2']),
adj('it_2128',2128,'benefico','beneficial','benefici',['Un effetto benefico.'],['b2']),
adj('it_2129',2129,'neutro','neutral — see 1178','neutri',['—'],['b1']),
adj('it_2130',2130,'virulento','virulent','virulenti',['Un virus virulento.'],['b2']),
adj('it_2131',2131,'pandemico','pandemic','pandemici',['Una crisi pandemica.'],['b2']),
adj('it_2132',2132,'epidemico','epidemic','epidemici',['Una diffusione epidemica.'],['b2']),
adj('it_2133',2133,'endemico','endemic','endemici',['Una malattia endemica.'],['b2']),
adj('it_2134',2134,'contagioso','contagious','contagiosi',['È molto contagioso.'],['b2']),
adj('it_2135',2135,'virulento','virulent — dup','virulenti',['—'],['b2']),
adj('it_2136',2136,'immunizzato','immunized','immunizzati',['La popolazione immunizzata.'],['b2']),
adj('it_2137',2137,'vaccinato','vaccinated','vaccinati',['Un bambino vaccinato.'],['b2']),
adj('it_2138',2138,'inattivo','inactive','inattivi',['Un vulcano inattivo.'],['b2']),
adj('it_2139',2139,'latente','latent','latenti',['Un conflitto latente.'],['b2']),
adj('it_2140',2140,'manifesto','manifest/obvious','manifesti',['Un\'intenzione manifesta.'],['b2']),
adj('it_2141',2141,'palese','evident/clear','palesi',['È palese.'],['b2']),
adj('it_2142',2142,'occulto','hidden/occult','occulti',['Poteri occulti.'],['b2']),
adj('it_2143',2143,'clandestino','clandestine','clandestini',['Un\'attività clandestina.'],['b2']),
adj('it_2144',2144,'sotterraneo','underground','sotterranei',['Un\'economia sotterranea.'],['b2']),
adj('it_2145',2145,'informale','informal — see 1169','informali',['—'],['a2']),
adj('it_2146',2146,'sommerso','submerged/underground','sommersi',['L\'economia sommersa.'],['b2']),
adj('it_2147',2147,'trasparente','transparent','trasparenti',['Un sistema trasparente.'],['b2']),
adj('it_2148',2148,'opaco','opaque','opachi',['Un sistema opaco.'],['b2']),
adj('it_2149',2149,'inequivocabile','unequivocal','inequivocabili',['Una risposta inequivocabile.'],['b2']),
adj('it_2150',2150,'ambiguo','ambiguous — see 1179','ambigui',['—'],['b1']),

// Adverbs 2151-2250
adv('it_2151',2151,'inequivocabilmente','unequivocally',['È inequivocabilmente sbagliato.'],['b2']),
adv('it_2152',2152,'incontrovertibilmente','incontrovertibly',['È incontrovertibilmente vero.'],['c1']),
adv('it_2153',2153,'categoricamente','categorically',['Rifiuto categoricamente.'],['b2']),
adv('it_2154',2154,'perentoriamente','peremptorily',['Ha risposto perentoriamente.'],['c1']),
adv('it_2155',2155,'incondizionatamente','unconditionally',['Lo supporto incondizionatamente.'],['b2']),
adv('it_2156',2156,'irrevocabilmente','irrevocably',['È irrevocabilmente perso.'],['b2']),
adv('it_2157',2157,'inesorabilmente','inexorably',['Avanza inesorabilmente.'],['c1']),
adv('it_2158',2158,'inevitabilmente','inevitably',['Inevitabilmente accadrà.'],['b2']),
adv('it_2159',2159,'sistematicamente','systematically',['Lavora sistematicamente.'],['b2']),
adv('it_2160',2160,'metodicamente','methodically',['Procede metodicamente.'],['b2']),
adv('it_2161',2161,'rigorosamente','rigorously',['Analizza rigorosamente.'],['b2']),
adv('it_2162',2162,'scrupolosamente','scrupulously',['Lavora scrupolosamente.'],['b2']),
adv('it_2163',2163,'meticolosamente','meticulously',['Controlla meticolosamente.'],['b2']),
adv('it_2164',2164,'accuratamente','accurately/carefully',['Esamina accuratamente.'],['b2']),
adv('it_2165',2165,'sommariamente','summarily',['È stato giudicato sommariamente.'],['c1']),
adv('it_2166',2166,'arbitrariamente','arbitrarily',['È deciso arbitrariamente.'],['b2']),
adv('it_2167',2167,'unilateralmente','unilaterally',['Ha deciso unilateralmente.'],['b2']),
adv('it_2168',2168,'bilateralmente','bilaterally',['Hanno concordato bilateralmente.'],['b2']),
adv('it_2169',2169,'multilateralmente','multilaterally',['Si accordano multilateralmente.'],['c1']),
adv('it_2170',2170,'consensualmente','consensually',['Hanno deciso consensualmente.'],['b2']),
adv('it_2171',2171,'democraticamente','democratically',['È stato eletto democraticamente.'],['b2']),
adv('it_2172',2172,'autoritariamente','authoritariamente',['Governa autoritariamente.'],['b2']),
adv('it_2173',2173,'trasparentemente','transparently',['Agisce trasparentemente.'],['b2']),
adv('it_2174',2174,'in modo fraudolento','fraudulently',['Ha agito in modo fraudolento.'],['b2']),
adv('it_2175',2175,'corruttamente','corruptly',['Ha agito corruttamente.'],['b2']),
adv('it_2176',2176,'eticamente','ethically — see 1249','eticamente',['—'],['b1']),
adv('it_2177',2177,'in buona fede','in good faith',['Ha agito in buona fede.'],['b2']),
adv('it_2178',2178,'in malafede','in bad faith',['Ha agito in malafede.'],['b2']),
adv('it_2179',2179,'intenzionalmente','intentionally — see 1488','intenzionalmente',['—'],['b1']),
adv('it_2180',2180,'con dolo','with malice/intent',['Ha agito con dolo.'],['c1']),
adv('it_2181',2181,'per colpa','through negligence',['È successo per colpa.'],['b2']),
adv('it_2182',2182,'fortuita mente','fortuitously',['È successo fortuitamente.'],['b2']),
adv('it_2183',2183,'casualmente','casually/accidentally',['L\'ho incontrato casualmente.'],['b2']),
adv('it_2184',2184,'incidentalmente','incidentally',['Incidentalmente, sapevi che?'],['b2']),
adv('it_2185',2185,'per inciso','incidentally/by the way',['Per inciso, è sbagliato.'],['b2']),
adv('it_2186',2186,'a titolo di esempio','by way of example',['A titolo di esempio.'],['b2']),
adv('it_2187',2187,'a mo\' di','by way of/in the manner of',['A mo\' di conclusione.'],['c1']),
adv('it_2188',2188,'in virtù di','by virtue of',['In virtù del contratto.'],['b2']),
adv('it_2189',2189,'in forza di','by force of','In forza di legge.',['b2']),
adv('it_2190',2190,'ai sensi di','pursuant to',['Ai sensi dell\'articolo 3.'],['c1']),
adv('it_2191',2191,'a norma di','in accordance with',['A norma di legge.'],['c1']),
adv('it_2192',2192,'in ottemperanza a','in compliance with',['In ottemperanza alle norme.'],['c1']),
adv('it_2193',2193,'nel rispetto di','in respect of',['Nel rispetto della legge.'],['b2']),
adv('it_2194',2194,'a detrimento di','to the detriment of',['A detrimento della salute.'],['c1']),
adv('it_2195',2195,'a scapito di','at the expense of',['A scapito della qualità.'],['b2']),
adv('it_2196',2196,'a vantaggio di','to the advantage of',['A vantaggio di tutti.'],['b2']),
adv('it_2197',2197,'a favore di','in favor of',['Si è espresso a favore.'],['b2']),
adv('it_2198',2198,'contro','against — see 248','contro',['—'],['a2']),
adv('it_2199',2199,'nell\'interesse di','in the interest of',['Nell\'interesse pubblico.'],['b2']),
adv('it_2200',2200,'per conto di','on behalf of',['Parla per conto dell\'azienda.'],['b2']),
adv('it_2201',2201,'in nome di','in the name of',['In nome della legge.'],['b2']),
adv('it_2202',2202,'per quanto riguarda','as regards',['Per quanto riguarda il prezzo.'],['b2']),
adv('it_2203',2203,'con riferimento a','with reference to',['Con riferimento alla sua lettera.'],['b2']),
adv('it_2204',2204,'in risposta a','in response to',['In risposta alla sua domanda.'],['b2']),
adv('it_2205',2205,'a seguire','to follow/next',['A seguire il discorso.'],['b2']),
adv('it_2206',2206,'di seguito','below/as follows',['Di seguito il testo.'],['b2']),
adv('it_2207',2207,'come indicato','as indicated',['Come indicato sopra.'],['b2']),
adv('it_2208',2208,'come previsto','as expected',['Come previsto, ha funzionato.'],['b2']),
adv('it_2209',2209,'come stabilito','as established',['Come stabilito dall\'accordo.'],['b2']),
adv('it_2210',2210,'come concordato','as agreed',['Come concordato, procedo.'],['b2']),
adv('it_2211',2211,'fatte salve le eccezioni','subject to exceptions',['Fatte salve le eccezioni.'],['c1']),
adv('it_2212',2212,'fatto salvo il diritto','reserving the right',['Fatto salvo il diritto di recesso.'],['c1']),
adv('it_2213',2213,'senza pregiudizio','without prejudice',['Senza pregiudizio alcuno.'],['c1']),
adv('it_2214',2214,'a pena di','under penalty of',['A pena di nullità.'],['c1']),
adv('it_2215',2215,'in deroga a','by way of derogation from',['In deroga alla norma.'],['c1']),
adv('it_2216',2216,'in via eccezionale','exceptionally',['In via eccezionale, sì.'],['b2']),
adv('it_2217',2217,'in via ordinaria','ordinarily',['In via ordinaria si fa così.'],['b2']),
adv('it_2218',2218,'in via straordinaria','in extraordinary manner',['In via straordinaria.'],['b2']),
adv('it_2219',2219,'in via provvisoria','provisionally',['In via provvisoria.'],['b2']),
adv('it_2220',2220,'in via definitiva','definitively',['In via definitiva.'],['b2']),
adv('it_2221',2221,'pro tempore','pro tempore',['Il presidente pro tempore.'],['c1']),
adv('it_2222',2222,'ad interim','ad interim',['Il ministro ad interim.'],['c1']),
adv('it_2223',2223,'ex officio','ex officio',['Membro ex officio.'],['c1']),
adv('it_2224',2224,'de facto','de facto',['Un\'autorità de facto.'],['b2']),
adv('it_2225',2225,'de iure','de jure',['Il riconoscimento de iure.'],['c1']),
adv('it_2226',2226,'erga omnes','towards all',['Un obbligo erga omnes.'],['c1']),
adv('it_2227',2227,'inter alia','among other things',['Inter alia, si è discusso.'],['c1']),
adv('it_2228',2228,'mutatis mutandis','with necessary changes',['Mutatis mutandis, vale anche qui.'],['c1']),
adv('it_2229',2229,'prima facie','at first sight',['Prima facie sembra corretto.'],['c1']),
adv('it_2230',2230,'sine die','without a date','La riunione è rinviata sine die.',['c1']),
adv('it_2231',2231,'pro rata','proportionally',['Il pagamento è pro rata.'],['c1']),
adv('it_2232',2232,'in abstracto','in the abstract',['Analizzare in abstracto.'],['c1']),
adv('it_2233',2233,'in concreto','in the concrete case',['Valutare in concreto.'],['c1']),
adv('it_2234',2234,'a fortiori','a fortiori/all the more so',['A fortiori questo vale.'],['c1']),
adv('it_2235',2235,'a contrario','by contrary reasoning',['Argomento a contrario.'],['c1']),
adv('it_2236',2236,'a priori','a priori',['Non si può sapere a priori.'],['b2']),
adv('it_2237',2237,'a posteriori','a posteriori',['Lo sappiamo a posteriori.'],['b2']),
adv('it_2238',2238,'in ultima analisi','in the final analysis',['In ultima analisi, dipende.'],['b2']),
adv('it_2239',2239,'tutto sommato','all things considered',['Tutto sommato, va bene.'],['b2']),
adv('it_2240',2240,'nel bene e nel male','for better or worse',['Nel bene e nel male, è così.'],['b2']),
adv('it_2241',2241,'alla fin fine','in the final end',['Alla fin fine, ha ragione.'],['b2']),
adv('it_2242',2242,'in definitiva','ultimately',['In definitiva, è positivo.'],['b2']),
adv('it_2243',2243,'a conti fatti','when all is said and done',['A conti fatti, vale la pena.'],['b2']),
adv('it_2244',2244,'al netto di','net of',['Al netto delle spese.'],['b2']),
adv('it_2245',2245,'al lordo di','gross of',['Al lordo delle imposte.'],['b2']),
adv('it_2246',2246,'su base mensile','on a monthly basis',['Pagamento su base mensile.'],['b2']),
adv('it_2247',2247,'su base annuale','on an annual basis',['Crescita su base annuale.'],['b2']),
adv('it_2248',2248,'su base trimestrale','on a quarterly basis',['Report su base trimestrale.'],['b2']),
adv('it_2249',2249,'anno su anno','year on year',['Crescita anno su anno.'],['b2']),
adv('it_2250',2250,'in termini reali','in real terms',['In termini reali è un calo.'],['b2']),
];

// ══════════════════════════════════════════════════════════════════════════════
// words-010.json  ranks 2251-2500  C1 level
// ══════════════════════════════════════════════════════════════════════════════
const e010=[
// Nouns 2251-2400
n('it_2251',2251,'assiologia','axiology','feminine',null,['L\'assiologia studia i valori.'],['c1']),
n('it_2252',2252,'gnoseologia','gnoseology','feminine',null,['La gnoseologia della conoscenza.'],['c1']),
n('it_2253',2253,'teleologia','teleology','feminine',null,['La teleologia aristotelica.'],['c1']),
n('it_2254',2254,'cosmologia','cosmology','feminine',null,['La cosmologia moderna.'],['c1']),
n('it_2255',2255,'escatologia','eschatology','feminine',null,['L\'escatologia cristiana.'],['c1']),
n('it_2256',2256,'eristica','eristics','feminine',null,['L\'arte dell\'eristica.'],['c1']),
n('it_2257',2257,'maieutica','maieutics','feminine',null,['Il metodo maieutico socratico.'],['c1']),
n('it_2258',2258,'dialogo socratico','Socratic dialogue','masculine',null,['Il dialogo socratico.'],['c1']),
n('it_2259',2259,'sillogismo','syllogism','masculine','sillogismi',['Un sillogismo valido.'],['c1']),
n('it_2260',2260,'sofisma','sophism','masculine','sofismi',['Un sofisma ingannevole.'],['c1']),
n('it_2261',2261,'fallacia','fallacy','feminine','fallace',['Una fallacia logica.'],['c1']),
n('it_2262',2262,'circolarità','circularity','feminine',null,['Il difetto della circolarità.'],['c1']),
n('it_2263',2263,'tautologia','tautology','feminine','tautologie',['È una tautologia.'],['c1']),
n('it_2264',2264,'aporia','aporia','feminine','aporie',['Un\'aporia irrisolvibile.'],['c1']),
n('it_2265',2265,'regressio ad infinitum','infinite regress','feminine',null,['Una regressione all\'infinito.'],['c1']),
n('it_2266',2266,'dilemma','dilemma','masculine','dilemmi',['Un dilemma etico.'],['b2']),
n('it_2267',2267,'trilemma','trilemma','masculine','trilemmi',['Un trilemma impossibile.'],['c1']),
n('it_2268',2268,'antinomia','antinomy','feminine','antinomie',['Un\'antinomia kantiana.'],['c1']),
n('it_2269',2269,'aporismo','aphorism','masculine','aforismi',['Un famoso aforisma.'],['c1']),
n('it_2270',2270,'massima','maxim','feminine','massime',['Una massima di vita.'],['c1']),
n('it_2271',2271,'aforisma','aphorism','masculine','aforismi',['Un aforisma di Nietzsche.'],['c1']),
n('it_2272',2272,'proverbio','proverb','masculine','proverbi',['Un antico proverbio.'],['a2']),
n('it_2273',2273,'detto','saying','masculine','detti',['Un vecchio detto.'],['a2']),
n('it_2274',2274,'idioma','idiom/language','masculine','idiomi',['Un idioma regionale.'],['b2']),
n('it_2275',2275,'dialetto','dialect','masculine','dialetti',['Il dialetto veneto.'],['b2']),
n('it_2276',2276,'gergo','jargon/slang','masculine','gerghi',['Il gergo tecnico.'],['b2']),
n('it_2277',2277,'gergale','slang (adj as noun)','masculine',null,['Espressione gergale.'],['b2']),
n('it_2278',2278,'arcaismo','archaism','masculine','arcaismi',['Un arcaismo letterario.'],['c1']),
n('it_2279',2279,'neologismo','neologism','masculine','neologismi',['Un neologismo della rete.'],['b2']),
n('it_2280',2280,'prestito linguistico','loanword','masculine',null,['Un prestito linguistico.'],['b2']),
n('it_2281',2281,'calco linguistico','calque','masculine',null,['Un calco dall\'inglese.'],['c1']),
n('it_2282',2282,'interferenza linguistica','linguistic interference','feminine',null,['L\'interferenza tra lingue.'],['c1']),
n('it_2283',2283,'code-switching','code-switching','masculine',null,['Il code-switching bilingue.'],['c1']),
n('it_2284',2284,'plurilinguismo','multilingualism','masculine',null,['Il plurilinguismo in Europa.'],['c1']),
n('it_2285',2285,'glottodidattica','language teaching','feminine',null,['La glottodidattica moderna.'],['c1']),
n('it_2286',2286,'acquisizione linguistica','language acquisition','feminine',null,['L\'acquisizione della L2.'],['c1']),
n('it_2287',2287,'interlingua','interlanguage','feminine',null,['L\'interlingua del parlante.'],['c1']),
n('it_2288',2288,'fossilizzazione','fossilization','feminine',null,['La fossilizzazione degli errori.'],['c1']),
n('it_2289',2289,'transfer linguistico','language transfer','masculine',null,['Il transfer dalla L1.'],['c1']),
n('it_2290',2290,'prosodia','prosody','feminine',null,['La prosodia dell\'italiano.'],['c1']),
n('it_2291',2291,'fonologia','phonology','feminine',null,['La fonologia italiana.'],['c1']),
n('it_2292',2292,'morfologia','morphology','feminine',null,['La morfologia nominale.'],['c1']),
n('it_2293',2293,'sintassi','syntax','feminine',null,['La sintassi della frase.'],['b2']),
n('it_2294',2294,'semantica','semantics','feminine',null,['La semantica lessicale.'],['b2']),
n('it_2295',2295,'pragmatica','pragmatics','feminine',null,['La pragmatica comunicativa.'],['b2']),
n('it_2296',2296,'lessicologia','lexicology','feminine',null,['La lessicologia italiana.'],['c1']),
n('it_2297',2297,'lessicografia','lexicography','feminine',null,['La lessicografia moderna.'],['c1']),
n('it_2298',2298,'metalinguaggio','metalanguage','masculine',null,['Il metalinguaggio della grammatica.'],['c1']),
n('it_2299',2299,'deissi','deixis','feminine',null,['La deissi spaziale.'],['c1']),
n('it_2300',2300,'anafora','anaphora','feminine','anafore',['Un\'anafora retorica.'],['c1']),
n('it_2301',2301,'catafora','cataphora','feminine','catafore',['Una catafora testuale.'],['c1']),
n('it_2302',2302,'ellissi','ellipsis','feminine','ellissi',['Un\'ellissi grammaticale.'],['c1']),
n('it_2303',2303,'polisemia','polysemy','feminine',null,['La polisemia del termine.'],['c1']),
n('it_2304',2304,'omonimia','homonymy','feminine',null,['L\'omonimia crea confusione.'],['c1']),
n('it_2305',2305,'sinonimia','synonymy','feminine',null,['La sinonimia nel lessico.'],['c1']),
n('it_2306',2306,'antinomia','antonomy/antinomy','feminine','antinomie',['Un\'antinomia semantica.'],['c1']),
n('it_2307',2307,'iponimia','hyponymy','feminine',null,['La relazione di iponimia.'],['c1']),
n('it_2308',2308,'iperonimia','hyperonymy','feminine',null,['La relazione di iperonimia.'],['c1']),
n('it_2309',2309,'campo semantico','semantic field','masculine',null,['Il campo semantico del cibo.'],['b2']),
n('it_2310',2310,'rete semantica','semantic network','feminine',null,['Una rete semantica.'],['c1']),
n('it_2311',2311,'frame semantico','semantic frame','masculine',null,['Un frame semantico complesso.'],['c1']),
n('it_2312',2312,'schema cognitivo','cognitive schema','masculine',null,['Lo schema cognitivo.'],['c1']),
n('it_2313',2313,'prototipo cognitivo','cognitive prototype','masculine',null,['Il prototipo categoriale.'],['c1']),
n('it_2314',2314,'categorizzazione','categorization','feminine','categorizzazioni',['La categorizzazione concettuale.'],['c1']),
n('it_2315',2315,'concettualizzazione','conceptualization','feminine',null,['La concettualizzazione del spazio.'],['c1']),
n('it_2316',2316,'metafora concettuale','conceptual metaphor','feminine',null,['La teoria della metafora concettuale.'],['c1']),
n('it_2317',2317,'blending concettuale','conceptual blending','masculine',null,['Il blending concettuale.'],['c1']),
n('it_2318',2318,'spazio mentale','mental space','masculine',null,['I spazi mentali di Fauconnier.'],['c1']),
n('it_2319',2319,'embodiment','embodiment','masculine',null,['L\'embodiment cognitivo.'],['c1']),
n('it_2320',2320,'enattivismo','enactivism','masculine',null,['L\'enattivismo di Varela.'],['c1']),
n('it_2321',2321,'neuropragmatica','neuropragmatics','feminine',null,['La neuropragmatica.'],['c1']),
n('it_2322',2322,'neuroplasticità','neuroplasticity','feminine',null,['La neuroplasticità del cervello.'],['c1']),
n('it_2323',2323,'sinaptogenesi','synaptogenesis','feminine',null,['La sinaptogenesi neonatale.'],['c1']),
n('it_2324',2324,'mielinizzazione','myelination','feminine',null,['La mielinizzazione delle fibre.'],['c1']),
n('it_2325',2325,'potenziamento a lungo termine','long-term potentiation','masculine',null,['Il potenziamento a lungo termine.'],['c1']),
n('it_2326',2326,'memoria di lavoro','working memory','feminine',null,['La capacità della memoria di lavoro.'],['c1']),
n('it_2327',2327,'memoria procedurale','procedural memory','feminine',null,['La memoria procedurale è implicita.'],['c1']),
n('it_2328',2328,'memoria dichiarativa','declarative memory','feminine',null,['La memoria dichiarativa.'],['c1']),
n('it_2329',2329,'memoria episodica','episodic memory','feminine',null,['La memoria episodica autobiografica.'],['c1']),
n('it_2330',2330,'memoria semantica','semantic memory','feminine',null,['La memoria semantica del lessico.'],['c1']),
n('it_2331',2331,'attenzione selettiva','selective attention','feminine',null,['L\'attenzione selettiva.'],['c1']),
n('it_2332',2332,'funzioni esecutive','executive functions','feminine',null,['Le funzioni esecutive prefrontali.'],['c1']),
n('it_2333',2333,'metacognizione','metacognition','feminine',null,['La metacognizione nell\'apprendimento.'],['c1']),
n('it_2334',2334,'autoregolazione','self-regulation','feminine',null,['La capacità di autoregolazione.'],['c1']),
n('it_2335',2335,'automonitoraggio','self-monitoring','masculine',null,['L\'automonitoraggio cognitivo.'],['c1']),
n('it_2336',2336,'autoefficacia','self-efficacy','feminine',null,['Il senso di autoefficacia.'],['c1']),
n('it_2337',2337,'locus of control','locus of control','masculine',null,['Il locus of control interno.'],['c1']),
n('it_2338',2338,'attribuzione causale','causal attribution','feminine',null,['La teoria dell\'attribuzione causale.'],['c1']),
n('it_2339',2339,'bias cognitivo','cognitive bias','masculine',null,['Il confirmation bias.'],['b2']),
n('it_2340',2340,'euristica','heuristic','feminine','euristiche',['L\'euristica della disponibilità.'],['c1']),
n('it_2341',2341,'ancoraggio','anchoring','masculine',null,['Il bias di ancoraggio.'],['c1']),
n('it_2342',2342,'effetto alone','halo effect','masculine',null,['L\'effetto alone nella valutazione.'],['c1']),
n('it_2343',2343,'fallacia del giocatore','gambler\'s fallacy','feminine',null,['La fallacia del giocatore.'],['c1']),
n('it_2344',2344,'pensiero critico','critical thinking','masculine',null,['Il pensiero critico è essenziale.'],['b2']),
n('it_2345',2345,'problem-solving','problem-solving','masculine',null,['Il problem-solving creativo.'],['b2']),
n('it_2346',2346,'pensiero laterale','lateral thinking','masculine',null,['Il pensiero laterale di De Bono.'],['b2']),
n('it_2347',2347,'brainstorming','brainstorming','masculine',null,['Una sessione di brainstorming.'],['b2']),
n('it_2348',2348,'design thinking','design thinking','masculine',null,['Il metodo del design thinking.'],['b2']),
n('it_2349',2349,'agile','agile methodology','masculine',null,['Il metodo agile.'],['b2']),
n('it_2350',2350,'scrum','scrum','masculine',null,['Usiamo la metodologia scrum.'],['b2']),
n('it_2351',2351,'sprint','sprint','masculine','sprint',['Uno sprint di due settimane.'],['b2']),
n('it_2352',2352,'backlog','backlog','masculine','backlog',['Il backlog del prodotto.'],['b2']),
n('it_2353',2353,'retrospettiva','retrospective','feminine','retrospettive',['La retrospettiva dello sprint.'],['b2']),
n('it_2354',2354,'user story','user story','feminine','user story',['Una user story ben scritta.'],['b2']),
n('it_2355',2355,'acceptance criteria','acceptance criteria','masculine',null,['I criteri di accettazione.'],['b2']),
n('it_2356',2356,'MVP','MVP (minimum viable product)','masculine',null,['Rilasciamo il MVP.'],['b2']),
n('it_2357',2357,'prova di concetto','proof of concept','feminine',null,['Una prova di concetto.'],['b2']),
n('it_2358',2358,'scalabilità','scalability','feminine',null,['La scalabilità del sistema.'],['b2']),
n('it_2359',2359,'interoperabilità','interoperability','feminine',null,['L\'interoperabilità dei sistemi.'],['b2']),
n('it_2360',2360,'latenza','latency','feminine',null,['La latenza della rete.'],['b2']),
n('it_2361',2361,'throughput','throughput','masculine',null,['Il throughput del sistema.'],['b2']),
n('it_2362',2362,'disponibilità','availability','feminine',null,['La disponibilità del servizio.'],['b2']),
n('it_2363',2363,'affidabilità','reliability','feminine',null,['L\'affidabilità del sistema.'],['b2']),
n('it_2364',2364,'manutenibilità','maintainability','feminine',null,['La manutenibilità del codice.'],['b2']),
n('it_2365',2365,'sicurezza informatica','cybersecurity','feminine',null,['La sicurezza informatica è cruciale.'],['b2']),
n('it_2366',2366,'crittografia','cryptography','feminine',null,['La crittografia asimmetrica.'],['b2']),
n('it_2367',2367,'autenticazione a due fattori','two-factor authentication','feminine',null,['Usa l\'autenticazione a due fattori.'],['b2']),
n('it_2368',2368,'phishing','phishing','masculine',null,['Un attacco di phishing.'],['b2']),
n('it_2369',2369,'malware','malware','masculine',null,['Un malware pericoloso.'],['b2']),
n('it_2370',2370,'ransomware','ransomware','masculine',null,['Un attacco ransomware.'],['b2']),
n('it_2371',2371,'vulnerabilità','vulnerability','feminine',null,['Una vulnerabilità zero-day.'],['b2']),
n('it_2372',2372,'exploit','exploit','masculine','exploit',['Un exploit critico.'],['b2']),
n('it_2373',2373,'patch','patch','feminine','patch',['Installa la patch.'],['b2']),
n('it_2374',2374,'aggiornamento di sicurezza','security update','masculine',null,['Installa l\'aggiornamento di sicurezza.'],['b2']),
n('it_2375',2375,'GDPR','GDPR','masculine',null,['Il GDPR tutela i dati.'],['b2']),
n('it_2376',2376,'trattamento dei dati','data processing','masculine',null,['Il trattamento dei dati personali.'],['b2']),
n('it_2377',2377,'titolare del trattamento','data controller','masculine',null,['Il titolare del trattamento.'],['c1']),
n('it_2378',2378,'responsabile del trattamento','data processor','masculine',null,['Il responsabile del trattamento.'],['c1']),
n('it_2379',2379,'consenso informato','informed consent','masculine',null,['Il consenso informato al trattamento.'],['b2']),
n('it_2380',2380,'diritto all\'oblio','right to be forgotten','masculine',null,['Il diritto all\'oblio.'],['b2']),
n('it_2381',2381,'portabilità dei dati','data portability','feminine',null,['La portabilità dei dati.'],['b2']),
n('it_2382',2382,'anonimizzazione','anonymization','feminine',null,['L\'anonimizzazione dei dati.'],['b2']),
n('it_2383',2383,'pseudonimizzazione','pseudonymization','feminine',null,['La pseudonimizzazione.'],['c1']),
n('it_2384',2384,'profilazione','profiling','feminine',null,['La profilazione dell\'utente.'],['b2']),
n('it_2385',2385,'algoritmo raccomandativo','recommendation algorithm','masculine',null,['L\'algoritmo raccomandativo.'],['b2']),
n('it_2386',2386,'camera d\'eco','echo chamber','feminine',null,['La camera d\'eco dei social.'],['b2']),
n('it_2387',2387,'bolla informativa','information bubble','feminine',null,['La bolla informativa on line.'],['b2']),
n('it_2388',2388,'disinformazione','disinformation','feminine',null,['La disinformazione è pericolosa.'],['b2']),
n('it_2389',2389,'misinformazione','misinformation','feminine',null,['La misinformazione si diffonde.'],['b2']),
n('it_2390',2390,'fact-checking','fact-checking','masculine',null,['Il fact-checking è necessario.'],['b2']),
n('it_2391',2391,'debunking','debunking','masculine',null,['Il debunking delle fake news.'],['b2']),
n('it_2392',2392,'fake news','fake news','feminine','fake news',['Le fake news si diffondono.'],['b2']),
n('it_2393',2393,'deep fake','deep fake','masculine','deep fake',['Un deep fake video.'],['b2']),
n('it_2394',2394,'astroturfing','astroturfing','masculine',null,['Una campagna di astroturfing.'],['c1']),
n('it_2395',2395,'bot','bot','masculine','bot',['Un bot automatizzato.'],['b2']),
n('it_2396',2396,'algoritmo','algorithm — see 1085','masculine','algoritmi',['—'],['b1']),
n('it_2397',2397,'apprendimento automatico','machine learning','masculine',null,['L\'apprendimento automatico.'],['b2']),
n('it_2398',2398,'rete neurale','neural network','feminine',null,['Una rete neurale artificiale.'],['b2']),
n('it_2399',2399,'deep learning','deep learning','masculine',null,['Il deep learning avanza.'],['b2']),
n('it_2400',2400,'modello linguistico di grandi dimensioni','large language model','masculine',null,['Un modello linguistico di grandi dimensioni.'],['b2']),

// Adjectives 2401-2450
adj('it_2401',2401,'deterministico','deterministic','deterministici',['Un sistema deterministico.'],['c1']),
adj('it_2402',2402,'stocastico','stochastic','stocastici',['Un processo stocastico.'],['c1']),
adj('it_2403',2403,'probabilistico','probabilistic','probabilistici',['Un approccio probabilistico.'],['c1']),
adj('it_2404',2404,'bayesiano','Bayesian','bayesiani',['L\'inferenza bayesiana.'],['c1']),
adj('it_2405',2405,'frequentista','frequentist','frequentisti',['L\'approccio frequentista.'],['c1']),
adj('it_2406',2406,'non parametrico','non-parametric','non parametrici',['Un test non parametrico.'],['c1']),
adj('it_2407',2407,'parametrico','parametric','parametrici',['Un modello parametrico.'],['c1']),
adj('it_2408',2408,'asintomatico','asymptomatic','asintomatici',['Un caso asintomatico.'],['b2']),
adj('it_2409',2409,'sintomatico','symptomatic','sintomatici',['Un caso sintomatico.'],['b2']),
adj('it_2410',2410,'patognomico','pathognomonic','patognomonici',['Un segno patognomico.'],['c1']),
adj('it_2411',2411,'idiopatico','idiopathic','idiopatici',['Una malattia idiopatica.'],['c1']),
adj('it_2412',2412,'iatrogeno','iatrogenic','iatrogeni',['Un effetto iatrogeno.'],['c1']),
adj('it_2413',2413,'nosologico','nosological','nosologici',['Una categoria nosologica.'],['c1']),
adj('it_2414',2414,'eziopatogenetico','etiopathogenetic','eziopatogenetici',['Il processo eziopatogenetico.'],['c1']),
adj('it_2415',2415,'multifattoriale','multifactorial','multifattoriali',['Una causa multifattoriale.'],['c1']),
adj('it_2416',2416,'comorbido','comorbid','comorbidi',['Condizioni comorbide.'],['c1']),
adj('it_2417',2417,'refrattario','refractory','refrattari',['Un caso refrattario.'],['c1']),
adj('it_2418',2418,'benigno','benign','benigni',['Un tumore benigno.'],['b2']),
adj('it_2419',2419,'maligno','malignant','maligni',['Un tumore maligno.'],['b2']),
adj('it_2420',2420,'cronico','chronic','cronici',['Una malattia cronica.'],['b2']),
adj('it_2421',2421,'acuto','acute','acuti',['Una fase acuta.'],['b2']),
adj('it_2422',2422,'subacuto','subacute','subacuti',['Una fase subacuta.'],['c1']),
adj('it_2423',2423,'recidivante','relapsing','recidivanti',['Una malattia recidivante.'],['c1']),
adj('it_2424',2424,'progressivo','progressive — see 1236','progressivi',['—'],['b1']),
adj('it_2425',2425,'regressivo','regressive — see 2115','regressivi',['—'],['c1']),
adj('it_2426',2426,'stazionario','stationary','stazionari',['Un quadro clinico stazionario.'],['c1']),
adj('it_2427',2427,'asimmetrico','asymmetric','asimmetrici',['Una distribuzione asimmetrica.'],['c1']),
adj('it_2428',2428,'simmetrico','symmetric','simmetrici',['Una distribuzione simmetrica.'],['c1']),
adj('it_2429',2429,'omogeneo','homogeneous','omogenei',['Un gruppo omogeneo.'],['c1']),
adj('it_2430',2430,'eterogeneo','heterogeneous','eterogenei',['Un campione eterogeneo.'],['c1']),
adj('it_2431',2431,'isotropo','isotropic','isotropi',['Un mezzo isotropo.'],['c1']),
adj('it_2432',2432,'anisotropo','anisotropic','anisotropi',['Un cristallo anisotropo.'],['c1']),
adj('it_2433',2433,'complesso','complex','complessi',['Un sistema complesso.'],['b2']),
adj('it_2434',2434,'complicato','complicated','complicati',['Un problema complicato.'],['b2']),
adj('it_2435',2435,'caotico','chaotic','caotici',['Un sistema caotico.'],['b2']),
adj('it_2436',2436,'deterministico','deterministic — dup','deterministici',['—'],['c1']),
adj('it_2437',2437,'emergente','emergent','emergenti',['Una proprietà emergente.'],['c1']),
adj('it_2438',2438,'auto-organizzante','self-organizing','auto-organizzanti',['Un sistema auto-organizzante.'],['c1']),
adj('it_2439',2439,'adattivo','adaptive','adattivi',['Un sistema adattivo.'],['c1']),
adj('it_2440',2440,'retroattivo','retroactive','retroattivi',['Effetto retroattivo.'],['c1']),
adj('it_2441',2441,'proattivo','proactive','proattivi',['Un approccio proattivo.'],['b2']),
adj('it_2442',2442,'reattivo','reactive','reattivi',['Un approccio reattivo.'],['b2']),
adj('it_2443',2443,'riflessivo','reflective','riflessivi',['Una risposta riflessiva.'],['b2']),
adj('it_2444',2444,'impulsivo','impulsive','impulsivi',['Una risposta impulsiva.'],['b2']),
adj('it_2445',2445,'deliberato','deliberate','deliberati',['Una scelta deliberata.'],['b2']),
adj('it_2446',2446,'spontaneo','spontaneous','spontanei',['Una reazione spontanea.'],['b2']),
adj('it_2447',2447,'automatico','automatic','automatici',['Un processo automatico.'],['b2']),
adj('it_2448',2448,'consapevole','conscious/aware','consapevoli',['Una scelta consapevole.'],['b2']),
adj('it_2449',2449,'inconsapevole','unaware','inconsapevoli',['Lo fa in modo inconsapevole.'],['b2']),
adj('it_2450',2450,'esplicito','explicit — see 1680','espliciti',['—'],['b1']),

// Adverbs 2451-2500
adv('it_2451',2451,'ontologicamente','ontologically',['È ontologicamente diverso.'],['c1']),
adv('it_2452',2452,'epistemologicamente','epistemologically',['È epistemologicamente valido.'],['c1']),
adv('it_2453',2453,'fenomenologicamente','phenomenologically',['È fenomenologicamente significativo.'],['c1']),
adv('it_2454',2454,'ermeneuticamente','hermeneutically',['È ermeneuticamente complesso.'],['c1']),
adv('it_2455',2455,'dialetticamente','dialectically',['Si pone dialetticamente.'],['c1']),
adv('it_2456',2456,'strutturalmente','structurally',['È strutturalmente simile.'],['b2']),
adv('it_2457',2457,'funzionalmente','functionally',['È funzionalmente equivalente.'],['b2']),
adv('it_2458',2458,'semanticamente','semantically',['È semanticamente ambiguo.'],['b2']),
adv('it_2459',2459,'pragmaticamente','pragmatically',['È pragmaticamente inutile.'],['b2']),
adv('it_2460',2460,'morfologicamente','morphologically',['È morfologicamente complesso.'],['c1']),
adv('it_2461',2461,'sintatticamente','syntactically',['È sintatticamente corretto.'],['c1']),
adv('it_2462',2462,'fonologicamente','phonologically',['È fonologicamente simile.'],['c1']),
adv('it_2463',2463,'cognitivamente','cognitively',['È cognitivamente impegnativo.'],['c1']),
adv('it_2464',2464,'neurologicamente','neurologically',['È neurologicamente correlato.'],['c1']),
adv('it_2465',2465,'psicologicamente','psychologically',['È psicologicamente stressante.'],['b2']),
adv('it_2466',2466,'sociologicamente','sociologically',['È sociologicamente rilevante.'],['c1']),
adv('it_2467',2467,'antropologicamente','anthropologically',['È antropologicamente interessante.'],['c1']),
adv('it_2468',2468,'storicamente','historically — see 661','storicamente',['—'],['b1']),
adv('it_2469',2469,'geneticamente','genetically',['È geneticamente determinato.'],['b2']),
adv('it_2470',2470,'epigeneticamente','epigenetically',['È epigeneticamente modulabile.'],['c1']),
adv('it_2471',2471,'evolutivamente','evolutionarily',['È evolutivamente vantaggioso.'],['c1']),
adv('it_2472',2472,'adattativamente','adaptively',['Risponde adattativamente.'],['c1']),
adv('it_2473',2473,'omeostaticamente','homeostatically',['Il corpo regola omeostaticamente.'],['c1']),
adv('it_2474',2474,'metabolicamente','metabolically',['È metabolicamente attivo.'],['c1']),
adv('it_2475',2475,'fisiologicamente','physiologically',['È fisiologicamente normale.'],['c1']),
adv('it_2476',2476,'patologicamente','pathologically',['È patologicamente alterato.'],['c1']),
adv('it_2477',2477,'iatrogena mente','iatrogenically',['È causato iatrogena mente.'],['c1']),
adv('it_2478',2478,'farmacologicamente','pharmacologically',['È farmacologicamente attivo.'],['c1']),
adv('it_2479',2479,'terapeuticamente','therapeutically',['È terapeuticamente efficace.'],['c1']),
adv('it_2480',2480,'chirurgicamente','surgically',['È trattato chirurgicamente.'],['c1']),
adv('it_2481',2481,'clinicamente','clinically',['È clinicamente significativo.'],['b2']),
adv('it_2482',2482,'statisticamente','statistically — see 1498','statisticamente',['—'],['b1']),
adv('it_2483',2483,'epidemiologicamente','epidemiologically',['È epidemiologicamente rilevante.'],['c1']),
adv('it_2484',2484,'demograficamente','demographically',['È demograficamente in calo.'],['b2']),
adv('it_2485',2485,'geopoliticamente','geopolitically',['È geopoliticamente sensibile.'],['b2']),
adv('it_2486',2486,'diplomaticamente','diplomatically',['È diplomaticamente irrisolvibile.'],['b2']),
adv('it_2487',2487,'militarmente','militarily',['È militarmente insostenibile.'],['b2']),
adv('it_2488',2488,'economicamente','economically — see 664','economicamente',['—'],['b1']),
adv('it_2489',2489,'commercialmente','commercially',['È commercialmente vantaggioso.'],['b2']),
adv('it_2490',2490,'industrialmente','industrially',['È industrialmente maturo.'],['b2']),
adv('it_2491',2491,'tecnologicamente','technologically',['È tecnologicamente avanzato.'],['b2']),
adv('it_2492',2492,'digitalmente','digitally',['È digitalmente nativo.'],['b2']),
adv('it_2493',2493,'algoritmicamente','algorithmically',['È generato algoritmicamente.'],['b2']),
adv('it_2494',2494,'computazionalmente','computationally',['È computazionalmente costoso.'],['b2']),
adv('it_2495',2495,'informaticamente','in computing terms',['È informaticamente sicuro.'],['b2']),
adv('it_2496',2496,'ciberneticamente','cybernetically',['È ciberneticamente connesso.'],['c1']),
adv('it_2497',2497,'virtualmente','virtually — see 1702','virtualmente',['—'],['b1']),
adv('it_2498',2498,'nella fattispecie','in the specific case',['Nella fattispecie, non vale.'],['c1']),
adv('it_2499',2499,'nel caso di specie','in the case at hand',['Nel caso di specie, la norma.'],['c1']),
adv('it_2500',2500,'in conclusione','in conclusion — see 1217','in conclusione',['—'],['b1']),
];

function filterAndWrite(arr, outFile, label){
  const final=arr.filter(x=>!x.examples[0].startsWith('—'));
  console.log(`${label}: ${final.length} entries, ranks ${final[0].rank}-${final[final.length-1].rank}`);
  const ranks=final.map(x=>x.rank);
  const dups=ranks.filter((r,i)=>ranks.indexOf(r)!==i);
  if(dups.length) console.warn('Dups:',dups);
  fs.writeFileSync(path.join(__dirname,`../src/data/${outFile}`),JSON.stringify(final,null,2));
  console.log(`${outFile} written.`);
}

filterAndWrite(e008,'words-008.json','words-008');
filterAndWrite(e009,'words-009.json','words-009');
filterAndWrite(e010,'words-010.json','words-010');
